### ISSUE TITLE
Variables from query initBindings ignored in CONSTRUCT body

### ISSUE THREAD

**Issue by sa-bpelakh** [RDFLib/rdflib#1001]
If I feed a `CONSTRUCT` query with some initial bindings, e.g.
```python
query = """
prefix ex: <http://example.com/>
CONSTRUCT {
  ?uri ex:prop1 ?val1;
       ex:prop2 ?c .
}
WHERE {
  bind(uri(concat("http://example.com/", ?a)) as ?uri)
  bind(?b as ?val1)
}
"""
graph = rdflib.Graph()
results = graph.query(query, initBindings={
  'a': graph.Literal('A'),
  'b': graph.Literal('B'),
  'c': graph.Literal('C')
})
```
then I will get a single triple back (`ex:A ex:prop1 "B"`), because it uses variables that are bound in the `WHERE` block, but I will not get back `ex:A ex:prop2 "C"`, because the `?c` binding is not propagated into the `CONSTRUCT` evaluation.
If I modify the query as follows, it works fine:
```python
query = """
prefix ex: <http://example.com/>
CONSTRUCT {
  ?uri ex:prop1 ?val1;
       ex:prop2 ?val2 .
}
WHERE {
  bind(uri(concat("http://example.com/", ?a)) as ?uri)
  bind(?b as ?val1)
  bind(?c as ?val2)
}
"""
```
Is this is not WAI, would love to help on  a fix, trying to learn this code base.

**Comment by white-gecko** [comment]
Thank you for reporting this. I'm not sure if this is dealt with in the SPARQL specification, at least I could not find anything about it. The RDFlib documentation is not specific about this case. In my eyes it is fine as it is. Also there is a solution for your use case, as you have presented it already and which is very straight forward.
Do you know of other libraries dealing with this situation in another way?

For me this is nothing that needs to be solved, so I put it to out-of-scope. If you have any argument for bringing it into the scope of the rdflib we can change that. If you agree with my points please close it.

What does WAI stand for? https://www.w3.org/WAI/ ?

You are welcome to contributing to the code base. To get into it there are some "good first issues" which might help with this: https://github.com/RDFLib/rdflib/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by sa-bpelakh** [comment]
@white-gecko WAI stands for 'Working As Intended'. And you are right, there is not really a standard behavior to test here - it's just particularly useful for my use case (where I use a CSV file to feed the bindings, evaluating the `CONSTRUCT` once per each line in a CSV to build up a graph). 

I will probably try and take a shot at fixing it, and see how successful I am, but as you stated, there is a pretty easy workaround.
