### ISSUE TITLE
Question: How do I set the rdfs:isDefinedBy for all resources in my graph?

### ISSUE THREAD

**Issue by DanielBakas** [RDFLib/rdflib#1013]
Hi there!

I would like to modify a property for all resources in my graph which I generated from parsing a file. I then want to save the modified graph into a new file. 

Is there an easy way to do this?

Thanks!

Daniel

**Comment by white-gecko** [comment]
Yes, there is. But please ask this on Sack Overflow.

Close.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by DanielBakas** [comment]
Ok great! Thanks!

**Comment by nicholascar** [comment]
Now at https://stackoverflow.com/questions/61278691/how-do-i-set-the-rdfsisdefinedby-for-all-resources-in-my-rdflib-graph
