### ISSUE TITLE
Missing Content-Type header for SPARQLConnector update method (?)

### ISSUE THREAD

**Issue by NoutieH** [RDFLib/rdflib#1021]
In rdflib 4.2.2 the SPARQLWrapper added an applicable content-type header when sending queries and updates to a SPARQL endpoint.
The 5.0.0 the SPARQLConnector does not add a content-type and, since the GraphDB we use as SPARQL endpoint rejects update requests when Content-Type: application/sparql-update is not added to the header, I had to monkey patch the update method to forcebily add the content type to the header.

I also tried to add a headers parameter with the content-type to the SPARQLUpdateStore parameter when constructing a SPARQLUpdateStore instance, but this then the content type is also used for query request, which results in rejected query requests in case the store instance is used for querying.

Should the the content type be added by the SPARQLConnector like the SPARQLWrapper did or am i missing an other intended solution?

Best regards,
Arnoud

**Comment by nicholascar** [comment]
Hi @NoutieH, I know there have been several issues raised recently about the `SPARQLUpdateStore` so I think that's going to have to be looked at closely soon.

> Should the the content type be added by the SPARQLConnector like the SPARQLWrapper did or am i missing an other intended solution?

I'm not aware of the original design - wasn't involved then and someone else may comment - but you'd think `SPARQLConnector` should be using the correct headers! If `SPARQLWrapper` has it correctly, this should just follow.

I see `SPARQLStore` & `SPARQLUpdateStore` both using `SPARQLConnector` so I suppose a fix to `SPARQLConnector` will be correct for all

> I had to monkey patch the update method...

If you have this working, would you consider raising a Pull Request with your fix for `SPARQLConnector`? I'd be happy to review and merge.

**Comment by NoutieH** [comment]
I first wanted to find out the intensions of the changes, but I also think the content type should be added by the SPARQLConnector. I'll setup a PR, but maybe not today. Basically it came down to this (SPARQLConnector.update(..), ln: 119):

```
        headers = {
            "Accept": _response_mime_types[self.returnFormat],
            "Content-Type": "application/sparql-update",
        }
```

**Comment by nicholascar** [comment]
I thought it might just be a one- or two-liner like that! Very keen for other people to submit these sorts of PRs though: great to have the community all involved and there's a higher likelihood of good code if it's external then reviewed as that removes the chance of cor dev GroupThink!
