### ISSUE TITLE
Graph.update with SPARQLStore should return Exception

### ISSUE THREAD

**Issue by white-gecko** [RDFLib/rdflib#1032]
When I instantiate a `Graph` with the `SPARQLStore` and call `query()` on it I get:

    TypeError: update() takes from 2 to 3 positional arguments but 5 were given

while I would expect an Exception.

Reproduce it with:

    from rdflib import Graph
    graph = Graph(store="SPARQLStore")
    graph.update("insert data {graph <urn:ex> {<urn:s> <urn:p> <urn:o>}}")

This is caused by the fact, that the `SPARQLStore` inherits from `SPARQLConnector`:

    class SPARQLStore(SPARQLConnector, Store):

Two issues:

- Why does `SPARQLStore` inherit from `SPARQLConnector`?
- The `SPARQLStore` should define `update` and return en Exception.

**Comment by nicholascar** [comment]
> The `SPARQLStore` should define `update` and return en Exception.

Agree. I think a few people trip up on this - `SPARQLStore`  is read-only - so returning an error would be best to make it clear.

**Comment by white-gecko** [comment]
Do you see any reason, why SPARQLStore should inherit from SPARQLConnector? Maybe it is better to just instantiate a SPARQLConnector and use it in the SPARQLStore. That would provide a clearer structure in my eyes.
