### ISSUE TITLE
pip install rdflib doesn't install all dependencies

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#1035]
When I install rdflib with pip:

```
pip install rdflib
```

I don't get `requests` installed, even though it's in the *requirements.txt* file. 

Is this correct behaviour?

**Comment by tgbugs** [comment]
Yes it is correct. You have to install with `pip install rdflib[sparql]` because requests is an extra requirement. There is a bug though which is that requests probably needs to be added to tests_require.

**Comment by nicholascar** [comment]
I think I just never noticed before because I’ve always installed `requests` with `rdflib` because I tend to be doing HTTP actions in my APIs and always have needed it anyway.

We can re-examine all dependencies as we remove the Py 2/3 requirements like `six` now that Py 2 is gone.

**Comment by tgbugs** [comment]
Related: https://github.com/RDFLib/rdflib/pull/969

**Comment by white-gecko** [comment]
Yes I had added it for sparql in #969 already, but it was also missing for the tests which should be fixed in #1036.
