### ISSUE TITLE
Wikidata rdfxml dumps with wrong IDs

### ISSUE THREAD

**Issue by someSven** [RDFLib/rdflib#1050]
Hi, I downloaded some items from Wikidata as .rdf files, whe I tried to load the graph with python3-rdflib version 4.2.2-2 in Python 3.7.3 following error occured (example):
`rdf:nodeID value is not a valid NCName: 6aad7017843afb03b069981cb0e0e5a7
`
Same with raptor version 2.0.14:
```
rapper -c Q23.rdf
rapper: Parsing URI file:///home/pi/NLP/Q23.rdf with parser rdfxml
rapper: Error - URI file:///home/pi/NLP/Q23.rdf:5672 - Illegal rdf:nodeID value '6aad7017843afb03b069981cb0e0e5a7
```
I reported this to Wikidata. They have some problems with empty node IDs in some usecases, and then implemented the creation of automatically generated IDs in a way which may not comply with RDFxml standard, or there are disagreements about if it does or not.
Please consider to put some exception handling into your library, maybe even only if some special option is being used (wd-rdfxml, lol) . For now the only workaround seems to be using Turtle instead of RDFxml. I might come up with a solution myself and try to push it into the lib, but I'm quite new to using Github, RDF and Python, so don't hold your breath for it. For now I'm planing to either use Turtle imports or automatically renaming these nodes.

[My issue report on Wikidata:](https://www.wikidata.org/wiki/Wikidata:Project_chat#Your_data_isn%27t_rdfxml%3F)
[Background: Blank node deprecation in WDQS & Wikibase RDF model](https://www.wikidata.org/wiki/Wikidata:Contact_the_development_team/Query_Service_and_search#Blank_node_deprecation_in_WDQS_&_Wikibase_RDF_model)

**Comment by gjhiggins** [comment]
Not actually an issue as the error is both explicitly handled and correctly reported.
