### ISSUE TITLE
Like .triples() but return a graph

### ISSUE THREAD

**Issue by sharpaper** [RDFLib/rdflib#1055]
My use case is that I would like to chain multiple operations like this:

    graph.triples().add().remove().serialize()

The problem is that `triples` returns an iterator, not a graph object. I do understand that `triples` needs an iterator to deal with the possible situation of having too many results at once. But assuming that I'm only retrieving a small number of triples, for example a single node like this `.triples(subject, None, None)` it would be nice to be able to chain those operations. Is is possible to do something like this?

**Comment by sharpaper** [comment]
Something like a "subgraph" function, that returns a graph by matching triples.

**Comment by piyush69** [comment]
From what I infer, you require something like `graph.subgraph(subject=s, [predicate=p, object=o]) `that'll return a subgraph consisting of triples that match the provided arguments. Is that so?

**Comment by sharpaper** [comment]
Sounds right. Like `triples()` but that returns a graph instead of an iterator.
By the way, If I'm correct `add()` and `remove()` do not return the graph object, they are in-place operations that return `None`. Which means it's not possible to chain them. However:

- `subgraph()` will be useful anyway, as long as the user is aware that all the triples will be loaded in memory
- `add()` and `remove()` (and maybe others?) could return the graph instance to allow chaining, if this is possible and does not disrupt the behavior of rdflib

**Comment by achaudhary997** [comment]
So the `subgraph()` method can be added without disrupting any of the other functionalities (I have implemented this and tested it locally as well). I have currently added a hard limit of a maximum of 1000 nodes (can be changed as per further discussion) in the subgraph that will be returned by the `subgraph()` function. If a number lower than that is needed it can be set using the `max_triples=100` argument of the function.  
As far as `add()` and `remove()` go transforming them into a java like fluent API will require a lot of changes that may disrupt the behavior of rdflib. 
I would suggest waiting for a maintainer's review on the 2nd point and we will see how it goes from there.

**Comment by tgbugs** [comment]
`add` and `remove` are side effecting operations and thus probably should not be modified in core to return self. If you want to use this pattern I would suggest subclassing `Graph`, perhaps as `ChainOpsGraph` or something of that nature.

```python
import rdflib
class ChainOpsGraph(rdflib.Graph):
    def add(self, *args, **kwargs):
        super().add(*args, **kwargs)
        return self

    def remove(self, *args, **kwargs):
        super().remove(*args, **kwargs)
        return self

    def populate_from_triples(self, generator):
        [self.add(t) for t in generator]
        return self

some_graph = rdflib.Graph('https://some-url.org/')
ChainOpsGraph().populate_from_triples(some_graph[s:p:o]).add().remove().serialize()
```

**Comment by sharpaper** [comment]
Thank you @achaudhary997 for the patch! I was wondering... would there be any way to create a Graph() object (a subgraph) without loading all triples in memory? For my specific use case I'm fine with a all-in-memory graph, as it serves what I need it for. But if the subgraph is big, it could be pretty useful to have a not-in-memory subgraph. Or another example, I could add triples to the original graph and these triples will automatically be accessible from the subgraph mapping.

**Comment by tgbugs** [comment]
@sharpaper the reason why the static `subgraph` solution (with chaining) is almost never used is because it does not scale to large graph sizes, which is why triples and graph[s:p:o] are generators -- they can be used to implement low memory streaming on top of graphs of arbitrary size. You could also write a streaming serializer for some of the formats (the trivial case being n-triples), but in order to do that you couldn't use the pattern you originally described. On other hand it is not much more complex to write `filter(match_things_i_do_not_want, chain(triples_to_add, graph[s:p:o]))` and let the branch predictor take care of performance, or even just do `[graph.remove(t) for t in triples_i_do_not_want]` then `chain(triples_to_add, graph[s:p:o])` and finally `[graph.add(t) for triples_i_do_not_want]`.

**Comment by nicholascar** [comment]
We (maintainers) have decided not to merge in PR #1058 that partly addresses this issue. We are still interested in the ChainOpsGraph wrapper though (it might be useful for some styles of programming) and so we will also close this issue.

@tgbugs: do you want to contribute that ChainOpsGraph?
