### ISSUE TITLE
Regular expression in sh:pattern not processed correctly

### ISSUE THREAD

**Issue by James-Hudson3010** [RDFLib/rdflib#1071]
Discovered because I am using pySHACL. I originally reported this as a pySHACL bug but it appears to be a rdflib bug. See https://github.com/RDFLib/pySHACL/issues/47

I have the following:

```
graph_data = """
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sch:  <http://schema.org/> .
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix ex:  <http://example.org/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .

ex:JohnDoe a ex:XXXX .
ex:JohnDoe ex:name "hello.txt" .
"""

shape_data = """
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sch:  <http://schema.org/> .
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix ex:   <http://example.org/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .

ex:PersonShape
  a sh:NodeShape ;
  sh:targetClass ex:XXXX ;
  sh:property ex:PersonShape-name .

ex:PersonShape-name
  a sh:PropertyShape ;
  sh:path ex:name ;
  sh:minCount 1 ;
  sh:pattern  ".*.txt" .
"""
        
data  = rdflib.Graph().parse( data = graph_data, format = 'ttl' )
shape = rdflib.Graph().parse( data = shape_data, format = 'ttl' )

print( f"{data.serialize( format = 'ttl' ).decode( 'utf8' )}" )

report = validate( data, shacl_graph=shape, abort_on_error = False, meta_shacl = False, debug = True, advanced = True )

print( report[2] )
```

The ```sh:pattern``` should be ```".*\.txt"```, but when I do that, the following errors are generated:

``` 
... notation3.py", line 1591, in strconst  "bad escape")
... notation3.py", line 1615, in BadSyntax  raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)

  File "<string>", line unknown
BadSyntax
```

At least according to http://www.datypic.com/books/xquery/chapter19.html, I am using the escape correctly.

As commented on in the pySHACL bug...

> This problem is not of pySHACL but rdfLib library as rdfLib processes the shape file into rdf graph and during that processing, it is decoding the regular expression which is essentially the problem you are referring to

> Can you try this?: `sh:pattern ".*\\.txt" .`

Adding the extra escape does work.

This is probably going to be expected behavior and not an actual bug, but incase something can be done because an additional escape is required to resolve the problem should not be needed.

**Comment by nicholascar** [comment]
This is a "WONTFIX" as in, there's nothing to fix here. The Turtle spec must be respected so use of Regex within it requires the user to escape the Regex as needed. In this case, the use of double backslash.
