### ISSUE TITLE
AttributeError: 'SPARQLUpdateStore' object has no attribute 'endpoint'

### ISSUE THREAD

**Issue by mhmgad** [RDFLib/rdflib#1124]
I have a code that uses RDFlib 4.2.2. I tried to upgrade to 5.0.0.
when I create a graph using SPARQLUpdateStore as follows
```
g=Graph(store='SPARQLUpdateStore', identifier='http://test.org')
g.open('http://localhost:8890/sparql')
```
I get the following error
```
File "/home/gadelrab/anaconda3/envs/ExDEC/lib/python3.7/site-packages/rdflib/graph.py", line 373, in open
    return self.__store.open(configuration, create)
File "/home/gadelrab/anaconda3/envs/ExDEC/lib/python3.7/site-packages/rdflib/plugins/stores/sparqlstore.py", line 512, in open
    self.update_endpoint = self.endpoint
AttributeError: 'SPARQLUpdateStore' object has no attribute 'endpoint'
```
This is not the case with 4.2.2

**Comment by white-gecko** [comment]
You have to change the line `g.open(('http://localhost:8890/sparql', 'http://localhost:8890/sparql'))` where the first IRI in the tuple is the query endpoint and the second IRI the update endpoint is.

**Comment by white-gecko** [comment]
There was a recent update https://github.com/RDFLib/rdflib/commit/48a250e0341c85e27b9cb38b1c37fafdf4c02119 which is available on the current master but not yet released, which should also fix this issue in your case.
