### ISSUE TITLE
FOAF missing some unstable and testing properties

### ISSUE THREAD

**Issue by hufman** [RDFLib/rdflib#1127]
After #962 converted the FOAF namespace to a ClosedNamespace, consumers of this class are restricted to the namespace members hardcoded into `namespaces.py`. This, however, omits some useful properties such as `birthday` and `status`, which are marked as unstable in the [FOAF spec](http://xmlns.com/foaf/spec/), while including other unstable properties such as `age`. Attributes marked `testing` is similarly inconsistent, with `jabberID` but not `aimID` included.
Should all unstable and testing properties be included for comprehensiveness, to prevent problems with the ClosedNamespace feature? I am willing to provide a PR, depending on the decision.

**Comment by danbri** [comment]
They've been unstable for 15-20 years, we should probably fix that in FOAF too :)

**Comment by aucampia** [comment]
I would say they should be included if they are in the namespace.

**Comment by gjhiggins** [comment]
Evaporated, closing
