### ISSUE TITLE
Minor typo(?) in example

### ISSUE THREAD

**Issue by stigbd** [RDFLib/rdflib#1129]
I think the comment on line 36 is wrong and should read
```
# add a graph for John's facts to the Conjunctive Graph 
```
https://github.com/RDFLib/rdflib/blob/e4fe0fdbd4de7e1183418f302315b51a14602e03/examples/conjunctive_graphs.py#L36-L37

No big deal, but it may be confusing to learners.

**Comment by ashleysommer** [comment]
Yep, a long standing copy/paste error. Thanks for the PR.
