### ISSUE TITLE
Importing rdflib outputs the version

### ISSUE THREAD

**Issue by donpellegrino** [RDFLib/rdflib#1135]
When importing rdflib, an identifier and the version number are output. There is no need to output on the successful loading of an import. It should remain silent when loaded. For background, see the "[Rule of Silence](http://www.catb.org/~esr/writings/taoup/html/ch01s06.html#id2878450)."

```
Python 3.6.5 (default, Oct  8 2018, 17:39:55)
[GCC 7.3.0 20180125 (Cray Inc.)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdflib
RDFLib Version: 5.0.0

```

**Comment by nicholascar** [comment]
OK, point taken, now I have to figure out what code makes this happen, I've never really noticed it before...
