### ISSUE TITLE
duplicate prefix declaration injected on sparqlstore & sparqlupdatestore in 5.0.0

### ISSUE THREAD

**Issue by pebbie** [RDFLib/rdflib#1136]
In 5.0.0, `xml`, `rdf`, `rdfs`, and `xsd` are injected twice when querying a sparql endpoint using `SPARQLStore` or `SPARQLUpdateStore` causing malformed query error on GraphDB (OpenLink Virtuoso backed SPARQL endpoint runs just fine).

**Comment by jclerman** [comment]
Oops, I just reported the same thing as issue #1157.

**Comment by gjhiggins** [comment]
Covered more extensively in #1157, closing.
