### ISSUE TITLE
rdflib.plugin.PluginException: No plugin registered for (rdfa, <class 'rdflib.parser.Parser'>) version 5 incompatibility to examples

### ISSUE THREAD

**Issue by WolfgangFahl** [RDFLib/rdflib#1147]
I started out with:
```
  from rdflib import Graph
  g=Graph()
  g.parse('http://wikicfp.com/cfp/servlet/event.showcfp?eventid=3862',format='rdfa')
```
which earned me:
```
 File "/Users/wf/Library/Python/3.8/lib/python/site-packages/rdflib/plugin.py", line 105, in get
    raise PluginException(
rdflib.plugin.PluginException: No plugin registered for (rdfa, <class 'rdflib.parser.Parser'>)
```

and some research on what is going on. I found:
* https://github.com/RDFLib/rdflib/pull/828/files
so there was a decision to break examples found out there on the internet by removing the built in support and hope that people would guess how to get this working.

After a bit of guessing i came up with:

```
from rdflib import Graph,plugin
from rdflib.parser import Parser
 plugin.register(
            'rdfa', Parser,
            'rdflib.plugins.parsers.structureddata', 'RDFaParser')
        g=Graph()
        g.parse('http://wikicfp.com/cfp/servlet/event.showcfp?eventid=3862',format='rdfa')
```
with the error

```
ModuleNotFoundError: No module named 'rdflib.plugins.parsers.structureddata'
```
which pointed me to https://github.com/scrapinghub/extruct/issues/131 - saying:

 _I had the same issue. Just install the rdflib==4.2.2_

pointing to: https://rdflib.readthedocs.io/en/stable/upgrade4to5.html

Removed RDF Parsers

_The RDFa and Microdata format RDF parsers were removed from rdflib. There are still other python libraries available to implement these parsers._

**Which are these parsers and how is the above example migrated?**. I'd rather see the original solution still working with the same API.

**Version info**
```
pip show rdflib
Name: rdflib
Version: 5.0.0
Summary: RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
Home-page: https://github.com/RDFLib/rdflib
Author: Daniel 'eikeon' Krech
Author-email: eikeon@eikeon.com
License: BSD-3-Clause
Location: /Users/wf/Library/Python/3.8/lib/python/site-packages
Requires: six, isodate, pyparsing
Required-by: weaviate-client, SPARQLWrapper
```

**Comment by gjhiggins** [comment]
RDFa example has subsequently been removed. Glad you managed to find an alternative route.
