### ISSUE TITLE
Resolve .term.Statement deprecation

### ISSUE THREAD

**Issue by mwatts15** [RDFLib/rdflib#1158]
`.term.Statement` has been deprecated since 2012. Is there any plan to actually remove it or un-deprecate it?

https://github.com/RDFLib/rdflib/blob/master/rdflib/term.py#L1699

**Comment by ashleysommer** [comment]
Hi @mwatts15 
Looks like we should just remove it.
We are going through at the moment identifying any old stuff we should remove, and what other things we will want to deprecate, in order to remove down the track.
This will be removed in RDFLib v5.1.0 or v6.0.0
