### ISSUE TITLE
serialize fails on windows machine with multiple drives

### ISSUE THREAD

**Issue by urbanmatthias** [RDFLib/rdflib#1170]
In the serialize method of graph.py, you urlparse the given  destination:https://github.com/RDFLib/rdflib/blob/e56df6e189fba0e592391d21e3b394882032f186/rdflib/graph.py#L985

On windows machines this strips the leading drive letter (e.g. `C:\`).
On some machines the shutil.move call seems to work nevertheless, but on some it doesn't:
https://github.com/RDFLib/rdflib/blob/e56df6e189fba0e592391d21e3b394882032f186/rdflib/graph.py#L996

```
  File "...", line 133, in store
    self._graph.serialize(destination=path_graph, format="xml")
  File "...\lib\site-packages\rdflib\graph.py", line 982, in serialize
    shutil.move(name, path)
  File "...\lib\shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "...\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "...\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, "rb") as fsrc, open(dst, "wb") as fdst:
FileNotFoundError: [Errno 2] No such file or directory: "\\Users\\urba\\.osp_ontologies\\graph.xml"
```

Why do you strip the drive and why does it work sometimes and sometimes not?

**Comment by urbanmatthias** [comment]
```
from urllib.parse import urlparse
import os

path = os.path.join(os.path.expanduser("~"), ".osp_ontologies")
print(path)

scheme, netloc, newpath, params, _query, fragment = urlparse(path)
print(newpath)
```

Which outputs:

```
C:\Users\urba\.osp_ontologies
\Users\urba\.osp_ontologies
```

**Comment by CaptainHillman** [comment]
It appears that the issue only appears on Windows machines with multiple drives. On such a machine, making a call to shutil.move() with an absolute path that does not include a drive identifier caused a "FileNotFoundError".
