### ISSUE TITLE
add() method

### ISSUE THREAD

**Issue by alex-randles** [RDFLib/rdflib#1171]
Hi,

I have a question about the rdflib add() method. Does this method use a SPARQL query? and if so, can the query executed be retrieved?

Thanks.

**Comment by ashleysommer** [comment]
Hi @alex-randles 
I'm assuming you're talking about the `graph.add()` method. Correct me if that is wrong.

Whether it uses a SPARQL query is dependent on what kind of triplestore you are using.
For example, if you are using the default in-memory triplestore, then running `g.add((x, y, z))` goes not use a SPARQL query, it simply puts that triple into the in-memory store programmatically.

On the other hand, if you're using a SPARQLStore like SPARQLWrapper, then _yes_ the store backend _does_ generate a SPARQL query. But the `g.add()` does not know about that. The graph abstraction layer does not know/care about what underlying store is being used or what mechanisms it uses to add triples. So you cannot retrieve the SPARQL query executed.

**Comment by ashleysommer** [comment]
Hi @alex-randles 
Did my response answer your question?

**Comment by alex-randles** [comment]
yes that's fine, thank you.
