### ISSUE TITLE
AttributeError: module 'rdflib' has no attribute 'Graph'

### ISSUE THREAD

**Issue by HYDesmondLiu** [RDFLib/rdflib#1173]
OS: Ubuntu 18.04
python version: Python 3.6.9
rdflib version: rdflib==5.0.0 / rdflib-jsonld==0.5.0

By running a simple code extracted from your official website, encountered this error. Cannot find any valid solutions on internet.

```
import rdflib
#from rdflib import Graph

def validateTTL():
    # Create a graph
    g = rdflib.Graph()

    result = g.parse("XXX.ttl")

    # print the number of "triples" in the Graph
    print("graph has {} statements.".format(len(g)))
    # prints graph has 86 statements.

    # print out the entire Graph in the RDF Turtle format
    print(g.serialize(format="turtle").decode("utf-8"))


if __name__ == "__main__":
    validateTTL()

```

Error:
`Traceback (most recent call last):
  File "rdflib.py", line 19, in <module>
    validateTTL()
  File "rdflib.py", line 6, in validateTTL
    g = rdflib.Graph()
AttributeError: module 'rdflib' has no attribute 'Graph'`

**Comment by ashleysommer** [comment]
Hi.
I think maybe you have another file in your project called "rdflib.py", so when you do "import rdflib" it is importing your file instead of the RDFLib library.

**Comment by HYDesmondLiu** [comment]
Oh shoot, this is a stupid one. Should've never named that file.

**Comment by ashleysommer** [comment]
That is why all my files are always called `test1.py` `t2.py` `anothertest.py` `thisoneworks.py` `broken_code.py` haha 😂
