### ISSUE TITLE
graph serialize() method 

### ISSUE THREAD

**Issue by alex-randles** [RDFLib/rdflib#1174]
Hi All,

I'm having the following problem when using rdflib serialize() method to print the graph. The layout changes from the original file used to create the graph.

The code is as follows

``` 
from rdflib import Graph
mapping_graph = Graph().parse("valid_mapping.ttl", format="ttl")
print(mapping_graph.serialize(format="ttl").decode("utf-8"))
```

Which outputs
```
<#TripleMap1> rr:logicalTable [ rr:tableName "people" ],
                [ rr:tableName "people" ] .
```

While the input file is
```
<#TripleMap1>
        rr:logicalTable        [ rr:tableName  "people" ] ;
        rr:logicalTable        [ rr:tableName  "people" ] ;
```

The layout of the graph is changed by the serialize() method. 

Any help would be gratefully appreciated.

**Comment by white-gecko** [comment]
This is correct behavior.
The Turtle serialization allows different layouts for the same RDF graph. Especially in this case an even more concise representation is found.
