### ISSUE TITLE
[BUG] SOSA and SSN namespace have been defined incorrectly

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/rdflib#1187]
In RDFLib 5.0.0 `rdflib.namespace` sosa and ssn have been defined as follows:

```python
SOSA = Namespace('http://www.w3.org/ns/ssn/')
SSN = Namespace('http://www.w3.org/ns/sosa/')
```

https://github.com/RDFLib/rdflib/blob/master/rdflib/namespace.py#L494-L495

They need to be switched around.

**Comment by edmondchuc** [comment]
Looks like it's already fixed in master.

**Comment by ashleysommer** [comment]
Hi Edmond.
This was reported in https://github.com/RDFLib/rdflib/issues/1126
and fixed in https://github.com/RDFLib/rdflib/pull/1128

Github should have pointed these out to you as existing topics in its auto-search feature when you created this Topic.

**Comment by edmondchuc** [comment]
Hi Ashley, not sure why but GitHub didn't show related issues for me when I wrote this.
