### ISSUE TITLE
BadSyntax subclasses from SyntaxError, but does not set parent fields

### ISSUE THREAD

**Issue by sa-bpelakh** [RDFLib/rdflib#1194]
The documentation for `SyntaxError` states:
> Instances of this class have attributes filename, lineno, offset and text for easier access to the details.

but none of these are set by BadSyntax.

**Comment by gjhiggins** [comment]
> The documentation for `SyntaxError` states:
> "Instances of this class have attributes filename, lineno, offset and text for easier access to the details."
> but none of these are set by BadSyntax.

The Notation3 parser doesn't have access to some of these values when it isn't parsing a file but some values _are_ bound:

https://github.com/RDFLib/rdflib/blob/6ed2ef48ed38679bcdafe7cae250a2ef4b315e7b/rdflib/plugins/parsers/notation3.py#L1653
