### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib

### ISSUE THREAD

**Issue by honzajavorek** [RDFLib/rdflib#1196]
Using `rdflib==4.2.2` as part of `extruct` and getting this warning: 

```
/.../python3.8/site-packages/rdflib/plugins/parsers/pyRdfa/utils.py:19
  /.../python3.8/site-packages/rdflib/plugins/parsers/pyRdfa/utils.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import os, os.path, sys, imp, datetime
```

Not sure if this has been fixed in v5, I didn't find anything mentioning importlib in the issues or PRs here.

**Comment by FlorianLudwig** [comment]
This was fixed in 

https://github.com/RDFLib/pyrdfa3/commit/d4b91f81d75150abaa8587f93d53dc7130e09f6a

on `pyrdfa3`, which is not part of rdflib core.

**Comment by honzajavorek** [comment]
OK, thanks! I also got a confirmation from `extruct` this is an issue more on their side as they're stuck with older versions of dependencies.
