### ISSUE TITLE
Can't add more than a certain number of triples to SPARQLUpdateStore

### ISSUE THREAD

**Issue by timcroydon** [RDFLib/rdflib#1199]
I'm experiencing a strange problem trying to sequentially add triples to a graph backed by a SPARQLUpdateStore I just can't figure out. It just seems like non-deterministic behaviour and I've no idea whether it's a problem with RDFLib itself or something more fundamental.

A colleague has verified the same behaviour (in a very similar dev environment). I'm tearing my hair out a bit at this one, and just don't know what else to look at - any pointers gratefully received!

Thanks in advance.

### Problem
When adding a 'large' number of triples to a graph, they don't get added to my store. e.g. in the example below, adding <3329 triples works and I see all triples in my store. If I try and add 3330 or more nothing gets written.

### Expected behaviour
All triples added to the store.

### Error message
No error messages or crashes encountered - code _appears_ to work correctly.

### Minimal reproduction

Here's a minimal test (using pytest) - it just creates a new graph named `test-<uuid>` and then sequentially adds some basic triples to it, performing a single `commit()` when I'm done. Just set `number_of_triples` to choose how many to try with.

```python
import pytest
from rdflib import Graph, Namespace, Literal
from rdflib.plugins.stores.sparqlstore import SPARQLUpdateStore
import uuid


@pytest.fixture(scope='session')
def store():
	store = SPARQLUpdateStore(query_endpoint='http://localhost:9080/sparql',
							  update_endpoint='http://localhost:9080/sparql',
							  auth=('admin', 'Passw0rd1'), autocommit=False)

	return store


@pytest.fixture(scope='session')
def graph_name():
	return f'test-{uuid.uuid4()}'


def test_create_1m_triples(store: SPARQLUpdateStore, graph_name):
	graph = Graph(store=store, identifier=graph_name)

	ns = Namespace('http://test#')
	item = ns.term('item')

        number_of_triples = 100

	for i in range(number_of_triples):
		graph.add((ns.term(i), item, Literal(i)))

	graph.commit()

	assert True
```

### Error diagnosis
Stepping through, I see the problem at:
https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/stores/sparqlstore.py#L613-L615

When `self._transaction()` is called, a new empty list is assigned to `self._edits`. However, after the `.append()` is called, `self._edits` is now set to `None`, leaving nothing for the `commit()` call to do.

### Environment
Python 3.8.6 on OSX 10.15.4
SPARQL store: AnzoGraph 2.2.1 (although I'm confident this isn't the problem)
RDFLib: commit c5ff127 (and others - I'm not using the latest release 5.0.0 because of a bug fix that's been applied since that we needed)

**Comment by gjhiggins** [comment]
I'm unable to reproduce this using your test (thank you!) with 10000 entries using Mint Uma, Python 3.8, RDFLib 6.1 and fuseki.

> When `self._transaction()` is called, a new empty list is assigned to `self._edits`. However, after the `.append()` is called, `self._edits` is now set to `None`, leaving nothing for the `commit()` call to do.

Appearances can be deceptive, self._edits is only set to the empty list when the value is `None` - which is only set by `__init__`, `commit()` and `rollback()` --- temporarily adding a couple of logging calls shows it to be functioning effectively.
