### ISSUE TITLE
Turtle de/serialize incorrectly interprets gYear

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#1228]
In 5.0.0, when a `gYear` is parsed and then re-serialised, from any format to any other format, RDFlib adds "-01-01" to the literal so, for example, `"1982"^^xsd:gYear` goes to `"1982-01-01"^^xsd:gYear` which is invalid.

Testing code:

```python
from rdflib import Graph

data =  """
        PREFIX sdo: <https://schema.org/>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

        <x:> sdo:startDate "1982"^^xsd:gYear .
        """

g = Graph().parse(data=data, format="ttl")
assert "1982-01-01" not in g.serialize(format="ttl").decode()


data2 = """<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:sdo="https://schema.org/"
>
  <rdf:Description rdf:about="x:">
    <sdo:startDate rdf:datatype="http://www.w3.org/2001/XMLSchema#gYear">1982</sdo:startDate>
  </rdf:Description>
</rdf:RDF>"""

g2 = Graph().parse(data=data2, format="xml")
assert "1982-01-01" not in g2.serialize(format="xml").decode()
```

**Comment by aucampia** [comment]
May be related to https://github.com/RDFLib/rdflib/issues/806

**Comment by aucampia** [comment]
Can we close this and use #1228 instead?

**Comment by nicholascar** [comment]
> Can we close this and use #747 instead?

Yes, we should! I raised this one, obviously while using RDFlib, but I failed to check that a previous issue existed. Thanks for making the link @aucampia. Closing this one as duplicate.
