### ISSUE TITLE
Leading digits in local part of prefixed names and `rdflib.Namespace`

### ISSUE THREAD

**Issue by tombaker** [RDFLib/rdflib#1233]
According to [RDF 1.1 Turtle](https://www.w3.org/TR/turtle/#sec-iri), the local part of prefixed names may include leading digits. For example, ` http://lod.nal.usda.gov/nalt/286017 ` can be prefixed as `nalt:286017`.  However, the rdflib Namespace mechanism does not handle this URI as expected:
```
>>> from rdflib import Namespace, Graph, RDFS
>>> NALT=Namespace("http://lod.nal.usda.gov/nalt/")
>>> g = Graph()
>>> g.parse('nalt.nt', format='nt')
<Graph identifier=Nc26a8583c0c14cb9b323bf7dc55375fe (<class 'rdflib.graph.Graph'>)>
>>> list(g.subject_objects(RDFS.label))
[(rdflib.term.URIRef('http://lod.nal.usda.gov/nalt/'), rdflib.term.Literal('NAL Thesaurus'))]
>>> list(g.predicates(NALT.28601))
  File "<ipython-input-24-460dbe57146e>", line 1
    list(g.predicates(NALT.28601))
                          ^
SyntaxError: invalid syntax
```
Is this a known issue (I couldn't find one here) and, if so, could it be fixed?

**Comment by hsolbrig** [comment]
The problem with what you are trying to do is that it is an illegal construct in the Python language itself.  

`NALT['28601']` will work, however.

**Comment by tombaker** [comment]
@hsolbrig Thank you! I see now that the documentation on [Namespaces and Bindings](https://rdflib.readthedocs.io/en/stable/namespaces_and_bindings.html) makes this point, but only as a comment to the code snippet.

I think it is worth drawing attention to this point so have submitted a pull request on the RTD page.
