### ISSUE TITLE
"Bag" in rdflib

### ISSUE THREAD

**Issue by RichardPinka** [RDFLib/rdflib#1235]
hello, 
Do You have please clue, why "Bag" is not working in module rdflib as you may see ? 
![image](https://user-images.githubusercontent.com/8267708/105617976-fb988180-5de2-11eb-920b-a54955c67222.png)

**Comment by white-gecko** [comment]
Hello @RichardPinka ,
the containers were added in the current master branch but are not yet released. Probably you are using rdflib 5.0.0 which does not include containers.
When you install from the current master branch you will need to import `Bag` from `rdflib.container` as the following example shows:

```
from rdflib import Graph, BNode, Literal
from rdflib.container import Bag

g = Graph()
b = Bag(g, BNode(), [Literal("one"), Literal("two"), Literal("three")])

print(g.serialize(format="turtle"))
```

A minor remark. Please directly paste your code and the relevant output into the issue. That makes it easier to reproduce your code.

**Comment by RichardPinka** [comment]
Hello and thank you. Now, I just need to find out how the "current master branch" could be installed :)  (sorry i am civil engineer, i like simple stuf like    setup.exe for installing the stuff  :)   )

**Comment by white-gecko** [comment]
You can try it with

    pip install git+https://github.com/RDFLib/rdflib@master

but be aware, the code in the master branch is not yet released and might be unstable
