### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by ashleysommer** [RDFLib/rdflib#1243]
Travis is discontinuing Travis-CI.org, and all opensource projects are now able to migrate to a free travis-ci.com account.

I've already added Travis-CI.com permissions to the RDFLib github organisation, and I've already migrated the PySHACL repository from travis-ci.org to travis-ci.com, it seemed to go well.

**Comment by white-gecko** [comment]
I think we should do that for rdflib as well I it is easy. I did not find the correct buttons to do that. But at some point we might want to switch away from travis. (https://groups.google.com/g/rdflib-dev/c/Ub-J4Oev0UA)

**Comment by ashleysommer** [comment]
Migration is complete.
