### ISSUE TITLE
Possible optimisation of notation3.py ?

### ISSUE THREAD

**Issue by rchateauneu** [RDFLib/rdflib#1262]
The file rdflib/plugins/parsers/notation3.py contains very often this pattern to access a single character from a string:

ch = argstr[i : i + 1]  # Quick 1-character checks first
if argstr[j : j + 1] == "=":
ch2 = argstr[i + 1 : i + 2]

It seems to be equivalent to these lines which would be simpler and faster:

ch = argstr[i]  # Quick 1-character checks first
if argstr[j] == "=":
ch2 = argstr[i + 1]

So, is there a specific reason to select a substring instead of a single character ?

**Comment by white-gecko** [comment]
Could you verify, that it is actually faster?
I think it is very important to find such very minor fixes and improvements as some lines in the parsers are executed very often.

**Comment by rchateauneu** [comment]
About 5% speedup on benchmark mentioned at [https://github.com/RDFLib/rdflib/issues/1261](url)

Simple micro-optimizations.

Here is the patch:
[notation3.patch.txt](https://github.com/RDFLib/rdflib/files/6050780/notation3.patch.txt)

Also, here is a profile of the most expensive calls:

Number of calls, total time, total / number, cumulated, cumulated / number
  3103323    7.598    0.000    8.958    0.000 rdflib\rdflib\events.py:41(__init__)
  4992083    7.800    0.000   10.484    0.000 rdflib\rdflib\term.py:941(__hash__)
 10112080    8.500    0.000    8.500    0.000 rdflib\rdflib\term.py:140(__eq__)
  3103322    8.896    0.000   96.288    0.000 rdflib\rdflib\plugins\parsers\notation3.py:748(verb)
76360883/76360882    9.619    0.000    9.619    0.000 {built-in method builtins.isinstance}
 10174736    9.765    0.000    9.765    0.000 rdflib\rdflib\term.py:76(_is_valid_uri)
  9309969   11.754    0.000   20.630    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1821(normalise)
  3103323   11.836    0.000   21.617    0.000 rdflib\rdflib\store.py:207(add)
1178974/755643   12.668    0.000  374.562    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1056(property_list)
  3103323   15.510    0.000   35.617    0.000 rdflib\rdflib\plugins\stores\memory.py:439(__add_triple_context)
6418508/5571846   15.886    0.000  216.144    0.000 rdflib\rdflib\plugins\parsers\notation3.py:874(node)
  3103323   22.054    0.000   96.704    0.000 rdflib\rdflib\plugins\stores\memory.py:214(add)
 31829425   23.576    0.000   26.065    0.000 rdflib\rdflib\plugins\parsers\notation3.py:497(tok)
  5995191   27.499    0.000  110.626    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1158(uri_ref2)
  5995205   30.621    0.000   45.841    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1313(qname)
 31812017   34.271    0.000   84.777    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1245(skipSpace)
101433082   47.083    0.000   47.083    0.000 {method 'match' of '_sre.SRE_Pattern' objects}

**Comment by rchateauneu** [comment]
@white-gecko

25% speedup with a new implementation of skipSpace() in notation3.py .

[notation3.skipSpace.patch.txt](https://github.com/RDFLib/rdflib/files/6052248/notation3.skipSpace.patch.txt)

The idea is to process first the most common case, a non-commented line starting with few spaces and tabs:

    def skipSpace(self, argstr, i):
        """Skip white space, newlines and comments.
        return -1 if EOF, else position of first non-ws character"""

        # Most common case is a non-commented line starting with few spaces and tabs.
        try:
            while True:
                ch = argstr[i]
                if ch in " \t":
                    i += 1
                    continue
                elif ch not in "#\r\n":
                    return i
                break
        except IndexError:
            return -1

# Then same function as now.

It eliminates the overhead of regex.

**Comment by white-gecko** [comment]
I think this would be a good pull-request.

**Comment by rchateauneu** [comment]
Done:
It includes two completely independent changes.
* Changes in setup.py allowing Cython with specific library build setup option.
* Speedup of Turtle parsing in notation3.py : Pure Python

**Comment by rchateauneu** [comment]
Most expensive calls now:
6418508/5571846    8.919    0.000  250.319    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1448(nodeOrLiteral)
 10174736    8.927    0.000   27.541    0.000 rdflib\rdflib\term.py:221(__new__)
  3103323    9.272    0.000  180.095    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1804(makeStatement)
  3103323   10.191    0.000   12.054    0.000 rdflib\rdflib\events.py:41(__init__)
  4992083   10.574    0.000   14.163    0.000 rdflib\rdflib\term.py:941(__hash__)
  3103322   11.241    0.000  103.487    0.000 rdflib\rdflib\plugins\parsers\notation3.py:748(verb)
 10112080   11.744    0.000   11.744    0.000 rdflib\rdflib\term.py:140(__eq__)
 10174736   12.627    0.000   12.627    0.000 rdflib\rdflib\term.py:76(_is_valid_uri)
76360918/76360917   12.635    0.000   12.635    0.000 {built-in method builtins.isinstance}
 16175314   15.421    0.000   15.421    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
  9309969   15.680    0.000   27.241    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1824(normalise)
1178974/755643   16.114    0.000  437.318    0.001 rdflib\rdflib\plugins\parsers\notation3.py:1056(property_list)
  3103323   16.618    0.000   29.824    0.000 rdflib\rdflib\store.py:207(add)
6418508/5571846   20.322    0.000  241.467    0.000 rdflib\rdflib\plugins\parsers\notation3.py:874(node)
  3103323   21.612    0.000   48.845    0.000 rdflib\rdflib\plugins\stores\memory.py:439(__add_triple_context)
 31812017   22.675    0.000   38.168    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1237(skipSpace)
  3103323   30.058    0.000  132.423    0.000 rdflib\rdflib\plugins\stores\memory.py:214(add)
 31829425   30.733    0.000   33.567    0.000 rdflib\rdflib\plugins\parsers\notation3.py:497(tok)
  5995191   36.575    0.000  124.959    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1158(uri_ref2)
  5995205   39.199    0.000   42.524    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1319(qname)

skipSpace() is now far behind, and regex calls not visible anymore.

**Comment by rchateauneu** [comment]
@white-gecko
@m1ci

Another speed-up, 6%, attached and in my fork.
Function is qname in notation3.py
[notation3.qname.patch.txt](https://github.com/RDFLib/rdflib/files/6054208/notation3.qname.patch.txt)

The idea is to concatenate to the result only once, or only if there are two consecutive back-slashes.
Also, the order of tests on the current character to put the rarest case first.

**Comment by rchateauneu** [comment]
Profile is now:

  3103323    6.804    0.000    7.961    0.000 rdflib\rdflib\events.py:41(__init__)
  4992083    7.123    0.000    9.664    0.000 rdflib\rdflib\term.py:941(__hash__)
  3103322    7.922    0.000   70.861    0.000 rdflib\rdflib\plugins\parsers\notation3.py:748(verb)
 10112080    8.229    0.000    8.229    0.000 rdflib\rdflib\term.py:140(__eq__)
 10174736    8.990    0.000    8.990    0.000 rdflib\rdflib\term.py:76(_is_valid_uri)
76360966/76360965    9.131    0.000    9.131    0.000 {built-in method builtins.isinstance}
 16175314    9.920    0.000    9.920    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
  3103323   10.559    0.000   19.281    0.000 rdflib\rdflib\store.py:207(add)
1178974/755643   10.991    0.000  295.641    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1056(property_list)
  9309969   11.001    0.000   19.474    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1824(normalise)
  3103323   13.928    0.000   32.920    0.000 rdflib\rdflib\plugins\stores\memory.py:439(__add_triple_context)
6418508/5571846   14.141    0.000  162.327    0.000 rdflib\rdflib\plugins\parsers\notation3.py:874(node)
 31812017   15.529    0.000   25.716    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1237(skipSpace)
  3103323   19.865    0.000   88.120    0.000 rdflib\rdflib\plugins\stores\memory.py:214(add)
 31829425   22.057    0.000   24.223    0.000 rdflib\rdflib\plugins\parsers\notation3.py:497(tok)
  5995205   24.967    0.000   27.250    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1319(qname)
  5995191   25.026    0.000   83.409    0.000 rdflib\rdflib\plugins\parsers\notation3.py:1158(uri_ref2)

So the next target to optimize is the fucntion uri_ref2()

**Comment by rchateauneu** [comment]
Do not integrate yet please, there are a couple of tests which do not pass.
