### ISSUE TITLE
Discrepancy between SPARQLStore and SPARQLWrapper behavior for query on wikidata

### ISSUE THREAD

**Issue by g-vidal** [RDFLib/rdflib#1264]
I am a beginner with RDFLib, I thought it was equivalent (except for differences on output)  to use `SPARQLStore` or `SPARQLWrapper` . I am facing a a problem when using   `SPARQLStore` with the collowing code : 

```python
from rdflib import Graph
remote = Graph("SPARQLStore", identifier="http://wikidata.org/")
remote.open("http://query.wikidata.org/sparql")
qresRem = remote.query(
    """
    SELECT DISTINCT ?p 
    WHERE {
    wd:Q182250  ?p ?o .
    }
    LIMIT 10
    """)
```
I ger a `400` error : 
```shell
HTTPError: 400 Client Error: Bad Request for url: https://query.wikidata.org/sparql?query=PREFIX+xml%3A+%3Chttp%3A%2F%2Fwww.w3.org%2FXML%2F1998%2Fnamespace%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX+xml%3A+%3Chttp%3A%2F%2Fwww.w3.org%2FXML%2F1998%2Fnamespace%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%0A++++PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0A++++SELECT+DISTINCT+%3Fp+%0A++++WHERE+%7B%0A++++wd%3AQ182250++%3Fp+%3Fo+.%0A++++%7D%0A++++LIMIT+10%0A++++&default-graph-uri=http%3A%2F%2Fwikidata.org%2F
```
The problem coming from the automatic add of PREFIX values, if I remove those unrequested values the request works perfectly. 
It is probably linked with #1168 and maybe #710 #794, is there a solution ?

I can confirm that using `SPARQLWrapper` works perfectly with the same query, it is not clear for me if it is a workaround, an alternative or a temporary solution until `SPARQLStore`evolves :

```python
from SPARQLWrapper import SPARQLWrapper, JSON
remote = SPARQLWrapper("http://query.wikidata.org/sparql")
remote.setQuery("""
    PREFIX wd: <http://www.wikidata.org/entity/>
    SELECT DISTINCT ?p  
    WHERE {wd:Q182250  ?p ?o .} 
    LIMIT 10
""")
remote.setReturnFormat(JSON)
results = remote.query().convert()
for result in results["results"]["bindings"]:
    print(result["p"]["value"])
print('---------------------------')
```
Result : 
```shell
http://schema.org/version
http://schema.org/dateModified
http://schema.org/description
http://www.w3.org/2000/01/rdf-schema#label
http://www.w3.org/2004/02/skos/core#altLabel
http://wikiba.se/ontology#statements
http://wikiba.se/ontology#sitelinks
http://wikiba.se/ontology#identifiers
http://wikiba.se/ontology#timestamp
http://www.wikidata.org/prop/direct/P227
---------------------------
```
Should we only use `SPARQLWrapper` or `SPARQLStore`  will not add unwanted PREFIX in future relases.

Many thanks for your work anyway :)

**Comment by white-gecko** [comment]
Just looking at it.
Will the first example work if you add

    PREFIX wd: <http://www.wikidata.org/entity/>

to it?

**Comment by g-vidal** [comment]
Thanks for the answer.
I checked with  the following code, I get  the same behavior with `HTTPError: 400 Client Error: Bad Request for url:` .  In the "unwanted URL declarations" `www.wikidata.org%2Fentity%2F` is still present, the bugis coming from elsewhere.

```python
from SPARQLWrapper import SPARQLWrapper, JSON
remote = SPARQLWrapper("http://query.wikidata.org/sparql")
remote.setQuery("""
    PREFIX wd: <http://www.wikidata.org/entity/>
    SELECT DISTINCT ?p  
    WHERE {wd:Q182250  ?p ?o .} 
    LIMIT 10
""")
```
```http
 https://query.wikidata.org/sparql?query=PREFIX+xml%3A+%3Chttp%3A%2F%2Fwww.w3.org%2FXML%2F1998%2Fnamespace%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX+xml%3A+%3Chttp%3A%2F%2Fwww.w3.org%2FXML%2F1998%2Fnamespace%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%0A++++PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0A++++SELECT+DISTINCT+%3Fp+%0A++++WHERE+%7Bwd%3AQ182250++%3Fp+%3Fo+.%7D%0A++++LIMIT+10%0A++++&default-graph-uri=http%3A%2F%2Fwikidata.org%2F
```

**Comment by white-gecko** [comment]
I've tried your code on my system. I could reproduce it with the current 5.0.0 release as it is published on pypi.
The problem are "Multiple prefix declarations for prefix 'xml'" (as reported by the wikidata endpoint).
However it is fixed in the current master, but I could not identify the exact commit.

If you uninstall your current rdflib installation you can install the latest master with

    pip install git+https://github.com/rdflib/rdflib@master

Will that solve the problem for you?

For the SPARQLWrapper issues I suggest reporting them at https://github.com/RDFLib/sparqlwrapper/issues

**Comment by g-vidal** [comment]
Unfortunately no...
I am using pipenv and jupyterlab3 inside the virt env. When I try to install  I get an error message :
```shell
pipenv install git+https://github.com/rdflib/rdflib@master
Installing git+https://github.com/rdflib/rdflib@master…
⠴WARNING: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+https://github.com/rdflib/rdflib#egg=<package-name>.
```
Then I change the command to :
```shell
 pipenv install git+https://github.com/rdflib/rdflib#egg=rdflib
Installing git+https://github.com/rdflib/rdflib#egg=rdflib…
⠏Warning: You installed a VCS dependency in non–editable mode. This will work fine, but sub-dependencies will not be resolved by $ pipenv lock.
  To enable this sub–dependency functionality, specify that this dependency is editable.
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: rdflib from git+https://github.com/rdflib/rdflib#egg=rdflib in /home/vidal/.local/share/virtualenvs/JupVirtEnv-fb6ZW8xR/lib/python3.9/site-packages (5.0.0)
Requirement already satisfied: six in /home/vidal/.local/share/virtualenvs/JupVirtEnv-fb6ZW8xR/lib/python3.9/site-packages (from rdflib) (1.15.0)
Requirement already satisfied: pyparsing in /home/vidal/.local/share/virtualenvs/JupVirtEnv-fb6ZW8xR/lib/python3.9/site-packages (from rdflib) (2.4.7)
Requirement already satisfied: isodate in /home/vidal/.local/share/virtualenvs/JupVirtEnv-fb6ZW8xR/lib/python3.9/site-packages (from rdflib) (0.6.0)

Adding git+https://github.com/rdflib/rdflib#egg=rdflib to Pipfile's [packages]…
Pipfile.lock (0d97db) out of date, updating to (07c6e2)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (07c6e2)!
Installing dependencies from Pipfile.lock (07c6e2)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 116/116 — 00:00:32
```
Start jupyter lab and get same errors. I'll reread and report on the adress you recommend .

**Comment by white-gecko** [comment]
In your log it says `Requirement already satisfied: rdflib from … in … (5.0.0)`. pipenv thinks it is the same version in the git repo as you have installed already installed and does not install it from the git. This is why I wrote that you need to uninstall rdflib first, or you install it into a fresh environment.

This might be solved with #1285 .

**Comment by g-vidal** [comment]
Sorry @white-gecko  I read your post too fast, I did not catch I had to uninstall !
Your workaround works perfectly :
```shell
pipenv uninstall rdflib
pipenv clean
pipenv install git+https://github.com/rdflib/rdflib@master#egg=rdflib
```
Many thanks for the follow up things are working. I am just wondering which one from `Wrapper` or `Store` should be used in which situation and why, if you may   know a link with explanations or discussions.

**Comment by white-gecko** [comment]
Actually I had the same question and didn't get an answer so far: https://github.com/RDFLib/sparqlwrapper/issues/37#issuecomment-803640092
You are invited to find an answer :-) https://github.com/RDFLib/sparqlwrapper/issues might be the proper place.
Maybe the two code bases should get closer together.
