### ISSUE TITLE
Broken tests Windows 7, Python 3.6, rdflib 5.0

### ISSUE THREAD

**Issue by rchateauneu** [RDFLib/rdflib#1265]
This is the list of unit tests which do not pass on Windows 7, Python 3.6, rdflib version 5.0.0.

Maybe this is expected ?

test/test_conneg.py
    def testConNeg()

test/test_csv2rdf.py
    def test_csv2rdf_cli_fileout(self)

test/test_finalnewline.py
    def testFinalNewline()

test/test_graph.py
    def testAdd(self)
    def testRemove(self)
    def testTriples(self)
    def testConnected(self)
    def testSub(self)
    def testGraphAdd(self)
    def testGraphIntersection(self)
    def testGuessFormatForParse(self)

test/test_graph_context.py
    def testConjunction(self):
    def testAdd(self):
    def testRemove(self):
    def testLenInOneContext(self)
    def testLenInMultipleContexts(self)
    def testRemoveInMultipleContexts(self)
    def testContexts(self)
    def testRemoveContext(self)
    def testRemoveAny(self)
    def testTriples(self)

test/test_sparqlstore.py
    def test_Query(self)

test/test_xmlliterals.py
    def testHTML()

**Comment by white-gecko** [comment]
To rework the test system I have opened #1268

**Comment by edmondchuc** [comment]
If you have Docker, try running the tests in a container. Introduced by https://github.com/RDFLib/rdflib/pull/1352

**Comment by gjhiggins** [comment]
Resolved by aucampia's Github Actions CI worksheet
