### ISSUE TITLE
SERVICE queries choke on certificate issues

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#1295]
Likely this is a duplicate issue...

In rdflib 6.0.0-dev, this code fails due to `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>`:

```python
import rdflib

g = rdflib.Graph()
qres = g.query(
    """
    SELECT ?s ?o
    WHERE {
      SERVICE <https://dbpedia.org/sparql> {
        ?s a ?o .
      }
    } 
    LIMIT 3
    """
)

for row in qres:
    print(row.s)

```

...and I can confirm that the above code works for insecure, i.e. HTTP, not HTTPS, SPARQL endpoints.

**Comment by nicholascar** [comment]
This issue is specific to people running Python 3.6+ on a Mac, like me. It's to do with Python on a Mac not installing the certs, rather than any RDFlib issue, so I'm closing.

**Comment by GiveMeMoreData** [comment]
I'm using Python 3.9.6 on Winodws 10, with rdflib version 6.2.0 and I had the same problem as described in this issue. Since this is exactly the problem I had, and it took me some time to find the solution I am posting it here. 

```python
import ssl  
ssl._create_default_https_context = ssl._create_unverified_context
```
