### ISSUE TITLE
Policy on type annotations

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1311]
There are not many changes needed to make to get mypy to pass, and this opens the door to adding more type annotations which makes it easier for users of the library and helps prevents errors.

Are you open to a PR that adds support for mypy to the CI pipelines and makes changes needed in the codebase for it to pass? Any preferences for config and styling (i.e. `import typing as t; import typing_extensions as te;`)?

Would really make the experience of using rdflib easier IMO.

**Comment by nicholascar** [comment]
We have a policy in place:
* type annotations are required for new PRs
* devs can run mypy if they like, but we definitely will for CICD testing

This needs to be better documented
