### ISSUE TITLE
Invalid serialization of xsd:decimal to scientific notation

### ISSUE THREAD

**Issue by wagonhelm** [RDFLib/rdflib#1314]
I'm having an issue when doing a construct query using SPARQL is returning a rdflib graph with small numbers casted as a literal in scientific notation.
```
from SPARQLWrapper import SPARQLWrapper, RDFXML
from rdflib.term import URIRef, Literal
import sys

endpoint_url = "https://query.wikidata.org/sparql"
user_agent = "WDQS-example Python/%s.%s" % (sys.version_info[0], sys.version_info[1])
sparql = SPARQLWrapper(endpoint_url, agent=user_agent)
sparql.setReturnFormat(RDFXML)
query = """CONSTRUCT { ?s ?p ?o } WHERE { VALUES ?s { wd:Q184832 } ?s ?p ?o }"""
sparql.setQuery(query)
results = sparql.query().convert()

triples = set(results.triples((None, URIRef("http://www.wikidata.org/prop/direct/P2201"), None)))

for triple in triples:
    (s, p, o) = triple
    print("triple = %s", triple)
    print("str(o) = %s", str(o))
    print("o.value = %s/%s", type(o.value), o.value)
    print("o.n3() = %s", o.n3())

```
and it's output

```
triple = %s (rdflib.term.URIRef('http://www.wikidata.org/entity/Q184832'), rdflib.term.URIRef('http://www.wikidata.org/prop/direct/P2201'), rdflib.term.Literal('1E-31', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#decimal')))
str(o) = %s 1E-31
o.value = %s/%s <class 'decimal.Decimal'> 1E-31
o.n3() = %s "1E-31"^^<http://www.w3.org/2001/XMLSchema#decimal>
```
I believe o.value should be class 'float' 

If you serialize it this

```
results.serialize(destination="wikidump-000000001.ttl", format="turtle")

with open("wikidump-000000001.ttl","r") as fp:
    for line in fp:
        if "wdt:P2201" in line:
            print(line)
```

It outputs:

```
    wdt:P2201 1E-31.0 ;
```

**Comment by aucampia** [comment]
Ideally questions like this should be asked in stackoverflow, unless it is a bug. In this case you can change the format for serialization by using `rdflib.term.bind` as follows:

```python
        endpoint_url = "https://query.wikidata.org/sparql"
        user_agent = "LINCS-https://lincsproject.ca//%s.%s" % (
            sys.version_info[0],
            sys.version_info[1],
        )
        sparql = SPARQLWrapper(endpoint_url, agent=user_agent)
        sparql.setReturnFormat(RDFXML)
        query = """CONSTRUCT { ?s ?p ?o } WHERE { VALUES ?s { wd:Q184832 } ?s ?p ?o }"""
        sparql.setQuery(query)

        rdflib.term.bind(
            XSD.decimal,
            decimal.Decimal,
            constructor=decimal.Decimal,
            lexicalizer=lambda val: f"{val:f}",
            datatype_specific=True,
        )

        results = sparql.query().convert()
        triples = set(
            results.triples(
                (None, URIRef("http://www.wikidata.org/prop/direct/P2201"), None)
            )
        )
        for triple in triples:
            (s, p, o) = triple
            logging.info("triple = %s", triple)
            logging.info("str(o) = %s", str(o))
            logging.info("o.value = %s/%s", type(o.value), o.value)
            logging.info("o.n3() = %s", o.n3())
```

Note bind comes before decode.

Full working example here: https://gitlab.com/aucampia/contrib/rdflib/-/blob/master/tests/test_issues.py#L13

Output:

```
datatype 'http://www.w3.org/2001/XMLSchema#decimal' was already bound. Rebinding.
triple = (rdflib.term.URIRef('http://www.wikidata.org/entity/Q184832'), rdflib.term.URIRef('http://www.wikidata.org/prop/direct/P2201'), rdflib.term.Literal('0.0000000000000000000000000000001', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#decimal')))
str(o) = 0.0000000000000000000000000000001
o.value = <class 'decimal.Decimal'>/1E-31
o.n3() = "0.0000000000000000000000000000001"^^<http://www.w3.org/2001/XMLSchema#decimal>
```

Please remember to close the issue

**Comment by wagonhelm** [comment]
This appears to fix my problem, thankyou @aucampia.  Originally I wasn't really sure if it was a bug or issue.

**Comment by aucampia** [comment]
@wagonhelm My appologies, I think this is actually a bug, the way you posed the question confused me and I did not actually check if the behaviour is correct.

https://www.w3.org/TR/xmlschema11-2/#decimal

> The lexical space of decimal is the set of lexical representations which match the grammar given above, or (equivalently) the regular expression
> ```
> (\+|-)?([0-9]+(\.[0-9]*)?|\.[0-9]+)
> ```

1E-31 does indeed not match that regex so a fix is needed.

Please re-open it, maybe we can change the title a bit, but as far as I can tell (after actually looking) this is a bug.

**Comment by wagonhelm** [comment]
@aucampia, I re-opened, though I do not thoroughly understand the issue or the library and fear I'm not using the right words.  Ultimately my issue was that when I tried to load the resulting turtle using Wikibase / WDQS I would get an error with any line with scientific notation.  When reloading the .ttl using rdflib it results in the following:

```
triple = %s (rdflib.term.URIRef('http://www.wikidata.org/entity/Q184832'), rdflib.term.URIRef('http://www.wikidata.org/prop/direct/P2201'), rdflib.term.Literal('1e-31', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#double')))
str(o) = %s 1e-31
o.value = %s/%s <class 'float'> 1e-31
o.n3() = %s "1e-31"^^<http://www.w3.org/2001/XMLSchema#double>
```

**Comment by aucampia** [comment]
`"1e-31"` is completely valid for `xsd:double` - but invalid for `xsd:decimal`

If I run `CONSTRUCT { ?s ?p ?o } WHERE { VALUES (?s ?p) { (wd:Q184832 <http://www.wikidata.org/prop/direct/P2201>) } ?s ?p ?o }` against Wikidata it returns this:

```bash
$ curl  --silent 'https://query.wikidata.org/sparql' --header "Accept: application/n-triples" --data-urlencode 'query=CONSTRUCT { ?s ?p ?o } WHERE { VALUES (?s ?p) { (wd:Q184832 <http://www.wikidata.org/prop/direct/P2201>) } ?s ?p ?o }'
```
```turtle
<http://www.wikidata.org/entity/Q184832>
  <http://www.wikidata.org/prop/direct/P2201> 
  "0.0000000000000000000000000000001"^^<http://www.w3.org/2001/XMLSchema#decimal> .
```

For me RDFLib formats that as `1E-31` unless I first do:

```python
        rdflib.term.bind(
            XSD.decimal,
            decimal.Decimal,
            constructor=decimal.Decimal,
            lexicalizer=lambda val: f"{val:f}",
            datatype_specific=True,
        )
```

This is a workaround though to a real issue, and I would  describe the real issue being worked around here as `Invalid serialization of xsd:decimal to scientific notation`.

If you prefer to format `xsd:double` to be serialized as decimal instead of scientific notation then that is user preference, and the right solution there would be to use `rdflib.term.bind` as follow (note `XSD.float` instead of `XSD.double`):

```python
        rdflib.term.bind(
            XSD.float,
            decimal.Decimal,
            constructor=decimal.Decimal,
            lexicalizer=lambda val: f"{val:f}",
            datatype_specific=True,
        )
```

Though I cannot guarantee this would be compliant with XSD, though I have no specific reason to doubt it would be. It's just user beware.

**Comment by aucampia** [comment]
Just noticed a mistake in my last comment and corrected it.
