### ISSUE TITLE
IRC -> Gitter/Matrix

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1341]
[`developers.rst`](https://github.com/RDFLib/rdflib/blob/master/docs/developers.rst) makes some mention of #rdflib on freenode, however with the recent developments I'm not sure what the future of freenode will be. It seems there are some people in #rdflib on libera.chat now.

There is also https://gitter.im/RDFLib/rdflib which has 27 people in, though is mostly idle also.

Should we update the documentation and README.md to mention gitter and libera.chat?

**Comment by rchateauneu** [comment]
Maybe yes, and explicitly mention that gitter has apparently merged with element.io

**Comment by nicholascar** [comment]
OK, let's kill any mention of freenode - it's dead - but then we need to decide on what other channels we're going to support. 

I'm not much into any of them but if you all prefer Gitter, let's just only use that and encourage people off libera.chat and on to that. 

@white-gecko @ashleysommer @edmondchuc @aucampia @rchateauneu @white-gecko  is Gitter your preferred channel?

**Comment by white-gecko** [comment]
I'm in the irc from time to time. At the moment there is only one other user in the room. So it might be ok to abandon it. I personally would prefer matrix and since the gitter channel is available via matrix as well this is ok. We should mention the accessibility via gitter as well as via matrix.

**Comment by nicholascar** [comment]
> We should mention the accessibility via gitter as well as via matrix.

I'm really not across all the options and combinations here! Could you perhaps draft an update to the documentation pages?

I think we need to update

* https://rdflib.readthedocs.io/en/stable/index.html - docco front page
* https://rdflib.readthedocs.io/en/stable/developers.html - developers page
* https://rdflib.dev/ - web page
* https://github.com/RDFLib/rdflib - repo README

I think only a couple of sentences are needed and the same information can be used in all those 4 locations, but I just wouldn't quite know what to write.
