### ISSUE TITLE
5.0.0 depends on six, but does not declare it

### ISSUE THREAD

**Issue by tardyp** [RDFLib/rdflib#1350]
Hello,

Trying to remove six from spdx/tools-python, I figured that the version of rdflib that is on pypi depends on six without actually declaring it.
I can see in the current master that six has been remove from rdflib.

Any plan to release a new version?

**Comment by tardyp** [comment]
sorry it was a confusion on my side :-}

**Comment by nicholascar** [comment]
Certainty no plans to put six back in and we are very close (several days) to releasing RDFlib 6.0.0 that is Python 3.6+ only, so no need for six.

If you _must_ have Pyt2 functionally, RDFlib 5.0.0 is the package for you...
