### ISSUE TITLE
Deprecate `rdflib.Graph.load()` in a release version.

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/rdflib#1356]
Leave deprecation warning in for another major version.

**Comment by ashleysommer** [comment]
The message currently says "will be removed in 6.0.0". Should we change the message, or remove it?
Also, `graph.comment()` `graph.label()` `graph.preferredLabel()` and `graph.seq()`. 
I've got to double check when we added the deprecation status to them.

**Comment by ashleysommer** [comment]
https://github.com/RDFLib/rdflib/commit/4e41b8e1e3f1be664541e705db61b80a1f0e5435
They were added _after_ the 5.0.0 release.

**Comment by ashleysommer** [comment]
I think at the time we'd intended to release a 5.1.0 with some minor fixes and these deprecations added, but it never happened because we ended up merging the python2-removal branch into master early.

**Comment by edmondchuc** [comment]
Related issue https://github.com/RDFLib/rdflib/issues/985

**Comment by gjhiggins** [comment]
Resolved in #1527
