### ISSUE TITLE
loading ontology in ttl format takes loo long

### ISSUE THREAD

**Issue by keloemma** [RDFLib/rdflib#1362]
Hello,

I have an ontology in the format "ttl" and I was advice to use rdflib to read and use it. But when trying to load the ontology to rdflib , it takes forever (after 30 min , it is still running). The ontology is language ressources with aprroximately 500 000 entries (mostly word with their description). I do not know how to speed the process. 

here is my script
```

import sys
import rdflib

g = rdflib.Graph()

g.parse(sys.argv[1], format=sys.argv[2])

print(len(g))
for stmt in g:
    print(stmt)
```

to launch I wrote on the terminal:

```
time python import.py fr_dbnary_ontolex.ttl n3

```

**Comment by rchateauneu** [comment]
Hi
Could you please share this file or a similar one so we can have a look and agree on the results ?
Thanks

**Comment by keloemma** [comment]
> Hi
> Could you please share this file or a similar one so we can have a look and agree on the results ?
> Thanks

**Comment by keloemma** [comment]
@rchateauneu    Hello which file,  the ontology  ? if it is the ontology , it can be download here  :  http://kaiko.getalp.org/about-dbnary/download/#Core_data

**Comment by keloemma** [comment]
I closed without knowing, now I reopen @rchateauneu

**Comment by nicholascar** [comment]
This is a "how do I" question, not a developer Issue, so please could this be asked on StackOverflow with the `[rdflib]` tag? So I'll close it here.
