### ISSUE TITLE
pyparsing 3.x and 2.x need simultaneous support

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/rdflib#1370]
[Issue 1190](https://github.com/RDFLib/rdflib/issues/1190) reported a breakage in the SPARQL engine from a pending change in `pyparsing` major version 3.  [PR 1366](https://github.com/RDFLib/rdflib/pull/1366) solved the problem temporarily by pinning `pyparsing` below version 3.  This unfortunately will cause an unsatisfiable complexity in any project that adopts `rdflib` while needing elsewhere a feature of `pyparsing` 3.x.

The last line of the stack trace from the original issue remains [line 114 of parserutils.py](https://github.com/RDFLib/rdflib/blob/3c509626f60cecec4c0495931728b2128aa625d4/rdflib/plugins/sparql/parserutils.py#L114) (linked commit is today's `master` branch).

**Comment by nicholascar** [comment]
@ajnelson-nist thanks for the Issue. I'll list it for 6.0.x

**Comment by ajnelson-nist** [comment]
I look forward to the release that incorporates this!  I work with some projects that had ceiling pins based on this that I'll be happy to turn into floors.  This is not a request to rush a release.
