### ISSUE TITLE
How to parse compressed file ?

### ISSUE THREAD

**Issue by bioinfornatics** [RDFLib/rdflib#1373]
Dear,

Firstly thanks for your amazing works.

I need to read a huge turtle file compressed with gunzip. And I didn't found yet how to parse such file directly or by stream which decompress on the fly.
Something like

```python
import rdflib
import gzip
my_file = 'test.ttl.gz'
with open(my_file, 'rb') as gzip_file_handler:
    with gzip.GzipFile(fileobj=gzip_file_handler) as fh:
        rdf_graph = rdflib.Graph()
        rdf_graph.parse(fileobj=fh)
```

Thanks for your help

**Comment by dargueta** [comment]
If you have Python 3, you can use [`gzip.open()`](https://docs.python.org/3/library/gzip.html#gzip.open).

```py
with gzip.open(my_file, mode="rt") as fh:
    #                          ^__ do not forget the "t" -- it indicates text mode
    rdf_graph = rdflib.Graph()
    rdf_graph.parse(fileobj=fh)
```

You can also pass in an open stream to `gzip.open()` instead of a filename.

**Comment by bioinfornatics** [comment]
thanks @dargueta 
that should works
