### ISSUE TITLE
RDF.li not in namespace (since 6.0)

### ISSUE THREAD

**Issue by carlosvega** [RDFLib/rdflib#1374]
After updating to the newest version of rdflib I started to have the following error whenever I use RDF.li

`AttributeError: term 'li' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'`

I see that is not defined in 22-rdf-syntax-ns, but is part of RDF.

> There is an rdf:li special property element that is equivalent to rdf:_1, rdf:_2 in order, explained in detail in section 7.4. The mapping to the container membership properties is always done in the order that the rdf:li special property elements appear in XML — the document order is significant. The equivalent RDF/XML to Example 17 written in this form is shown in Example 18.

https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-list-elements

> Note that RDF/XML uses li as a convenience element to avoid having to explicitly number each member. The li element assigns the properties _1, _2, and so on as necessary. The element name li was chosen to be mnemonic with the term "list item" from HTML.

https://www.w3.org/TR/1999/REC-rdf-syntax-19990222/

**Comment by white-gecko** [comment]
We had a similar issue with xsd #1364 . I assume it is due to the changes to the namespace handling in #1074. Could you try to add it to the respective namespace file and provide a pull-request?

**Comment by niklasl** [comment]
As you say, there is no `rdf:li` property defined in RDF. It is just used in the RDF/XML *syntax* as a "magic" element to utilize the element order to figure out the correct property to use.

What is certainly an error is that the `_{positive_integer}` forms seems to be sorely missing from the `RDF` `DefinedNamespace` as of 6.0.

In the vocabulary, one needs to have all positive integers defined in order to allow arbitrarily large RDF containers (if absolutely *necessary*, I'd say mint them on the fly using a specific Namespace subclass for RDF in particular). Of course, in practise, one should reasonably use RDF collections instead, and also in practise, it is "less likely" that one would use more than up to around `rdf:_100` (or `rdf:_1000`, or some other arbitrarily "non-too-large" number).

**Comment by carlosvega** [comment]
Yes but has to be allowed, as stated in https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-list-elements otherwise you won't be able to parse XML files with `rdf:li` elements.

> RDF has a set of container membership properties and corresponding property elements that are mostly used with instances of the rdf:Seq, rdf:Bag and rdf:Alt classes which may be written as typed node elements. The list properties are rdf:_1, rdf:_2 etc. and can be written as property elements or property attributes as shown in Example 17. There is an rdf:li special property element that is equivalent to rdf:_1, rdf:_2 in order, explained in detail in section 7.4. The mapping to the container membership properties is always done in the order that the rdf:li special property elements appear in XML — the document order is significant. The equivalent RDF/XML to Example 17 written in this form is shown in Example 18.

Even the W3C RELAX NG Compact Schema for RDF/XML says something about this element:

> # Also needed to allow rdf:li on all property element productions
> # since we can't capture the rdf:li rewriting to rdf_<n> in relaxng

Many XML files make use of `rdf:li` elements, for example SBML models that require proper parsing. What's the alternative then to produce something like:

```
<rdf:Bag>
<rdf:li rdf:resource="urn:miriam:refseq:NM_014874"/>
</rdf:Bag>
```

You can find thousands of examples of XML files using `rdf:li` property in https://www.ebi.ac.uk/biomodels/. For example https://www.ebi.ac.uk/biomodels/BIOMD0000000811#Files

How can we then generate and XML like above's example with the new release of rdflib?

**Comment by niklasl** [comment]
Yes, and it has always been particular to RDF/XML. It has to be handled by the RDF/XML parsers and serializers, not on the triple level.  (There is no `rdf:li` in the RDF vocabulary, just as there is no `rdf:Description` nor `rdf:about`, `rdf:resource ` etc., as these are all specific to the RDF/XML syntax.)

A quick glance and test shows that the RDF/XML parser fully handles this, also in 6.0, whereas the RDF/XML serializers, even the "pretty-xml" variant, emit the `rdf:_{positive_integer}` form as is (and has always done so, IIRC). So, albeit that is not formally wrong, there is room for improvement there.

My main point is: do not make it appear that `rdf:li` is a defined RDF property with implied magical ordering, as *there is no defined ordering of triples*. (And the corollary to that point is, prefer to use RDF collections when possible.) If you want to use them unordered, I guess you can use their super-property `rdfs:member` (but expect nothing to do anything special with that).

**Comment by niklasl** [comment]
And to be clear; there *is* a regression in RDFLib 6.0, as this used to work:

```python
a = g.resource(URIRef('A'))
bag = g.resource(BNode())
bag.add(RDF.type, RDF.Bag)
a.add(RDFS.seeAlso, bag) 
                                          
bag.add(RDF[1], URIRef('B'))
bag.add(RDF[2], URIRef('C'))
bag.add(RDF[3], URIRef('D'))
```
(Though I didn't know that, and would have preferred just a regular `RDF['_1']` to be explicit; which apparently, didn't work as of 4.2.2 at least.)

A work-around until that is fixed is something like:

```python
bag.add(URIRef(f'{RDF}_1'), URIRef('B'))
bag.add(URIRef(f'{RDF}_2'), URIRef('C'))
bag.add(URIRef(f'{RDF}_3'), URIRef('D'))
```

**Comment by nicholascar** [comment]
Yes, you can always force a URI through past the `DefinedNamespace`  / `ClosedNamespace` check by using direct `URIRef` declarations like `URIRef(f'{RDF}_1')` or `URIRef(f'{RDF}li')` etc.

I think I'd prefer to keep the current `ClosedNamespace` for RDF and still throw errors with non defined terms such as `RDF.li` etc. as this forces good vocab use behaviour, so perhaps we just need to document how to get around this for these odd RDF terms like `li`, `_1`, `_1000000` etc. as per `URIRef` use above.

Could people live with this or do we have to relax for `RDF.li`? 

Will have to look into the `Bag` regression thing too.

We plan on a patch update of 6.0.1 ASAP, like next week, as I have some documentation updates, so we can make any necessary changes here fast.

**Comment by niklasl** [comment]
Allowing `RDF.li` is *wrong* (there is no such property in the RDF vocabulary even "in spirit"), but allowing for `RDF[1]` (reasonably minting them on the fly, possibly persisting for speed) would be needed for backwards compatibility (that's the regession; I just used a bag in the example).

Allowing for `RDF['_1']` to mint these (on the fly) might be nice too, but  `RDF._1` might be going too far (remember that there is no end to these).

**Comment by carlosvega** [comment]
Thank you very much for the help and support. Just to clarify. I know that the problem relates to the XML representation of RDF but somehow I think this breaks some compatibility when parsing/creating XML files with certain XML/RDF elements. At least, it should be documented how to keep producing/parsing the files with this new release as we used to do with the previous release.

One quick fix is to set `RDF._fail` to `False` but I don't like this solution. Creating a custom URIRef seems like another option. IRC, what the w3c seems to agree is that they must be converted to `_1`, `_2` when a `rdf:li` is read. This means that there must be a way to read XML files containing `rdf.li` elements and also to write them.

The conflict between RDF schema and the XML representation has been discussed in W3C but my understanding is that a parser must support such property `rdf:li` to allow creating XML files.

Useful reference: https://www.w3.org/2000/03/rdf-tracking/#rdf-containers-syntax-vs-schema

Another useful sentence is written here: https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-list-elements

> Any other names are not defined and should generate a warning when encountered, but should otherwise behave normally.

For example, my code used to do like:

```
		bqbiol = Namespace("http://biomodels.net/biology-qualifiers/")
		bqmodel = Namespace("http://biomodels.net/model-qualifiers/")
		vcard   = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
		graph = rdflib.Graph()
		graph.bind('vCard', vcard)
		graph.bind('dc', DC)
		graph.bind('dcterms', DCTERMS)
		graph.bind('bqbiol', bqbiol)
		graph.bind('bqmodel', bqmodel)
		graph.bind('xsd', XSD)
		description = rdflib.URIRef(f'#{metaId}')
		
		#creator info
		author = ...
		creator_bag_node = rdflib.BNode()
		creator_vcard_node = rdflib.BNode()
		graph.add((description, DC.creator, creator_bag_node))
		graph.add((creator_bag_node, RDF.type, RDF.Bag))
		graph.add((creator_bag_node, RDF.li, creator_vcard_node))
		graph.add((creator_vcard_node, RDF.type, vcard.N))
		graph.add((creator_vcard_node, vcard.Family, rdflib.Literal(author.family_name)))
		graph.add((creator_vcard_node, vcard.Given, rdflib.Literal(author.first_name)))
```

to generate

```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:vCard="http://www.w3.org/2001/vcard-rdf/3.0#" xmlns:vCard4="http://www.w3.org/2006/vcard/ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/" xmlns:bqmodel="http://biomodels.net/model-qualifiers/">
        <rdf:Description rdf:about="#modelname">
          <dcterms:creator>
            <rdf:Bag>
              <rdf:li rdf:parseType="Resource">
                <vCard4:hasName rdf:parseType="Resource">
                  <vCard4:family-name>family_name</vCard4:family-name>
                  <vCard4:given-name>first_name</vCard4:given-name>
                </vCard4:hasName>
              </rdf:li>
            </rdf:Bag>
          </dcterms:creator>
        </rdf:Description>
      </rdf:RDF>
```

How could I generate the same thing with the new release? Should I use `URIRef(f'{RDF}li')` as @nicholascar recommends?

**Comment by niklasl** [comment]
@carlosvega 

> IRC, what the w3c seems to agree is that they must be converted to `_1`, `_2` when a `rdf:li` is read. This means that there must be a way to read XML files containing `rdf.li` elements and also to write them.

Reading them should work just fine. I've thrown some examples at the parser and it produces the correct `rdf:_{x}` predicates, honouring the order of XML `rdf:li` elements on input.

However, the RDF/XML serializer does not, nor has it ever it seems, produced the syntax shorthand on output, alas. This might have led you and possibly others into tricking it to produce that form using `RDF.li` directly. That this does not work anymore is actually a Good Thing™, as there is no guaranteed order on output! (Not much of a practical issue with `rdf:Bag` of course.)

> The conflict between RDF schema and the XML representation has been discussed in W3C but my understanding is that a parser must support such property `rdf:li` to allow creating XML files.

Yes, and per above, it does. As in, the *parser* supports it. RDFLib at this time does not support creating the shorthand form in RDF/XML on output. (Which is not formally a problem, but can be a practical one if RDF-unaware XML consumers expect particular forms.)

> Another useful sentence is written here: https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-list-elements
> 
> > Any other names are not defined and should generate a warning when encountered, but should otherwise behave normally.

Here RDFLib actually doesn't complain at all when unknown forms such as `rdf:li` appears in e.g. Turtle data (as we know, in RDF/XML, it is specially treated and never reaches any triple). You're just not allowed to conveniently create them using the `DefinedNamespace` utility.

> How could I generate the same thing with the new release? Should I use `URIRef(f'{RDF}li')` as @nicholascar recommends?

Almost; you *should* use `URIRef(f'{RDF}_{n}')`, where `n` is an integer in the 1-based order the items appear. Like:

```python
...

description = rdflib.URIRef(f'#{metaId}')
		
creator_bag_node = rdflib.BNode()
graph.add((description, DC.creator, creator_bag_node))
graph.add((creator_bag_node, RDF.type, RDF.Bag))
for i, author in enumerate(authors):
	creator_vcard_node = rdflib.BNode()
	graph.add((creator_bag_node, rdflib.URIRef(f'{RDF}_{i + 1}'), creator_vcard_node))
	graph.add((creator_vcard_node, RDF.type, vcard.N))
	graph.add((creator_vcard_node, vcard.Family, rdflib.Literal(author.family_name)))
	graph.add((creator_vcard_node, vcard.Given, rdflib.Literal(author.first_name)))
```

You *could* use the same approach for `rdf:li` to *coax* the serializer into producing the desired syntactic form. Just know two things: 1) that does *not* honour the order at all, 2) it might break in the future. The above example should keep on working even if a convenience mechanism is added.

Funny thing; I just recalled that there *is* a utility, in `rdflib.container`! So the above can be reduced to:

```python
from rdflib.container import Bag

...

description = rdflib.URIRef(f'#{metaId}')

creator_bag = Bag(graph, None)
graph.add((description, DC.creator, creator_bag_node))
for author in authors:
	creator_vcard_node = rdflib.BNode()
	creator_bag.append(creator_vcard_node)
	graph.add((creator_vcard_node, RDF.type, vcard.N))
	graph.add((creator_vcard_node, vcard.Family, rdflib.Literal(author.family_name)))
	graph.add((creator_vcard_node, vcard.Given, rdflib.Literal(author.first_name)))
```

For outputting RDF/XML, as ugly as the following is, if you really need the exact syntactic shape Right Now™, I'd almost suggest post-processing the output string, like:
```python
import re

rdfli_pattern = re.compile(r'\brdf:_\d+\b')  

pretty = graph.serialize(format='pretty-xml')
prettier = rdfli_pattern.sub('rdf:li', pretty)
print(prettier)
```

(As an aside I personally recommend using `graph.resource(...)` to reduce some code repetition when adding many triples about the same subject.)

**Comment by carlosvega** [comment]
Thanks @niklasl the container Bag utility is working great. It creates elements like `_1`, `_2`.
Now the problem is on a library that parses XML, (libsbml) that does not recognise that syntax (although it should), but does indeed work when I replace the numbers for `li`… 

Thanks for the support and thanks for clarifying this issue to me. You can close my PR and issue.

https://github.com/sbmlteam/python-libsbml/issues/24

**Comment by nicholascar** [comment]
Thanks @niklasl for all the support!
