### ISSUE TITLE
Update XSD Namespace

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#1391]
The current XSD namespace uses values from <http://www.w3.org/TR/xmlschema-2/> but we should be using values from <http://www.w3.org/TR/xmlschema11-2/>. As a result, we are missing things like `xsd:dateTimeStamp`.

**Comment by gtfierro** [comment]
@nicholascar I was looking into fixing this, but then I noticed a comment in [this file](https://github.com/RDFLib/rdflib/blob/master/rdflib/namespace/_XSD.py#L9-L10) that the DeclaredNamespace is generated automatically from the XSD file. Is this generation script available anywhere?

**Comment by nicholascar** [comment]
@edmondchuc @hsolbrig where is the script that was used to make DeclaredNamespace instances?

@gtfierro a script was indeed used but, as this issue shows, it missed some things. Probably because the real world namespace is made from details from multiple locations. Even though I’ve asked for the script above, I think it would be easiest to just add the bits known to be missing. This is sort of a one-time task anyway.
