### ISSUE TITLE
Unable to round-trip skolemize() and de_skolemize()

### ISSUE THREAD

**Issue by edwardanderson** [RDFLib/rdflib#1404]
I would like to be able to perform a round-trip skolemize and deskolemize on a graph. While `graph.skolemize()` works expectedly, I'm not able to convert the URIs back into blank nodes.

Convert a blank node to URI:

```python
from rdflib import Graph


ttl = '''
@prefix wd: <http://www.wikidata.org/entity/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

wd:Q1203 foaf:knows [ a foaf:Person;
    foaf:name "Ringo" ].
'''

graph = Graph()
graph.parse(data=ttl, format='turtle')
skolemized = graph.skolemize()
skolemized.namespace_manager.bind('foaf', 'http://xmlns.com/foaf/0.1/')
print(skolemized.serialize(format='turtle'))
```

```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

<http://www.wikidata.org/entity/Q1203> foaf:knows <http://rdlib.net/.well-known/genid/rdflib/n1c65f973c8e54cb2a6d199e36ec26a22b1> .

<http://rdlib.net/.well-known/genid/rdflib/n1c65f973c8e54cb2a6d199e36ec26a22b1> a foaf:Person ;
    foaf:name "Ringo" .
```

All good. However `graph.de_skolemize()` returns the URI unchanged:

```python
deskolemized = skolemized.de_skolemize()
deskolemized.namespace_manager.bind('foaf', 'http://xmlns.com/foaf/0.1/')
print(deskolemized.serialize(format='turtle'))
```

```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

<http://www.wikidata.org/entity/Q1203> foaf:knows <http://rdlib.net/.well-known/genid/rdflib/n1c65f973c8e54cb2a6d199e36ec26a22b1> .

<http://rdlib.net/.well-known/genid/rdflib/n1c65f973c8e54cb2a6d199e36ec26a22b1> a foaf:Person ;
    foaf:name "Ringo" .
```

I wonder if this is to do with the type checking inside [`do_de_skolemize2()`](https://rdflib.readthedocs.io/en/stable/_modules/rdflib/graph.html#Graph.de_skolemize)? As none of the subjects or objects in the graph are `isinstance(_, Genid)`, no deskolemize operation appears to be performed.

If I explicitly change the type and test for a string pattern, however, the URIs can be converted back to blank nodes:

```python
from rdflib.term import Genid


deskolemized = Graph()
skolem_base = 'http://rdlib.net/.well-known/genid/rdflib/'
for triple in skolemized:
    (s, p, o) = triple
    if str(s).startswith(skolem_base):
        s = Genid(s).de_skolemize()

    if str(o).startswith(skolem_base):
        o = Genid(o).de_skolemize()

    deskolemized.add((s, p, o))

deskolemized.namespace_manager.bind('foaf', 'http://xmlns.com/foaf/0.1/')
print(deskolemized.serialize(format='turtle'))
```

```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

<http://www.wikidata.org/entity/Q1203> foaf:knows [ a foaf:Person ;
            foaf:name "Ringo" ] .
```

To make the round-trip work with a single `graph.de_skolemize()`, should I be supplying the function with extra parameters? Or maybe modify the `rdflib.term.rdflib_skolem_genid` variable?

**Comment by edmondchuc** [comment]
I think the issue is due to `BNode.skolemize()` returning a `URIRef` instead of a `Genid` https://github.com/RDFLib/rdflib/blob/327de4ecc9e7a9a7c73b55d1b59b6e1e600f64ed/rdflib/term.py#L438-L449

I will create a PR for this.
