### ISSUE TITLE
Restore default implementation of Store.namespaces

### ISSUE THREAD

**Issue by mwatts15** [RDFLib/rdflib#1431]
The `Store` class has had an implementation of `namespaces` which returns an empty generator. This was removed in 6.0.2, so that stores which don't support namespaces would have to implement the method in order to work with code which queries for namespaces with this method (e.g., by creating a namespace manager) generically without knowing the underlying `Store`.

breaking commit: https://github.com/RDFLib/rdflib/commit/90f6fe5611f4c7411e5eac347cafb9d009829b6c

**Comment by aucampia** [comment]
Could you share the specific error you are receiving and clarify where it is coming from?

I will try add a test to confirm.

**Comment by aucampia** [comment]
For posterity sake, without `if False: yield None`, the test added in #1432 fails with:

```
$ .venv/bin/python3 -m unittest  --failfast test.test_store
E
======================================================================
ERROR: test_namespaces (test.test_store.TestAbstractStore)
This tests that Store.namespaces is an empty generator.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/iwana/sw/d/github.com/iafork/rdflib/test/test_store.py", line 14, in test_namespaces
    self.assertEqual(list(my_store.namespaces()), [])
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by mwatts15** [comment]
Essentially, here's how I encountered this issue:
```
from rdflib.graph import Graph
from rdflib.namespace import NamespaceManager
from rdflib.store import Store


class AStore(Store):
    def triples(self, pattern, context=None):
        if False:
            yield None


g = NamespaceManager(Graph(store=AStore()))
```

**Comment by aucampia** [comment]
Thanks @mwatts15 and sorry for breaking it. I added another unit tests for it via `NamespaceManager`.

**Comment by mwatts15** [comment]
@aucampia , no worries. Thanks for responding so quickly and comprehensively :)
