### ISSUE TITLE
Support HexTuples RDF format

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#1437]
The [HexTuples](https://github.com/ontola/hextuples) RDF format looks simple yet powerful. Support for this in RDFlib could be made easily using perhaps the [jsonlines](https://jsonlines.readthedocs.io/) JSON parser which supports NDJSON.

The reason for this request isn’t just the touted performance of the format in a browser but also because it’s extremely simple and explicit so I think it would assist new RDF users to differentiate BlankNodes, Named Nodes, datatypes and languages.

**Comment by nicholascar** [comment]
@joepio, author of HexTiples spec, you might be interested in this

**Comment by nicholascar** [comment]
Looks simple, yay! I’ll make sure correct attributions to the spec and implementation authors are added to any code in RDFlib.

**Comment by gjhiggins** [comment]
Finalized in https://github.com/RDFLib/rdflib/commit/dabcacf3bfda83715e3bc4afb85d10e7ae2630ce
