### ISSUE TITLE
Type annotations? 

### ISSUE THREAD

**Issue by pudo** [RDFLib/rdflib#1447]
I've just noticed that rdflib 6.0 marks itself as `py.typed` but that basic types, like `URIRef`, `Literal` and `Namespace` have no type annotations. This makes it impossible to write strictly typed mypy code against the library. Is there some thinking behind this - i.e. are you planning to roll out actual type annotations?

**Comment by aucampia** [comment]
The plan is more or less to do gradual typing, and maybe eventually getting to the point of being able to use this library with strictly typed code, however this will be a lengthy process. `py.typed` is there mainly to inform type checkers that typing information from rdflib comes from rdflib and not somewhere else. Without it type checkers will complain that rdflib is untyped.

Is the presence of `py.typed` with only partial type hints causing specific problems, and if so could you share more detail about it?

**Comment by eggplants** [comment]
Ref: https://github.com/eggplants/rdflib/tree/type_more_strict

Now I'm trying to make mypy more strict.

---

pyparsing will be published as a typed package in the next release soon. (Ref: https://github.com/pyparsing/pyparsing/pull/364)

isodate also will be done. (Ref: https://github.com/gweis/isodate/pull/72)

**Comment by eggplants** [comment]
html5lib has stubs in typeshed as types-html5lib.

berkeleydb is not exist any stubs. So I just created as [berkeleydb-stubs](https://github.com/eggplants/berkeleydb-stubs).

networkx is still on a long way to go. (Ref: https://github.com/networkx/networkx/issues/3988)

**Comment by aucampia** [comment]
For anyone interested, I have a bunch of typing in https://github.com/aucampia/rdflib/tree/iwana-20220126T2212-typing - I will start integrating it with master branch quite soon, but only bit by bit. Don't be discourgaged to add any types though, I rebase regularly as I use this to make it easier to fix bugs.

CC: @ajnelson-nist

**Comment by aucampia** [comment]
@pudo we added a bunch of type hints in 6.2.0 and and will add more in the next release, furthermore there are various options to mitigate the missing type hints in parts of RDFLib, including the option to treat it as untyped using:

https://github.com/python/typing/discussions/911#discussioncomment-1536037

```
[mypy]
[mypy-rdflib.*]
follow_imports = skip
```

We also describe the type hints and the gradual typing process in detail here <https://rdflib.readthedocs.io/en/latest/type_hints.html>.

Unless there is something more you want in this PR I will close it.

If there are more specific issues for specific type hints that you want please raise a issue specifically for that, but in general we want type hints for everything, and we will accept PRs adding type hints, ideally as small as possible and ideally they should only change type hints and nothing else.
