### ISSUE TITLE
Tests for translateAlgebra are not integrated with other unit tests

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1451]
As far as I can tell `translateAlgebra` tests (stuff in `test/translate_algebra/...`) are not integrated with other unit tests and will not run when `run_tests.py` or `nosetests` run.

```
$ \rm -rv .venv
$ python3.7 -m venv .venv
$ .venv/bin/python3 -m pip install -r requirements.txt -r requirements.dev.txt
$ export PYTHONPATH=$(readlink -f .):$(readlink -f .venv)
$ .venv/bin/python test/translate_algebra/main.py
Traceback (most recent call last):
  File "test/translate_algebra/main.py", line 1, in <module>
    from test_base import Test, TestExecution, format_text
  File "/home/iwana/d.x/github.com/RDFLib/rdflib/test/translate_algebra/test_base.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
$ .venv/bin/python3 -m pip install pandas
$ .venv/bin/python test/translate_algebra/main.py
Traceback (most recent call last):
  File "test/translate_algebra/main.py", line 1, in <module>
    from test_base import Test, TestExecution, format_text
  File "/home/iwana/d.x/github.com/RDFLib/rdflib/test/translate_algebra/test_base.py", line 5, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
$ .venv/bin/python3 -m pip install tabulate
```

Furthermore it seems these tests need `pandas` and `tabulate` and seems to be expecting a file `test/config.ini` with a section `TEST`

```
$ .venv/bin/python test/translate_algebra/main.py
Executing tests ...
Traceback (most recent call last):
  File "test/translate_algebra/main.py", line 889, in <module>
    t.run_tests()
  File "/home/iwana/d.x/github.com/RDFLib/rdflib/test/translate_algebra/test_base.py", line 107, in run_tests
    logging.getLogger().setLevel(int(self.test_config.get("TEST", "log_level")))
  File "/usr/lib64/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'TEST'
```

https://github.com/RDFLib/rdflib/blob/f4e1efd17f5faf8479bc04693929ced07a172ebf/test/translate_algebra/test_base.py#L62-L65

https://github.com/RDFLib/rdflib/blob/f4e1efd17f5faf8479bc04693929ced07a172ebf/test/translate_algebra/test_base.py#L107

Ideally this should be integrated with the rest of the tests, it should run when run_tests.py runs and when drone CI runs, it should also have all dependencies in requirements.dev.txt and it should have all required config files.

The best option would be to base the test system used for translateAlgebra on python's unittest module.

See also:

 - https://github.com/RDFLib/rdflib/pull/1322 - The original PR that introduced `translateAlgebra`
 - https://github.com/RDFLib/rdflib/pull/1361 - Some fixes (not merged yet)

**Comment by GreenfishK** [comment]
Yes, I know that my test system differs from the one rdflib uses and I need to integrate it. At the time I wrote the tests I was not aiming to merge the function to rdflib but only came up with the idea at a later point. However, I will put it on my todo list.

**Comment by aucampia** [comment]
@GreenfishK working on this in #1635 - the first step was just to call the existing tests from pytest. However test #1 is failing.

Will continue working on it.

**Comment by aucampia** [comment]
For details about the failure see: https://github.com/RDFLib/rdflib/runs/4662843569?check_suite_focus=true

```
                test.yn_passed
            ), f"test #{test.test_number} {test.test_name} failed: {test.tc_desc}"
E           AssertionError: test #1 test_functions__functional_forms failed: Test if functional forms are properly translated into the query text. The query must also be executable and shall not violate any SPARQL query syntax.
E           assert False
E            +  where False = <test_base.Test object at 0x7f3e9c776a50>.yn_passed

```

**Comment by aucampia** [comment]
So as far as I can tell, what these tests do is basically to round trip the queries by first parsing them to algebra, and then converting algebra back to text, and then running the query.

There is one case where it looks like there is an attempt to execute the query: https://github.com/RDFLib/rdflib/blob/43d86224382d64fba2e5e17acedea1704631e097/test/translate_algebra/main.py#L70-L82

But as far as I can tell `rdf_engine` will always be None, so I don't see how this will ever work:

```console
$ grep -ri rdf_engine test
grep: test/translate_algebra/__pycache__/main.cpython-38.pyc: binary file matches
test/translate_algebra/main.py:        self.rdf_engine = None
test/translate_algebra/main.py:            self.rdf_engine.get_data(
```

Working now on converting them to pytest, can all be done in one parameterized test if my reading is correct.

**Comment by aucampia** [comment]
Actually that is the one test that fails, so I guess the best option is to just not try and run the query trhough a None valued variable.

**Comment by aucampia** [comment]
Confirmed with script that each test has this basic block with one or two exceptions which is added exception handling in the middle of this block.

```python
        query_tree = parser.parseQuery(self.query_text)
        query_algebra = algebra.translateQuery(query_tree)
        self.query_from_algebra = translateAlgebra(query_algebra)

        query_tree_2 = parser.parseQuery(self.query_from_algebra)
        query_algebra_2 = algebra.translateQuery(query_tree_2)
        self.query_from_query_from_algebra = translateAlgebra(query_algebra_2)
        _pprint_query(self.query_from_query_from_algebra)
```

**Comment by aucampia** [comment]
https://github.com/RDFLib/rdflib/pull/1636 converts the unit tests to pytests.
