### ISSUE TITLE
Get a DOI for RDFLib

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1454]
I have been thinking, maybe if we have a DOI for RDFLib linked to contributors it may give people some incentive to contribute, and it may anyway make it easier to cite and get more prominence for RDFLib which may also get more contributors. If this reasoning makes sense to anyone else we can maybe look at setting up Zenodo and getting a DOI from there as per this guide: https://guides.github.com/activities/citable-code/

**Comment by aucampia** [comment]
I enabled zenodo for this repo now, however the DOI will only be generated after the next release, will add a shield then.

**Comment by aucampia** [comment]
DOI has been assigned: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.6845245.svg)](https://doi.org/10.5281/zenodo.6845245)

**Comment by ArenasGuerreroJulian** [comment]
"eggplants" is included as an author in Zenodo. Is this an error?

**Comment by aucampia** [comment]
> "eggplants" is included as an author in Zenodo. Is this an error?

It is not, @eggplants have indeed made contributions to RDFLib: https://github.com/RDFLib/rdflib/pulls?q=is%3Apr+author%3Aeggplants+is%3Aclosed+is%3Amerged

I will add a [CITATION.cff file](https://github.com/RDFLib/rdflib/issues/2059) sometime so we have more control over what goes into ZENODO but as we don't know the real name of some users there will be cases like that.

**Comment by ArenasGuerreroJulian** [comment]
Ohhh okay, thanks @aucampia . CITATION.cff would be definitely nice for the repo :)

**Comment by eggplants** [comment]
My real name is Wataru Haruna. My proof of online identities is available on [Keybase](https://keybase.io/egpl0). If you mind that my handle name slip into the author section, replace with this.
