### ISSUE TITLE
Nondeterministic graph serialization

### ISSUE THREAD

**Issue by jbulow** [RDFLib/rdflib#1457]
The default value  of parameter `_sn_gen` in `BNode`'s `__new__` method introduce randomness in the serialization of the graph. The code below may result in different output for each run. In some situations it is desirable to have deterministic output for a given piece of code. One option is to explicitly pass the `value` parameter to the `BNode` constructor. Another method is to "monkey patch" the uuid function to run from a specific seed. 

Is there an easier way of achieving deterministic serialization of a graph containing blank nodes? 

```
from rdflib import Graph, BNode, URIRef

g = Graph()

bn1 = BNode()
bn2 = BNode()

g.add((bn1, URIRef('P1'), URIRef('O1')))
g.add((bn2, URIRef('P2'), URIRef('O2')))

print(g.serialize(format="turtle"))
```

**Comment by gjhiggins** [comment]
> In some situations it is desirable to have deterministic output for a given piece of code. One option is to explicitly pass the `value` parameter to the `BNode` constructor. Another method is to "monkey patch" the uuid function to run from a specific seed.
> Is there an easier way of achieving deterministic serialization of a graph containing blank nodes?

No, I don't believe there is an easier way. `BNode.__new__()` is commented “only store implementations should pass in a value” but there isn't any enforcement, so passing deterministic values as the BNode value is the most straightforward approach.

**Comment by aucampia** [comment]
> Is there an easier way of achieving deterministic serialization of a graph containing blank nodes?

This should really be a question posted to stackoverflow, but in short, you should be able to do it with [`rdflib.compare.to_canonical_graph`](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.compare.to_canonical_graph) - this should return a deterministic graph.

This is however bugged, and fails in some cases, for more information about the bug you kind of have to read through some spaghetti:

- https://github.com/RDFLib/rdflib/issues/1797
- https://github.com/RDFLib/rdflib/discussions/1610
- https://github.com/RDFLib/rdflib/issues/1294

**Comment by aucampia** [comment]
@jbulow I will close this issue if there is nothing further, the bug with [`rdflib.compare.to_canonical_graph`](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.compare.to_canonical_graph) will be tracked in https://github.com/RDFLib/rdflib/issues/1797.
