### ISSUE TITLE
Python string methods collide with attributes for Namespace

### ISSUE THREAD

**Issue by gjhiggins** [RDFLib/rdflib#1468]
```
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdflib.namespace import Namespace
>>> EX_NS = Namespace('http://example.com/')
>>> x = EX_NS['partition']
>>> print(x)
http://example.com/partition
>>> y = EX_NS.partition
>>> print(y)
<built-in method partition of Namespace object at 0x7f114a5cb580>
```

**Comment by edmondchuc** [comment]
Not really sure if this is a bug. `Namespace` is a subclass of `str`, so it makes sense to be able to call the [string methods](https://docs.python.org/3/library/stdtypes.html#string-methods).

Maybe `Namespace` should be reworked to not subclass from `str`?

**Comment by gjhiggins** [comment]
Closing, as edmondchuc observes, Namespace is a subclass of `str` and this was first noted back in 2015 in https://github.com/RDFLib/rdflib/issues/556 - where the discussion included considerations of reworking Namespace subclassing, so this is just a duplicate.
