### ISSUE TITLE
Write EARL test reports by default

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1479]
Currently with pytest EARL report plugin a user has to specify a report file to generate reports.

I thought about it a bit and it may be best to just always generate the reports, one for each test suite.

Creating issue mostly to see what others thinks about this.

**Comment by aucampia** [comment]
I plan to work on this soon, I will write the test report to a file that is ignored by git by default, people can then manually rename to files that is not ignored to get it into git.

**Comment by aucampia** [comment]
I looked at this a bit, I think the first step is to get everything that works on manifests working through the same manifest processing system, currently the jsonld stuff does not use `read_manifest` like everything else, if it did it would be easier to use this to inject the name of the report to write to.

**Comment by aucampia** [comment]
EARL tests will be written by default for test suites using the new DAWG manifest processor added in https://github.com/RDFLib/rdflib/pull/1986

**Comment by gjhiggins** [comment]
> EARL tests will be written by default for test suites using the new DAWG manifest processor added in #1986

Looking forward this.

**Comment by aucampia** [comment]
Closing this as master branch will write test reports by default, still need to move some additional test suites to the new manifest test system though.
