### ISSUE TITLE
No matching distribution found for rdflib==6.0.2

### ISSUE THREAD

**Issue by div927** [RDFLib/rdflib#1506]
python version - 3.6.9

`pip install rdflib==6.0.2                                                                                                                                                 1 err  flask py  12:33:51 PM
Collecting rdflib==6.0.2
  Could not find a version that satisfies the requirement rdflib==6.0.2 (from versions: 2.4.1, 2.4.2, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.4.0, 4.0, 4.0.1, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 4.2.2, 5.0.0rc1, 5.0.0)
No matching distribution found for rdflib==6.0.2`

**Comment by aucampia** [comment]
Very peculiar indeed:

```console
$ pipx run --no-cache --spec rdflib==6.0.2 --python python3.6 rdfpipe --help
⚠️  rdfpipe is already on your PATH and installed at /home/iwana/.local/bin/rdfpipe. Downloading and running anyway.
Fatal error from pip prevented installation. Full pip output in file:
    /home/iwana/.local/pipx/logs/cmd_2021-12-15_09.21.59_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement rdflib==6.0.2 (from versions: 2.4.1, 2.4.2, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.4.0, 4.0, 4.0.1, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 4.2.2, 5.0.0rc1, 5.0.0)
    ERROR: No matching distribution found for rdflib==6.0.2
Error installing rdflib from spec 'rdflib==6.0.2'.

```

**Comment by aucampia** [comment]
Ah, @div927 sorry about that, forgot that 6.x dropped support for python 3.6, you need to move to python 3.7

**Comment by aucampia** [comment]
@div927 sadly we don't support python 3.6 in 6.x and it will soon be end of life, best advice is to migrate to python 3.7 or later. Hope that answers all your questions, I will close the issue next week if there is no further responses.

**Comment by aucampia** [comment]
Closing as there are no further questions.
