### ISSUE TITLE
IdentifiedNode should be used in Graph.triples() and related iterators

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/rdflib#1696]
I started a patch to try to strengthen the type signature of `Graph.triples()`.  The gist is, the signature should be changed from:

```python
def triples(
    self, triple: Tuple[Optional[Node], Union[None, Path, Node], Optional[Node]]
):
```

to

```python
def triples(
    self, triple: Tuple[Optional[IdentifiedNode], Union[None, Path, IdentifiedNode], Optional[Node]]
) -> Iterable[Tuple[IdentifiedNode, IdentifiedNode, Node]]:
```

to let the type system catch "thing-or-string" errors from trying to put `Literal`s into the wrong triple position.

I implemented the above change (draft PR coming in a minute, I need the Issue number first), and followed through with the analogous signatures for `Graph.subjects`, `Graph.subject_predicates`, and alike for the SPO combinations.  This revealed some deeper architectural issues that prevent immediate adoption of the new signature.  Issues were found via `mypy`.  (I'm also aware the middle triple-member of the return type needs some review with respect to `Path`.)

* `/rdflib/graph.py` and `/rdflib/paths.py` have circular dependencies that seem to necessitate a higher in-common module.  The issues boil down to `evalPath()` needing the signature of `Graph.triples()`, but `graph.py` imports `paths.py` and defines `Graph.triples` using `Path.eval()`, which in all subclass implementations calls `evalPath()`, closing the loop.
* `/rdflib/compare.py` has some type signatures that assumed general `Node`s, and from a 2-minute glance it isn't immediately obvious to me whether a `IdentifiedNode` can be used in place of `Node` usage from before.  Patch 2 in the PR fixes these, and IMO looks good enough to merge independently except for the dangling `Path` question.
* There are typing issues in `rdflib/plugins/serializers/rdfxml.py` that I think I managed to work around, using `IdentifiedNode` instead of `Identifier`.  Patch 3 in the PR fixes these, and (also) IMO looks good enough to merge independently except for the dangling `Path` question.

So, this type signature revision ended up blossoming into a rearchitecting project.  If the maintainers are interested in the signature on `Graph.triples()` being refined to enable some safety around `Literal` placement, what would be the next steps, broadly speaking?  Moving the circular type dependencies into a higher inner module?

**Comment by aucampia** [comment]
> * `/rdflib/graph.py` and `/rdflib/paths.py` have circular dependencies that seem to necessitate a higher in-common module.  The issues boil down to `evalPath()` needing the signature of `Graph.triples()`, but `graph.py` imports `paths.py` and defines `Graph.triples` using `Path.eval()`, which in all subclass implementations calls `evalPath()`, closing the loop.

I will try go through your post in more detail when I have time, but for type checking placing imports inside `if TYPE_CHECKING:` should help alleviate problems of circular dependencies:

```python
if TYPE_CHECKING:
    from rdflib import Graph

def foo(graph: "Graph") -> None:
    pass
```

**Comment by ajnelson-nist** [comment]
Thanks for the `TYPE_CHECKING` hint!  That alleviated the circular import issue.  I see this isn't the first time that variable has been used, so I'm fine withdrawing my concern about rearchitecting for circular dependencies.

My question on `Path` has grown a bit, after combing through `Graph.triples()`'s body and finding that `Path`s can be output in the predicate position.
* Within `graph.py`, how pervasive should `Path` be in the accepted and emitted types from generators?
* Within `Store`, there is a `triples` method.  Nothing under the `.../store` code tree references the `Path` class (at least according to grepping for "Path").  Should the type signature of `Store.triples` include `Path` in its inputs or outputs, or should that be restricted to just `IdentifiedNode` in the predicate position?

**Comment by aucampia** [comment]
> If the maintainers are interested in the signature on `Graph.triples()` being refined to enable some safety around `Literal` placement, what would be the next steps, broadly speaking?

I think it would be best that the type signatures match RDF 1.1 as closely as possible, so it should enforce this:

https://www.w3.org/TR/rdf11-concepts/#section-triples

> An RDF triple consists of three components:
> 
> - the subject, which is an [IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-iri) or a [blank node](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node)
> - the predicate, which is an [IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-iri)
> - the object, which is an [IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-iri), a [literal](https://www.w3.org/TR/rdf11-concepts/#dfn-literal) or a [blank node](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node)

And this:

https://www.w3.org/TR/rdf11-concepts/#section-dataset

> An RDF dataset is a collection of [RDF graphs](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-graph), and comprises:
> 
> - Exactly one default graph, being an [RDF graph](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-graph). The default graph does not have a name and may be empty.
> - Zero or more named graphs. Each named graph is a pair consisting of an [IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-iri) or a blank node (the graph name), and an [RDF graph](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-graph). Graph names are unique within an RDF dataset.

The actual code should not do excessive runtime validation though IMO, but I am not entirely opposed to more of that either, it is just that runtime validation has performance costs and does not add that much over what can be achieved with static type checking.

The general approach to getting there is to just add more types, as narrow as possible, but not more narrow than we are sure is valid. Ideally we should add typing in small chunks so it is easy to review, and we should try and make the type annotation PRs as purely related to type annotations as possible. Often bugs become apparent in the process of adding types but it would be best to fix those bugs in separate PRs with tests specifically for them.

CC: @eggplants

**Comment by aucampia** [comment]
> * Within `graph.py`, how pervasive should `Path` be in the accepted and emitted types from generators?

Difficult question to answer definitively, but in your PR the problem's that Path causes can be mitigated by using overloads, as Path will only be returned if it is passed in, so you can make a type signature for triples that does not include Path. I will make a PR to your PR to add this.

> * Within `Store`, there is a `triples` method.  Nothing under the `.../store` code tree references the `Path` class (at least according to grepping for "Path").  Should the type signature of `Store.triples` include `Path` in its inputs or outputs, or should that be restricted to just `IdentifiedNode` in the predicate position?

To begin with I would not accept Path in Store's methods, I don't think it should be accepted, and also from what I can tell from [`pytest-annotate`](https://github.com/kensho-technologies/pytest-annotate) Path is not a parameter or return value of store's triples method.

**Comment by aucampia** [comment]
And more type annotations are coming, I have a branch where I'm adding a bunch of it ([link](https://github.com/RDFLib/rdflib/compare/master...aucampia:iwana-20220126T2212-typing)) and plan to break parts of it off into PRs, but any help is welcome, and the smaller the PRs adding type annotations the better. It will just take some time.
