### ISSUE TITLE
Support for owl:imports?

### ISSUE THREAD

**Issue by gtfierro** [RDFLib/rdflib#1698]
Is there any interest in supporting `owl:imports` in the RDFlib ecosystem? I've been using it more and more recently, and there is direct support for it in other tools that goes beyond a simple URL resolution. When doing ontology development, it is helpful to be able to refer to local definitions of graphs rather than having to keep your in-development graph online somewhere.

I've been working on-and-off on a solution I call `ontoenv`: https://github.com/gtfierro/ontoenv. It is a command-line utility and Python library. You setup the "universe" using `ontoenv init` in a project directory -- this downloads and builds an index referring to online or local ontologies. You can then resolve the dependencies for a graph in Python as follows:

```python
import rdflib
import ontoenv

# initialize environment
env = ontoenv.OntoEnv()

g = rdflib.Graph()
g.parse("my_graph.ttl", format="ttl")
env.import_dependencies(g)
```

I thought this might be of interest to the RDFlib community. I'd be happy to contribute the code to RDFlib --- with feedback/guidance from the community --- or maintain as a separate tool. Whatever is the most useful! I'm open to all suggestions

(of course, it may be that there's already a way of doing this in RDFlib --- if so, can you point me to it?)

**Comment by ashleysommer** [comment]
Hi @gtfierro 
I believe the resolution of `owl:imports` belongs at the application level, not at the library level.
For example, I support `owl:imports` in PySHACL. PySHACL is built upon RDFLib, but I'm happy to keep the logic for `owl:imports` in PySHACL, ie, at the application level. That allows me to better control the behaviour of the feature, I can use whichever HTTP request library I fancy, I can set how many levels of imports I do, eg, "A imports B, B imports C, C imports D, and D is not allowed to do imports". I can also implement my own logic around recursive imports and relative imports. These are all behaviours you may want to be different in different applications.

As you said, you've already written your own utility to do this for your own use case, and I think that is the best solution.

**Comment by gtfierro** [comment]
I completely missed that `owl:imports` is implemented in PySHACL! I should have read the docs closer.

I think the rationale makes sense, too. Keeping the logic separate is a good design. I'll continue with `ontoenv` as a separate project
