### ISSUE TITLE
JSON-LD `@graph` section is silently ignored on import

### ISSUE THREAD

**Issue by anatoly-scherbakov** [RDFLib/rdflib#1699]
JSON-LD `@graph` section can be used to specify contents of a particular named graph identified by `@id`. When importing a document with such section into `Graph`, which is not context-aware, the contents of `@graph` section is lost. This is demonstrated by the following test failing under `rdflib==6.0.1`.

```python
import json

from rdflib import Graph, URIRef


def test_jsonld_with_graph():
    """Try to parse a JSON-LD document with a @graph entry in it."""
    document = [
        {
            '@id': 'https://spdx.org/licenses/',
            '@graph': [
                {
                    '@id': 'https://spdx.org/licenses/GPL-3.0-only',
                    '@type': 'https://spdx.org/licenses/ListedLicense',
                },
            ],
        },
    ]

    graph = Graph()
    graph.parse(
        data=json.dumps(document),
        format='json-ld',
    )

    assert (
        URIRef('https://spdx.org/licenses/GPL-3.0-only'),
        URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
        URIRef('https://spdx.org/licenses/ListedLicense'),
    ) in graph
```

If to replace `Graph()` with `ConjunctiveGraph()` in this test, it passes.

It can be argued that the behavior is logical, as plain `Graph()` cannot contain named graphs, — but perhaps an exception message would be helpful here? Just to let the user know what is going on, and what can be done. Otherwise, it might be hard to debug the problem. Maybe it is already discussed in the docs but I did not find it?

**Comment by gjhiggins** [comment]
> JSON-LD `@graph` section can be used to specify contents of a particular named graph identified by `@id`. When importing a document with such section into `Graph`, which is not context-aware, the contents of `@graph` section is lost.

Not "lost", just not accessible using `Graph` methods. One weird trick with RDFLib is to understand that the `Graph`,  `ConjunctiveGraph` and `Dataset` objects provide an API to work with the underlying quad stores. In your example, the contents have been successfully parsed into the `Memory` quad store and preserved ... they're just not _accessible_ by context-unaware `Graph` objects. Let's keep your example mostly as is except that we'll directly access the backing quad store and then the assertion is True:

```python
def test_jsonld_with_graph():
...
    graph.parse(data=json.dumps(document), format='json-ld')
    triplesinstore = [(s, p, o) for (s, p, o), ctxgen in graph.store.triples((None, None, None))]
    assert (
        URIRef('https://spdx.org/licenses/GPL-3.0-only'),
        URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
        URIRef('https://spdx.org/licenses/ListedLicense'),
    ) in triplesinstore
```
Another means of accessing the contents is (again via that weird trick) to bind an instance of a context-aware Dataset to the store ...
```py
ds = Dataset(store=graph.store)  # NB re-using the Graph's store as the Dataset's store
assert len(list(ds.contexts())) == 1
assert list(ds.contexts()) == [URIRef('https://spdx.org/licenses/')]
assert len(ds.graph(URIRef("https://spdx.org/licenses/"))) == 1
g = ds.graph(URIRef("https://spdx.org/licenses/"))
assert (
    URIRef('https://spdx.org/licenses/GPL-3.0-only'),
    URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
    URIRef('https://spdx.org/licenses/ListedLicense'),
) in g
```
HTH

**Comment by anatoly-scherbakov** [comment]
@gjhiggins thank you! So if I understand you correctly then `Graph` is a small window into the store, it only exposes quads which are associated with the graph's `identifier`. A `ConjunctiveGraph` or a `Dataset` (thanks for pointing out the latter, I did not know it existed) provide full access to the quads.

I have submitted a PR, suggesting to mention this in `Graph` class docstring.

**Comment by gjhiggins** [comment]
> ... `Dataset` (thanks for pointing out the latter, I did not know it existed)

As a general observation, Dataset is more attuned to working with quads than is ConjunctiveGraph.

For example, the iterators differ significantly:
#### `Dataset`
has its own [class-specific implementation](https://github.com/RDFLib/rdflib/blob/6ed2ef48ed38679bcdafe7cae250a2ef4b315e7b/rdflib/graph.py#L2076) which returns an iterator over quads:
```py
    def __iter__(self) -> Generator[DatasetQuad, None, None]:
        """Iterates over all quads in the store"""
        return self.quads((None, None, None, None))
```
#### `ConjunctiveGraph`
[inherits its iterator](https://github.com/RDFLib/rdflib/blob/6ed2ef48ed38679bcdafe7cae250a2ef4b315e7b/rdflib/graph.py#L549) from `Graph` and returns an iterator over triples:
```py
    def __iter__(self):
        """Iterates over all triples in the store"""
        return self.triples((None, None, None))
```
