### ISSUE TITLE
readthedocs.org previews and master branch builds

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1777]
I would like to configure readthedocs.org builds for master branch and for [PRs](https://docs.readthedocs.io/en/stable/pull-requests.html) so we can get an up to date preview of the docs and do better quality control on changes, but I don't have access to the [rdflib project on readthedocs.org](https://readthedocs.org/projects/rdflib/) - can someone please add me so I can configure these things?

My username on readthedocs.org is [`iwan.aucamp`](https://readthedocs.org/profiles/iwan.aucamp/) 

NOTE: added the current maintainers of the rdflib readthedocs project as assignees.

**Comment by gjhiggins** [comment]
> I would like to configure readthedocs.org builds for master branch ... can someone please add me so I can configure these things?

Added.

**Comment by aucampia** [comment]
thank you @gjhiggins
