### ISSUE TITLE
Typo "http://rdlib.net/"

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/rdflib#1824]
`http://rdlib.net/`, is this a typo? I think it's supposed to be `rdflib` instead of `rdlib` but I'm not sure.

I don't think it's a big deal but thought I'd create an issue for it.

There are two occurrences in the codebase.

https://github.com/RDFLib/rdflib/blob/b5703b94b0b101f895e0e9bcbd45fb63716ac72c/rdflib/term.py#L464

https://github.com/RDFLib/rdflib/blob/b5703b94b0b101f895e0e9bcbd45fb63716ac72c/rdflib/graph.py#L1988

**Comment by gjhiggins** [comment]
> `http://rdlib.net/`, is this a typo? I think it's supposed to be `rdflib` instead of `rdlib` but I'm not sure.

You are absolutely correct in identifying it as a typo, indeed it should be `http://rdflib.net/` (see [archive.org](https://web.archive.org/web/20020805130824/http://rdflib.net/) for history)

**Comment by aucampia** [comment]
- Fixed in https://github.com/RDFLib/rdflib/pull/1901
