### ISSUE TITLE
Error in using rdfalchemy and rdflib

### ISSUE THREAD

**Issue by ghost** [RDFLib/rdflib#183]
imrantau...@gmail.com, 2011-10-22T01:34:29.000Z

<pre>
<b>What steps will reproduce the problem?</b>
1.Installed rdfalchemy, rdflib
2.Imported rdfalchemy and rdflib in my code and when run the code, it gives me following error
3.Traceback (most recent call last):
  File "C:\Python27\sesame.py", line 40, in <module>
    import rdfalchemy
  File "build\bdist.win32\egg\rdfalchemy\__init__.py", line 2, in <module>
    from rdfalchemy.Literal import Literal
  File "build\bdist.win32\egg\rdfalchemy\Literal.py", line 10, in <module>
    from rdflib.Literal import bind as bindLiteral
ImportError: No module named Literal
<b>What is the expected output? What do you see instead?</b>
Code should run properly

<b>What version of the product are you using? On what operating system?</b>
python 2.7

<b>Please provide any additional information below.</b>
Could you please help..
Thanks in advance

Comment 1 by gjhigg...@gmail.com
This is not an issue with rdflib. It's either a broken installation of rdflib or an attempt to use an incorrect version of rdflib with rdfalchemy, the latter being more likely. Installation of the released version of rdfalchemy requires rdflib 2.4.0. installation of the development version of rdfalchemy requires rdflib 2.4.0=> <=2.4.9.
</pre>

**Comment by charbull** [comment]
Hello,
I am still having this error:
I installed with pip: >pip install http://www.openvest.com/public/downloads/RDFAlchemy-0.2.9.tar.gz
with Python 3.6.

Any suggestions?
thanks
