### ISSUE TITLE
N3 Formula <-> SQLAlchemy Store error

### ISSUE THREAD

**Issue by MartyStache** [RDFLib/rdflib#1876]
Greetings!

I have a need to store formulas in Conjunctive Graphs [as depicted in tests here](https://github.com/RDFLib/rdflib/blob/6f2c11cd2c549d6410f9a1c948ab3a8dbf77ca00/test/test_graph/test_graph_formula.py) in a SQLAlchemy backed store using Postgres.

I can run the tests just fine, but when I switch over the store using the code below, I receive the error in the image below.

`registerplugins() `
`store = plugin.get("SQLAlchemy", Store)(identifier="")`
`cg = ConjunctiveGraph(store=store)`
`cg.open(my_verified_sql_alchemy_connection_string, create=True)`
`testN3 = """`
`@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .`
`@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .`
`@prefix : <http://test/> .`
`{:a :b :c;a :foo} => {:a :d :c,?y}.`
`_:foo a rdfs:Class.`
`:a :d :c."""`
`cg.parse(data=testN3, format='n3')`

Any help on what I might be doing wrong? I am aware that my store needs to be a 'formula aware' store. Is there something I am not setting (or setting incorrectly?)

<img width="748" alt="image" src="https://user-images.githubusercontent.com/62360524/166151904-581b2a1d-65ab-48af-ab73-143a03825078.png">

**Comment by gjhiggins** [comment]
This is not an issue with RDFLib but with the ancillary rdflib-sqlalchemy package. If you would like to raise it on the [rdflib-sqlalchemy issues list](https://github.com/RDFLib/rdflib-sqlalchemy/issues), I can provide a fix.

**Comment by MartyStache** [comment]
Thanks! Passing issue on to rdflib SQLAlchemy folks and will get back to
you on it if any action is required on your part!
