### ISSUE TITLE
The same code using serialize() results in different types for different platforms/OS'es

### ISSUE THREAD

**Issue by wmelder** [RDFLib/rdflib#1905]
Maybe this is a bug in rdflib. 

I was trying to write n-triples data to a file. On my Windows 10 dev machine it works and results in a text file with required content. When deploying the code on RHEL7 I got a TypeError. It turned out that serialize() returns a str on Windows and bytes on Linux.

To fix it I introduced a try..catch... Here's a compact representation of the code:
```python
with open(data_fn, 'a', encoding="utf-8") as f:
    data = g.serialize(format='nt')
    try:
        f.write(data)
    except TypeError:
        # On Windows the type of data is 'str'. On Linux 'bytes'.
        f.write(data.decode(encoding="utf-8"))
```

 It might have to do with the locales, but I didn't get to the bottom of that. I think this is the (overloaded) version of serialize() function that should be triggered (and that should always  result in a string):
```python
serialize(destination: None = None, format: str = 'turtle', base: Optional[str] = None, encoding: None = None, **args) → str
```
I am working on Python 3.8, by the way.

**Comment by gjhiggins** [comment]
Hmm. Sorry I don't have much to offer in the way of help because I can't reproduce the issue - I'm on Linux Mint 20.3 Una using  RDFLib 6.1.1:
```pycon
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdflib import Graph, URIRef
>>> data_fn = "/tmp/foo"
>>> g = Graph()
>>> g.add((URIRef("urn:example:tarek"), URIRef("urn:example:likes"), URIRef("urn:example:pizza")))
<Graph identifier=Na43393f717d4461f935d065cd7922f1a (<class 'rdflib.graph.Graph'>)>
>>> with open(data_fn, 'a', encoding="utf-8") as f:
...     data = g.serialize(format='nt')
...     assert isinstance(data, str)
...     f.write(data)
... 
63
>>> 
```

**Comment by wmelder** [comment]
It turns out that the version on the RHEL7 server was still on:
>rdflib             5.0.0

which I replaced with;
>pip install rdflib==6.1.1

Guess what? I can't reproduce the error. It is gone!

Thanks for the help and sorry for being so ignorant to not have checked the rdflib version. I was assuming 6.1.1, but that wasn't true.
