### ISSUE TITLE
Include Concise Bounded Description example in the tests for `Graph.cbd`

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1914]
From a brief glance at `Graph.cbd` I'm unsure if it will be able to reproduce [the example from the Concise Bounded Description](https://www.w3.org/Submission/CBD/#example) definition, but regardless this example should be included in our tests so we can be sure it passes.

**Comment by ms1901** [comment]
Hello @aucampia,
I am working on solving this.

**Comment by gjhiggins** [comment]
> From a brief glance at `Graph.cbd` I'm unsure if it will be able to reproduce [the example from the Concise Bounded Description](https://www.w3.org/Submission/CBD/#example) definition, but regardless this example should be included in our tests so we can be sure it passes.

Yes `Graph.cbd()` does reproduce the example (I've elided the actual RDF/XML `inputgraph` and `expectedgraph` data) as far as `isomorphic` is concerned ...

```py
def testcbd_example():

    g = Graph()
    g.parse(data=inputgraph, format="xml")

    result = g.cbd(URIRef("http://example.com/aReallyGreatBook"))
    expected = Graph().parse(data=expectedgraph, format="xml")

    assert isomorphic(result, expected)
```
And I can confirm a slightly stronger test result via using my implementation of the DigitalBazaar `URDNA` canonicalizer:

```py
    canonicalized_expected = expected.serialize(format="rdna")
    canonicalized_result = result.serialize(format="rdna")

    assert canonicalized_expected == canonicalized_result
```
So `Grapg.cbd()` seems to be working as one would expect.
