### ISSUE TITLE
Consider renaming `Literal.ill_formed` to `Literal.ill_typed`

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1960]
From https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal

> The literal value associated with a [literal](https://www.w3.org/TR/rdf11-concepts/#dfn-literal) is:
> 
> 1. If the literal is a [language-tagged string](https://www.w3.org/TR/rdf11-concepts/#dfn-language-tagged-string), then the literal value is a pair consisting of its [lexical form](https://www.w3.org/TR/rdf11-concepts/#dfn-lexical-form) and its [language tag](https://www.w3.org/TR/rdf11-concepts/#dfn-language-tag), in that order.
> 2. If the literal's [datatype IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-datatype-iri) is in the set of [recognized datatype IRIs](https://www.w3.org/TR/rdf11-concepts/#dfn-recognized-datatype-iris), let d be the [referent](https://www.w3.org/TR/rdf11-concepts/#dfn-referent) of the datatype IRI.
>     - (a) If the literal's [lexical form](https://www.w3.org/TR/rdf11-concepts/#dfn-lexical-form) is in the [lexical space](https://www.w3.org/TR/rdf11-concepts/#dfn-lexical-space) of d, then the literal value is the result of applying the [lexical-to-value mapping](https://www.w3.org/TR/rdf11-concepts/#dfn-lexical-to-value-mapping) of d to the [lexical form](https://www.w3.org/TR/rdf11-concepts/#dfn-lexical-form).
>     - (b) Otherwise, the literal is ill-typed and no literal value can be associated with the literal. Such a case produces a semantic inconsistency but is not syntactically ill-formed. Implementations must accept ill-typed literals and produce RDF graphs from them. Implementations may produce warnings when encountering ill-typed literals.
> 3. If the literal's [datatype IRI](https://www.w3.org/TR/rdf11-concepts/#dfn-datatype-iri) is not in the set of [recognized datatype IRIs](https://www.w3.org/TR/rdf11-concepts/#dfn-recognized-datatype-iris), then the literal value is not defined by this specification.

Given that `Literal.ill_formed` is for 2b - I think it may be slightly more clear if it was `Literal.ill_typed` instead of `Literal.ill_formed`

https://github.com/RDFLib/rdflib/blob/ba855c233310afee65abd67f2f77239f909cd895/rdflib/term.py#L698-L709

**Comment by aucampia** [comment]
CC: @ashleysommer

**Comment by ashleysommer** [comment]
Yes, I'm happy with changing the name to ill-typed.

When I wrote this code, I was basing the naming off some language I remebered reading the [SHACL spec](https://www.w3.org/TR/shacl/#dfn-ill-formed).
But after re-reading that, I see that the term "ill-typed" is also used, when referring specifically to literals in the context we are using it.

I see my original PR (https://github.com/RDFLib/rdflib/pull/1773) even uses the term "ill-typed" in the title, but the code uses "ill-formed", perhaps I confused myself, used the wrong language in one place, and just continued with it though the code.

**Comment by ajnelson-nist** [comment]
Whoops, looks like everyone said "Yes we should" and forgot to check for a raised hand to implement this.  I've filed [PR 2003](https://github.com/RDFLib/rdflib/pull/2003) to handle this rename before whatever the next pending release is.

**Comment by aucampia** [comment]
- Fixed in https://github.com/RDFLib/rdflib/pull/2003

Thanks again @ajnelson-nist
