### ISSUE TITLE
I get errors when parsing RDF*

### ISSUE THREAD

**Issue by markstuttword** [RDFLib/rdflib#1990]
Can RDFLib not parse RDF*? To be more precise, I'm trying to parse some Turtle files with "<< >>" and "{| |}" but these won't parse.

**Comment by gjhiggins** [comment]
Not at the moment. An implementation of RDF* parsers for RDFLib is currently [work-in-progress](https://github.com/RDFLib/rdflib-rdfstar)

**Comment by gjhiggins** [comment]
Offhand, I woudln't know, sorry. It's a question better asked on StackOverflow with the [rdflib] tag.

**Comment by markstuttword** [comment]
Just out of curiosity, does RDFLib not work with RDF* at all or can it at least work with some of the simpler formats such as nt?

**Comment by aucampia** [comment]
> Just out of curiosity, does RDFLib not work with RDF* at all or can it at least work with some of the simpler formats such as nt?

This is not a straight forward a question as it seems, but in brief, iwon't work with RDF* at all. You can convert RDF* to RDF and then it will work.

In more complicated sense, I think the official view of RDF* is that is is a new abstract syntax, distinct from RDF, with various concrete syntaxes, one of which is Turtle*, and another is N-Triples*. We have no specific support for either the concrete or abstract syntaxes of RDF*.

One can however take RDF* and ([incorrectly](https://www.w3.org/2021/12/rdf-star.html#common-misconceptions)) interpret it as syntactic sugar for [standard reification](https://www.w3.org/TR/rdf11-mt/#reification) - and then under this interpretation convert it to RDF and process it with RDFLib. There are also maybe slightly less incorrect versions of this that is possible.

**Comment by nicholascar** [comment]
RDF-star support is being trialled, see https://github.com/RDFLib/rdflib-rdfstar/. So far this is only Turtle-star support but we are getting there...

**Comment by aucampia** [comment]
I will close this issue as RDFLib currently does not support RDF*, support will be added at a later point in time.
