### ISSUE TITLE
XML parsing ignores some node values

### ISSUE THREAD

**Issue by alexgao1** [RDFLib/rdflib#2043]
I am using rdflib 6.1.1.
  
Given the sample
```xml
<gml:MultiPolygon xmlns:gml="opengis.net/ont/gml#">
    <gml:polygonMember>
        <gml:Polygon>
            <gml:outerBoundaryIs>
                <gml:LinearRing>
                    <gml:coordinates>322508.3974999999,183565.0044 322506.8969,183552.0980999999 322509.7991,183506.8011 322527.1961999999,183509.9001999999 322542.4001,183503.7018999999 322553.0031999999,183496.8038999999 322573.3025999999,183471.3011999999 322573.8962,183470.3015 322574.8032,183464.0033 322575.1989,183458.304899999, 322574.3991999999164542.6994999999</gml:coordinates>
                </gml:LinearRing>
            </gml:outerBoundaryIs>
        </gml:Polygon>
    </gml:polygonMember>
</gml:MultiPolygon>
```
rdflib will pick up the value of `gml:coordinates` when parsed (and written out to file).  
```
@prefix ns1: <file:///home/user/opengis.net/ont/gml#> .

[] a ns1:MultiPolygon ;
    ns1:polygonMember [ a ns1:Polygon ;
            ns1:outerBoundaryIs [ a ns1:LinearRing ;
                    ns1:coordinates "322508.3974999999,183565.0044 322506.8969,183552.0980999999 322509.7991,183506.8011 322527.1961999999,183509.9001999999 322542.4001,183503.7018999999 322553.0031999999,183496.8038999999 322573.3025999999,183471.3011999999 322573.8962,183470.3015 322574.8032,183464.0033 322575.1989,183458.304899999, 322574.3991999999164542.6994999999" ] ] .
```
  
Given a different XML excerpt
```xml
<gmd:MD_Metadata xmlns:gco="http://www.isotc211.org/2005/gco#"
                 xmlns:gmd="http://www.isotc211.org/2005/gmd#"
                 >
	<gmd:fileIdentifier>
		<gco:CharacterString>geo.xml</gco:CharacterString>
	</gmd:fileIdentifier>
</gmd:MD_Metadata>
```
rdflib drops the node value in `gco:CharacterString`.  
```
@prefix gco: <http://www.isotc211.org/2005/gco#> .
@prefix gmd: <http://www.isotc211.org/2005/gmd#> .

[] a gmd:MD_Metadata ;
    gmd:fileIdentifier [ a gco:CharacterString ] .
```
  
Is this an issue with the multiple namespaces?
  
Sample code if needed:
```python
import rdflib

g = rdflib.Graph()
g.parse("myfile.xml", format="xml")
g.serialize("myresults", format="ttl")
```

**Comment by gjhiggins** [comment]
> I am not very familiar with the rules for the XML document; what can be fixed about the provided excerpt such that the values won't be dropped? What was stated implies that rdflib can drop the values, it is only erroneous in this case because it is silently doing so.

Ah-ha, now that I actually _look_ at the example, it's not RDF/XML, it's “just” XML. The `format='xml'` is shorthand for "rdf/xml" and signals that the [RDFXML parser](https://github.com/RDFLib/rdflib/blob/14bb3862f4aa2726546cf36bebf79dd0d63e7556/rdflib/plugin.py#L374) is to be used, so you'll need to feed it valid RDF/XML - see the W3's RDF/XML [example describing "striping"](https://www.w3.org/TR/rdf-syntax-grammar/#example1) to see what you'd need to do.

The example is valid XML but not meaningful RDF/XML and the RDF/XML parser can't know what it's _supposed_ to parse as, it just follows the rules for RDF/XML.

**Comment by alexgao1** [comment]
I see, thanks for the clarification.
