### ISSUE TITLE
function call fails as there is a reference to args.target_namespace which I believe shoud be target_namespace

### ISSUE THREAD

**Issue by konstantin-mergenthaler** [RDFLib/rdflib#2072]
https://github.com/RDFLib/rdflib/blob/cfa418074b27b12aac905ba266b002a237c5ff4c/rdflib/tools/defined_namespace_creator.py#L98

**Comment by aucampia** [comment]
Thanks for the bug report @konstantin-mergenthaler, this should be fixed in the next release in mid october.
