### ISSUE TITLE
html5lib is not specified as a dependency in pyproject.toml

### ISSUE THREAD

**Issue by mdw00d** [RDFLib/rdflib#2099]
The html5lib library is required under certain execution paths but is not included as a dependency in pyproject.toml.

  https://github.com/RDFLib/rdflib/blob/d11a5eff3d1ca99fa6d63d432e2a53f48a3394a4/rdflib/term.py#L1648

This can lead to unexpected runtime errors.

**Comment by aucampia** [comment]
I think this may be more a failure of documentation, we consider html5lib as an optional dependency and it is installed when you use install with `html` extras i.e. `pip install "rdflib[html]"`.
