### ISSUE TITLE
Regression in 6.2.0 when URL source to be parsed contains a query string

### ISSUE THREAD

**Issue by nutjob4life** [RDFLib/rdflib#2120]
`Graph.parse` in 6.2.0 is producing inconsistent statement counts when reading over HTTP versus 6.1.1 when the source URL contains a query string.

To reproduce:
```console
$ date -u
Wed Sep 21 16:57:54 UTC 2022
$ cd /tmp
$ python3.10 --version
Python 3.10.5
$ python3.10 -m venv venv
$ cd venv
$ bin/pip install --quiet --upgrade setuptools pip wheel rdflib==6.2.0
$ bin/python
Python 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdflib
>>> a, b = rdflib.Graph(), rdflib.Graph()
>>> a.parse('https://bmdb.jpl.nasa.gov/rdf/example')
>>> b.parse('https://bmdb.jpl.nasa.gov/rdf/example?all=right')
>>> len(a), len(b), len(a) != len(b)
(2, 2, False)
```
This should be `(2, 4, True)`.

Using 6.1.1 produces the correct results:
```console
$ bin/pip install --quiet rdflib==6.1.1
$ bin/python
Python 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdflib
>>> a, b = rdflib.Graph(), rdflib.Graph()
>>> a.parse('https://bmdb.jpl.nasa.gov/rdf/example')
>>> b.parse('https://bmdb.jpl.nasa.gov/rdf/example?all=right')
>>> len(a), len(b), len(a) != len(b)
(2, 4, True)
```

Apparently in 6.2.2 the query string part of the URL `?all=right` gets stripped out. It is necessary with certain web services APIs in order to select different sets of RDF statements.

**Comment by aucampia** [comment]
Regression came in with <https://github.com/RDFLib/rdflib/pull/1902>, the problem is that we are using quote(), which is designed for quoting paths, for non-path elements.

The exact fix is not that simple, but not that complex either,  should have this fixed for 6.3.2

**Comment by aucampia** [comment]
Okay, this is not that complex to fix: werkzeug has a valid implementation of this [[ref](https://github.com/pallets/werkzeug/blob/92c6380248c7272ee668e1f8bbd80447027ccce2/src/werkzeug/urls.py#L926-L931)] and I will try to align our implementation of `iri2uri` with theirs.

**Comment by nutjob4life** [comment]
Wow! That pull-request was a lot more involved than I expected.

Thank you for tackling this, @aucampia! 💃🕺
