### ISSUE TITLE
Set the `RDFLib/rdflib/pkgs/container/rdflib` package to be public

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#2122]
Currently the docker image for RDFLib is set to private, can someone set it to public please.

The visibility needs to be changed [here](https://github.com/orgs/RDFLib/packages/container/rdflib/settings)

![image](https://user-images.githubusercontent.com/4481387/191823296-ae63ee0d-da0f-4e19-8f5f-fd3fd1927191.png)

More info [here](https://github.com/RDFLib/rdflib/pull/2116#issuecomment-1255394134).

**Comment by gjhiggins** [comment]
Wouldn't work for me either until I changed the RDFLib org settings for [Packages](https://github.com/organizations/RDFLib/settings/packages)

**Comment by aucampia** [comment]
Closing this as it has now been set to public.
