### ISSUE TITLE
Too many calls to backend store for NamespaceManager.compute_qname()

### ISSUE THREAD

**Issue by zuotian** [RDFLib/rdflib#213]
While debugging some other issues, I noticed this piece of code in NamespaceManager,py

```
def compute_qname(self, uri, generate=True):
    if not uri in self.__cache:
        namespace, name = split_uri(uri)
        namespace = URIRef(namespace)
        prefix = self.store.prefix(namespace)
        ....
        self.__cache[uri] = (prefix, namespace, name)
  return self.__cache[uri]
```

Note that each self.store.prefix() call is a sql hit.

I have a triple store with 350k urls that only differ after #, this caching mechanism will seriously slow down the serialization.

I suggest to either cache prefixes in the store or have a better caching mechanism for NamespaceManager.

**Comment by gjhiggins** [comment]
Superseded  by #649
