### ISSUE TITLE
Unrecognised ISO 8601 for BC years

### ISSUE THREAD

**Issue by GreenfishK** [RDFLib/rdflib#2148]
Following triple cannot be parsed

```
from rdflib import Graph
g = Graph()
g.parse(data='<http://dbpedia.org/resource/Cologne> <http://dbpedia.org/ontology/foundingYear> "-0038"^^<http://www.w3.org/2001/XMLSchema#gYear> .')
```

Error message
```
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#gYear, Converter=<function parse_date at 0x7f84578fd040>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/opt/anaconda3/lib/python3.8/site-packages/isodate/isodates.py", line 203, in parse_date
    raise ISO8601Error('Unrecognised ISO 8601 date format: %r' % datestring)
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: '-0038'
<Graph identifier=N8a4fd05511ab4ad59496949f369abbee (<class 'rdflib.graph.Graph'>)>
```

According to ISO 8601 BC dates should be written with a minus, e.g. "-0038". So the input should be correct

**Comment by gjhiggins** [comment]
The Exception message identifies the isodate library as the cause:
> isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: '-0038'

There has been [some discussion of helping with / taking over maintenance of isodate](https://github.com/gweis/isodate/issues/73) but there is also an alternative, [metomi.isodatetime](https://github.com/metomi/isodatetime) published and maintained by the UK Meteorological Office:

```python
>>> tp = "-0038"
>>> import metomi.isodatetime.parsers as parse
>>> parse.TimePointParser().parse(tp)
<metomi.isodatetime.data.TimePoint: -003800-01-01T00:00:00Z>
```

**Comment by GreenfishK** [comment]
I see, thank you! 
Is there any alternative for the rdflib parser? Because how can I eventually parse a whole graph without getting this issue? Is there a setting/parameter for rdflib's to configure this or do I really need to change the modules locally?

**Comment by gjhiggins** [comment]
The in-code documentation for isodate acknowledges a [lack of support for dates before "0000-01-01"](https://github.com/gweis/isodate/blob/8856fdf0e46c7bca00229faa1aae6b7e8ad6e76c/src/isodate/isodates.py#L6)

> The only limitations it has, are given by the Python datetime.date implementation, which does not support dates before 0001-01-01.

At present, Literal values are implemented as Python datatypes ...
```python
>>> Literal("0001", datatype=XSD.gYear)
Literal('0001', datatype=URIRef('http://www.w3.org/2001/XMLSchema#gYear'))
>>> Literal("0001", datatype=XSD.gYear).value
datetime.date(1, 1, 1)
```
So, given that the basic limitation is Python itself and because integrating/switching to metomi.isodatetime would entail a fundamental change to the way Literal values are handled, it would likely be considered out of scope. After more detailed investigation, it would seem my mentioning it was ill-conceived.

All I can suggest is that if you want to work with this dataset in RDFLib/Python, you pre-filter the statements, remapping any offending negative `XSD.gYear` instances to `XSD.integer`.

**Comment by GreenfishK** [comment]
Ok I see, thank you! Then this issue has nothing to do with rdflib and can be closed

**Comment by niklasl** [comment]
Wouldn't you say that this still is issue with RDFLib, as it is not being conformant with ISO 8601? It is so through its choice of implementation, and `isodate` should be fixed (or RDFLib should switch underlying implementation). But that does not give RDFLib license to throw errors when parsing valid RDF containing correctly typed and formatted BCE dates.

**Comment by GreenfishK** [comment]
> Wouldn't you say that this still is issue with RDFLib, as it is not being conformant with ISO 8601? It is so through its choice of implementation, and `isodate` should be fixed (or RDFLib should switch underlying implementation). But that does not give RDFLib license to throw errors when parsing valid RDF containing correctly typed and formatted BCE dates.

I see your point and you are right. However, I think that I simply should raise this issue again on isodate's github page because I think that way it will be solved faster as date formats are probably not rdflib's priority.
