### ISSUE TITLE
URIRef strips forward slash from protocol

### ISSUE THREAD

**Issue by kwisatz** [RDFLib/rdflib#2158]
When constructing IRIs using `URIRef`, the resulting string is missing a forward slash in the protocol:

### Versions

- python 3.9.2 or python 3.7.3
- rdflib 6.2.0

### Minimal failing example

```python
from rdflib import URIRef
from rdflib.namespace import Namespace
from pprint import pprint

CRM = Namespace('http://www.cidoc-crm.org/cidoc-crm/')

pprint(CRM)
pprint(URIRef(CRM))
pprint(URIRef(base=CRM, value="foo"))
pprint(URIRef("foo", CRM))
```

### Result

```bash
kwisatz@bean:~$ python3 test.py 
Namespace('http://www.cidoc-crm.org/cidoc-crm/')
rdflib.term.URIRef('http://www.cidoc-crm.org/cidoc-crm/')
rdflib.term.URIRef('http:/www.cidoc-crm.org/cidoc-crm/foo')
rdflib.term.URIRef('http:/www.cidoc-crm.org/cidoc-crm/foo')
```

The problem occurs with all version of `rdflib` from 4.2.2 up until 6.2.0, so I don't think that the problem actually lies within `rdflib` here.

The use-case may be contrived though since the same can be achieved by using the following, functional code instead of manually calling `URIRef`:

```python
from rdflib.namespace import Namespace
from pprint import pprint

CRM = Namespace('http://www.cidoc-crm.org/cidoc-crm/')

pprint(URIRef(base=CRM, value="foo-bar"))
pprint(CRM['foo-bar'])
```

Giving

```bash
rdflib.term.URIRef('http:/www.cidoc-crm.org/cidoc-crm/foo-bar')
rdflib.term.URIRef('http://www.cidoc-crm.org/cidoc-crm/foo-bar')
```

**Comment by kwisatz** [comment]
OK, the problem is clearly with urllib3's urljoin:

```python
pprint(urljoin(CRM, "foo")) # prints 'http:/www.cidoc-crm.org/cidoc-crm/foo'
```

Closing this ticket.

**Comment by aucampia** [comment]
@kwisatz this seems to not be an issue with the latest python and RDFLib:

```console
$ pipx run --python python3.9 --spec rdflib==6.3.1 python /dev/stdin <<'EOF'
from rdflib import URIRef
from rdflib.namespace import Namespace
from pprint import pprint

CRM = Namespace('http://www.cidoc-crm.org/cidoc-crm/')

pprint(CRM)
pprint(URIRef(CRM))
pprint(URIRef(base=CRM, value="foo"))
pprint(URIRef("foo", CRM))

EOF
⚠️  python is already on your PATH and installed at /usr/bin/python. Downloading and running anyway.
Namespace('http://www.cidoc-crm.org/cidoc-crm/')
rdflib.term.URIRef('http://www.cidoc-crm.org/cidoc-crm/')
rdflib.term.URIRef('http://www.cidoc-crm.org/cidoc-crm/foo')
rdflib.term.URIRef('http://www.cidoc-crm.org/cidoc-crm/foo')
```

Can you confirm that you still get this problem?

Also, Python 3.9.2 and Python 3.7.3 was more than a year old when you made this, it would be best to try with newer versions if possible.

**Comment by kwisatz** [comment]
For me, this is still broken with the very same example:

```bash
kwisatz@thufir:~$ pipx run --python python3.9 --spec rdflib==6.3.1 python /dev/stdin << 'EOF'
from rdflib import URIRef
from rdflib.namespace import Namespace
from pprint import pprint

CRM = Namespace('http://www.cidoc-crm.org/cidoc-crm/')

pprint(CRM)
pprint(URIRef(CRM))
pprint(URIRef(base=CRM, value="foo"))
pprint(URIRef("foo", CRM))

EOF
⚠️  python is already on your PATH and installed at /usr/bin/python. Downloading and running anyway.
Namespace('http://www.cidoc-crm.org/cidoc-crm/')
rdflib.term.URIRef('http://www.cidoc-crm.org/cidoc-crm/')
rdflib.term.URIRef('http:/www.cidoc-crm.org/cidoc-crm/foo')
rdflib.term.URIRef('http:/www.cidoc-crm.org/cidoc-crm/foo')
```

Given that the version of `rdflib` is the same, the difference must still be in the python version – since urllib3 comes bundled? As far as I understood, `pipx` runs python versions installed on the system, so lest I build a more recent version myself, I'm stuck with what is available on Debian 11.

> Also, Python 3.9.2 and Python 3.7.3 was more than a year old when you made this, it would be best to try with newer versions if possible.

And here I thought I was already bleeding edge for using python 3 instead of 2.7 on a Debian distro ;)

```
python3:
  Installed: 3.9.2-3
  Candidate: 3.9.2-3
  Version table:
     3.11.2-1 350
        350 http://deb.debian.org/debian testing/main amd64 Packages
 *** 3.9.2-3 990
        990 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by aucampia** [comment]
Thanks for the info, I will see if I can figure out what is up when I have time. That version of python (3.9.2) is more than 2 years old now, not sure why Debian is not upgrading it :thinking:. Python 3.11.2 is the latest python 3.11 though, have you tried with that?

**Comment by kwisatz** [comment]
Debian being Debian.

I haven't tried 3.11 yet, maybe I'll get a chance this coming week.

**Comment by aucampia** [comment]
Closing this as this is an issue in upstream that is fixed in the latest version. The right solution is to update Python.
