### ISSUE TITLE
numeric(boolean) not implemented

### ISSUE THREAD

**Issue by majidaldo** [RDFLib/rdflib#2159]
not sure if this is an issue or discussion, but why not cast boolean to numeric ?

https://github.com/RDFLib/rdflib/blob/be13b3af51b69c6eaf6c88d6811b0573af8edffb/rdflib/plugins/sparql/operators.py#L1050

**Comment by aucampia** [comment]
I think this is because from the SPARQL spec:

https://www.w3.org/TR/sparql11-query/#operandDataTypes

> The following types are derived from numeric types and are valid arguments to functions and operators taking numeric arguments:
> 
> - [xsd:nonPositiveInteger](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-nonPositiveInteger)
> - [xsd:negativeInteger](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-negativeInteger)
> - [xsd:long](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-long)
> - [xsd:int](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-int)
> - [xsd:short](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-short)
> - [xsd:byte](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-byte)
> - [xsd:nonNegativeInteger](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-nonNegativeInteger)
> - [xsd:unsignedLong](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-unsignedLong)
> - [xsd:unsignedInt](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-unsignedInt)
> - [xsd:unsignedShort](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-unsignedShort)
> - [xsd:unsignedByte](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-unsignedByte)
> - [xsd:positiveInteger](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-positiveInteger)

This does not include boolean, and the places where `numeric(...)` is used corresponds to functions taking numeric args.
