### ISSUE TITLE
Shipped namespace bindings missing/misspelled

### ISSUE THREAD

**Issue by dargueta** [RDFLib/rdflib#2196]
Version: 6.2.0

In `rdflib.namespace._NAMESPACE_PREFIXES_RDFLIB` there are two bugs:

1. The prefix for DCTERMS is misspelled as "cdterms".
2. The WGS namespace is missing.

**Comment by aucampia** [comment]
I believe the first point has been corrected already now:

- #2173 and https://github.com/RDFLib/rdflib/pull/2291

I will look into the second point, I presume this is a regression.

**Comment by aucampia** [comment]
Regarding "The WGS namespace is missing."

I don't think we ever released a version with the `wgs` namespace bound, so I don't think that is strictly a bug, but we did accept a PR adding it (<https://github.com/RDFLib/rdflib/pull/1710>) so we should probably have it there.
