### ISSUE TITLE
Provide an easy way to disable tests that use the internet

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#2293]
This is a request from Gentoo:

- https://github.com/RDFLib/rdflib/pull/2282#issuecomment-1475321347

> One thing that would really be helpful is having some marker on tests using Internet, so we could easily deselect them all.

Not sure what the best way is to implement this, but it would be useful.

**Comment by aucampia** [comment]
We should probably add a custom marker (<https://docs.pytest.org/en/7.1.x/example/markers.html>), that way someone can do:

```
pytest -v -m "not uses_internet"
```

**Comment by aucampia** [comment]
I guess the biggest question that remains is, what should we call the marker? The pytest docs use `webtest`, which I guess works, but not sure if that is best, I think `uses_internet` may be better, but if `webtest` is widely used then we should use that rather.

**Comment by aucampia** [comment]
I will go for webtest:
- https://github.com/search?q=%22%40pytest.mark.webtest%22&type=code

**Comment by niklasl** [comment]
Makes sense. In theory `uses_network` might be more proper, but in practise, RDFLib should probably only use http(s) for network access anyway.

**Comment by mgorny** [comment]
Thank you!

**Comment by aucampia** [comment]
> Thank you!

Hope it helps. If there are other things we can do to make it easier to work with our releases, please let me know.
