### ISSUE TITLE
ISO 8601 date format

### ISSUE THREAD

**Issue by yangzhang33** [RDFLib/rdflib#2426]
I'm loading the .nt file with BC dates

the triple is: <http://www.wikidata.org/entity/Q105530696> <http://www.wikidata.org/prop/direct/P571> "-0150-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

I have the error: raise ISO8601Error('Unrecognised ISO 8601 date format: %r' % datestring)
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: '-0150-01-01'

**Comment by gjhiggins** [comment]
Duplicate of https://github.com/RDFLib/rdflib/issues/2210
