### ISSUE TITLE
Sphinx does not generate documentation for module level variables

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#2488]
RDFLib has a docstring for [rdflib.NORMALIZE_LITERALS](https://github.com/RDFLib/rdflib/blob/1e5f56b58f0803f13a576f2dffe31382ebba9ff4/rdflib/__init__.py#L122), and we use autodoc which generates the following for the rdflib module:

```rst
Module contents
---------------

.. automodule:: rdflib
   :members:
   :undoc-members:
   :show-inheritance:
```

As far as I understand, the presence of `:members:` should result in some documentation for `rdflib.NORMALIZE_LITERALS`. However, there is no documentation being generated for it as far as I can tell. If it were generated, I would expect to see it [here](https://rdflib.readthedocs.io/en/latest/apidocs/rdflib.html).

**Comment by aucampia** [comment]
I asked about it at the sphinx-user's google group [here](https://groups.google.com/g/sphinx-users/c/1ykfSpMaKpo/m/NvoYCmfpAgAJ?utm_medium=email&utm_source=footer) but got no response.

**Comment by edmondchuc** [comment]
I think I've got it working previously by using the `#:` syntax. Does the following work?

```python
#: If True - Literals lexical forms are normalized when created.
#: I.e. the lexical forms is parsed according to data-type, then the
#: stored lexical form is the re-serialized value that was parsed.
#: 
#: Illegal values for a datatype are simply kept.  The normalized keyword
#: for Literal.__new__ can override this.
#: 
#: For example:
#: 
#: >>> from rdflib import Literal,XSD
#: >>> Literal("01", datatype=XSD.int)
#: rdflib.term.Literal("1", datatype=rdflib.term.URIRef("http://www.w3.org/2001/XMLSchema#integer"))
#: 
#: This flag may be changed at any time, but will only affect literals
#: created after that time, previously created literals will remain
#: (un)normalized.
NORMALIZE_LITERALS = True
```

From the sphinx docs https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoproperty:

> For module data members and class attributes, documentation can either be put into a comment with special formatting (using a #: to start the comment instead of just #), or in a docstring after the definition. Comments need to be either on a line of their own before the definition, or immediately after the assignment on the same line. **The latter form is restricted to one line only**.

Important to note when using a docstring, it needs to be in one line after the variable, which I see currently the docstring is over multiple lines, maybe that's why it's not working.

https://github.com/RDFLib/rdflib/blob/1e5f56b58f0803f13a576f2dffe31382ebba9ff4/rdflib/__init__.py#L122-L141

**Comment by WhiteGobo** [comment]
I have gotten it to work with adding `NORMALIZE_LITERALS` to `__all__`.
Also you get it to work, if you directly mention `NORMALIZE_LITERALS` in members

```
.. automodule: rdflib
    :members: NORMALIZE_LITERALS
```
But i guess we want it either way in the public api and adding it to `__all__` was exactly for this(i think. im not entirely sure :P )
