### ISSUE TITLE
`rdflib.paths.Path` should be abstract

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#2509]
https://github.com/RDFLib/rdflib/blob/7665ec8c0245592f07d442ace88a530ac8b2a81e/rdflib/paths.py#L216-L230

`rdflib.paths.Path` should be an abstract base class with two abstract methods:

- `eval(...)`
- `n3(...)`

**Comment by mielvds** [comment]
@aucampia added my two cents in #2516
