### ISSUE TITLE
Namespaces not declared in __all__

### ISSUE THREAD

**Issue by stuchalk** [RDFLib/rdflib#2598]
When I import the namespaces below I get the following errors in PyCharm.   How do I fix this?
The namespaces still work even though there is the error...

CODE:
```
from rdflib import Literal, URIRef
from rdflib.namespace import RDF, RDFS, XSD, SKOS, OWL, DCTERMS

```
ERRORS:
```
'RDF' is not declared in __all__
'RDFS' is not declared in __all__
'XSD' is not declared in __all__
'SKOS' is not declared in __all__
'OWL' is not declared in __all__
'DCTERMS' is not declared in __all__
```

**Comment by WhiteGobo** [comment]
I couldn't recreate this error/warning. Might be more an issue of pycharm. Afaik `__all__` should only be relevant when you use `from rdflib import *`.

Can you give the used version of rdflib?

**Comment by stuchalk** [comment]
I tried both v6.3.2 and v7.  I changed my code to import * and the errors go away so yep its a PyCharm thing.  Thanks!
