### ISSUE TITLE
csv2rdf cannot parse config file

### ISSUE THREAD

**Issue by Tchy258** [RDFLib/rdflib#2618]
When trying to pass a settings file as an argument to -f to csv2rdf.py like this:
`python csv2rdf.py -f <path to settings> <path to csv file>`
it raises an exception and displays the following
```
Traceback (most recent call last):
  File "D:\Watos\env\Lib\site-packages\rdflib\tools\csv2rdf.py", line 553, in <module>
    main()
  File "D:\Watos\env\Lib\site-packages\rdflib\tools\csv2rdf.py", line 468, in main
    config.readfp(open(opts["-f"]))
    ^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
```

I checked the code of csv2rdf.py and tried changing that call from config.readfp to config.read, but it still fails and won't parse the csv file

**Comment by ageorgou** [comment]
This is because the `readfp` method has been removed in Python 3.12. The replacement is called `read_file`.
