### ISSUE TITLE
file opening problem in windows

### ISSUE THREAD

**Issue by mustafasoylu** [RDFLib/rdflib#2644]
When I try to open a file in Windows, an error occurs because of the Windows path style. Windows file paths start like "file://C:/..." unlike unix-based "file:///...". Therefore, the first if passed on [line 460 of the parser.py](https://github.com/RDFLib/rdflib/blob/3bee979cd0e5b6efc57296b4fc43dd8ede8cf375/rdflib/parser.py#L460) and the file is handled as an URL. In my opinion, it can be fixed as below.

from
```python
    if absolute_location.startswith("file:///"):
        filename = url2pathname(absolute_location.replace("file:///", "/"))
        file = open(filename, "rb")
    else:
        input_source = URLInputSource(absolute_location, format)
```  
to->
```python
    if absolute_location.startswith("file://"):
        filename = url2pathname(absolute_location.replace("file://", ""))
        file = open(filename, "rb")
    else:
        input_source = URLInputSource(absolute_location, format)
```

**Comment by aucampia** [comment]
Can you try using file URIs as per IETF RFC 8089:

https://datatracker.ietf.org/doc/html/rfc8089

> 
> [D.2](https://datatracker.ietf.org/doc/html/rfc8089#appendix-D.2).  DOS- and Windows-Like Systems
> 
> When mapping a DOS- or Windows-like file path to a file URI, the
> drive letter (e.g., "c:") is typically mapped into the first path
> segment.
> 
> [Appendix E](https://datatracker.ietf.org/doc/html/rfc8089#appendix-E) lists some nonstandard techniques for interacting with
> DOS- or Windows-like file paths and URIs.

So that would then be `file:///C:/...` instead of `file://C:/...`.

I believe this is how python works also:

https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_uri

```console
>>> p = PurePosixPath('/etc/passwd')
>>> p.as_uri()
'file:///etc/passwd'
>>> p = PureWindowsPath('c:/Windows')
>>> p.as_uri()
'file:///c:/Windows'
```

**Comment by mustafasoylu** [comment]
Thank you very much for the answer.
