### ISSUE TITLE
Binding user-defined Namespace

### ISSUE THREAD

**Issue by cameronmore** [RDFLib/rdflib#2659]
Hello! I wrote some code that iterates through a CSV which has RDF in it like the following: 
```
cco:Person1 , rdf:type , cco:Person
cco:Person1 rdfs:label , John
```
But I can't bind my user defined namespace (cco) in the graph. I've tried something like this:
```cco = Namespace('http://www.ontologyrepository.com/CommonCoreOntologies/')
g.bind('cco',cco)
```
And this:
```
g.bind('http://www.ontologyrepository.com/CommonCoreOntologies/',cco)
```
But neither works. Instead, `ns1` is bound simply as `cco` and `ns2` is `rdfs`
How can I bind user-defined prefixes in a graph that don't resort to ns1 ns2?

**Comment by WhiteGobo** [comment]
This should work:

```
from rdflib import *

cco = Namespace("http://www.ontologyrepository.com/CommonCoreOntologies/")

g = Graph()
g.add((cco.A, BNode(), BNode()))
g.bind("cco", cco)

print(g.serialize())
#@prefix cco: <http://www.ontologyrepository.com/CommonCoreOntologies/> .
#cco:A [ ] [ ] .
```
