### ISSUE TITLE
SPARQL Subquey parse error

### ISSUE THREAD

**Issue by hussien** [RDFLib/rdflib#2684]
I am trying to  parse the following SPARQL query using Python versions (rdflib 6.2.0, pyparsing  3.0.9) and  rdflib-7.0.0
 where I face the following error:
- line 1536, in parseQuery
- line 1141, in parse_string
- pyparsing.exceptions.ParseException: Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found '{'  (at char 116), (line:5, col:21)

```
select  (count(*) as ?s)
where
{
    ?s ?p ?o.
    {
        select distinct ?s
        from <http://wikikg-v2>
        where
        {
           ?s <http://www.wikidata.org/entity/P69> ?o.
           ?s a "human".
           ?o <http://schema.org/description> ?ol.
        }
    }
}
```

Your help is appreciated

**Comment by WhiteGobo** [comment]
You cant specifiy another default graph in a subquery. You could use a federated query instead, but i dont know if you can generate an endpoint locally.

Your query then would look something like this:

```
SELECT (count(*) as ?s)
WHERE { 
    ?s ?p ?o.
    SERVICE <http://wikikg-v2/> {
        ?s <http://www.wikidata.org/entity/P69> ?o.
        ?s a "human".
        ?o <http://schema.org/description> ?ol.
    }
} 
```

**Comment by WhiteGobo** [comment]
or maybe sparql* could do this. But this might take some time. See #1554

**Comment by hussien** [comment]
> Thanks a lot, Actually my query is selecting from the same default graph so I moved the from statement to the outer query only and it works:
```
select (count(*) as ?s)
from <http://wikikg-v2/>
where
{
  ?s ?p ?o.
  {
      select distinct ?s
      where
      {
        ?s <http://www.wikidata.org/entity/P69> ?o.
        ?s a "human".
        ?o <http://schema.org/description> ?ol.
      }
  }
}
```

**Comment by WhiteGobo** [comment]
I think this issue should be closed

**Comment by hussien** [comment]
> I think this issue should be closed 

Yes
