### ISSUE TITLE
Custom FILTER function for SPARQL engine

### ISSUE THREAD

**Issue by gromgull** [RDFLib/rdflib#274]
Like Jena :)

**Comment by pchampin** [comment]
I'm assuming that, by "FILTER function", you mean any function that can be used in [FunctionCall](https://www.w3.org/TR/sparql11-query/#rFunctionCall)...
If that's the case, +1 :)

Actually, I'm working on it...

**Comment by white-gecko** [comment]
Closed by #723 via 2182c0e08e540daa4708cee619fe6588dff0b83a.
