### ISSUE TITLE
Adding a value as a list to the graph

### ISSUE THREAD

**Issue by mohmehmo** [RDFLib/rdflib#2762]
Hi,

I am writing to ask you about adding a value as a list ( e.g. "(item1 item2 item3 )") to the N3 graph from Python code. Would you please guide me to resolve this problem?

Thanks, 
Mehdi

**Comment by ashleysommer** [comment]
@mohmehmo 
Another name for a RDF "list" is a Collection.
See the docs for RDF `Collection` here: https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.Graph.collection

See this example for how to use it:
```
g = rdflib.Graph()
my_list = g.collection(rdflib.URIRef("http://example.org/my_list"))
my_list.append(rdflib.URIRef("http://example.org/Huey"))
my_list.append(rdflib.URIRef("http://example.org/Dewey"))
my_list.append(rdflib.URIRef("http://example.org/Louie"))
g.add((URIRef("http://example.org/Donald"), URIRef("http://example.org/nephews"), my_list.uri))

n3_graph = g.serialize(format="n3")
```

**Comment by mohmehmo** [comment]
@ashleysommer
Thanks for your response. Your suggestion resolved a part of my problem. Consider I have the following script to create a list as a Collection.


```
myList= BNode()
g = Graph('Memory')
c = Collection(g, myList)
for item in [1, 2, 3, 4, 5]:
  c.append(Literal(item))
```
When I want to add `c` as an object of (S, P, O) to the main graph, I faced with an error saying  "_\<object\> must be an rdflib term_". I have tried different approaches e.g. `URIRef(c)`, `c.uri`, `c.n3()`, but none of them works without error. 
Do you have any suggestions for resolving this issue?

**Comment by ashleysommer** [comment]
Hi @mohmehmo 
I've tested your snippet above. In this case, the _object_ in your triple should be `myList` or `c.uri`, both work.

```python
from rdflib import Graph, BNode, Literal, URIRef
from rdflib.collection import Collection

myList = BNode()
g = Graph()
c = Collection(g, myList)
for item in [1, 2, 3, 4, 5]:
  c.append(Literal(item))

g.add((URIRef("http://example.org/"),URIRef("http://example.org/my_list"), myList))

# Test it:
print(g.serialize(format="turtle"))
```
or
```python
from rdflib import Graph, BNode, Literal, URIRef
from rdflib.collection import Collection

myList = BNode()
g = Graph()
c = Collection(g, myList)
for item in [1, 2, 3, 4, 5]:
  c.append(Literal(item))

g.add((URIRef("http://example.org/"),URIRef("http://example.org/my_list"), c.uri))

# Test it:
print(g.serialize(format="turtle"))
```

**Comment by mohmehmo** [comment]
@ashleysommer
Thanks a lot for your support. it is fine now.
