### ISSUE TITLE
Bug in `longturtle` serialization

### ISSUE THREAD

**Issue by mschiedon** [RDFLib/rdflib#2767]
The `longturtle` serializer fails to emit a whitespace separator between a predicate and a list of objects if one of these objects is a blank node (and the blank node cannot be 'inlined', i.e. is used more than once). The problem can be reproduced using this Python code:

```python
from rdflib import Graph

input = '''\
@prefix ex: <https://example.org/> .

ex:1 a ex:Thing ;
    ex:relatedTo ex:3, _:bnode0 .

ex:2 a ex:Thing ;
    ex:relatedTo _:bnode0 .

_:bnode0 a ex:Thing .
'''

graph = Graph().parse(data=input, format='turtle')
output = graph.serialize(format='longturtle')
print(output)
assert output.find('relatedTo_:') == -1, \
    'Missing whitespace separation between predicate' \
    ' and the first blank node of a list of objects.'
```

The resulting Turtle with the bug looks like below. Note the missing space between the predicate `ex:relatedTo` and blank node `_:n40fef3a41a034be9a7116df126afd613b1` for the `ex:1` case. The `ex:2` case does correctly use a space separator when serializing because it's a single object and not a list.

```turtle
PREFIX ex: <https://example.org/>

ex:1
    a ex:Thing ;
    ex:relatedTo_:n40fef3a41a034be9a7116df126afd613b1 ,
        ex:3 ;
.

ex:2
    a ex:Thing ;
    ex:relatedTo _:n40fef3a41a034be9a7116df126afd613b1 ;
.

_:n40fef3a41a034be9a7116df126afd613b1
    a ex:Thing ;
.
```

I believe the issue might be solved by adding an additional indent in the `longturtle.py` source code on [this line](https://github.com/RDFLib/rdflib/blob/7c99182845a156ba511a5240e266badc905ab73a/rdflib/plugins/serializers/longturtle.py#L295), as shown in the code below.

```python
    def objectList(self, objects):
        count = len(objects)
        if count == 0:
            return
        depthmod = (count == 1) and 0 or 1
        self.depth += depthmod
        first_nl = False
        if count > 1:
            if not isinstance(objects[0], BNode):
                self.write("\n" + self.indent(1))
                # BUG: Gave below line an extra indent.
                first_nl = True
        self.path(objects[0], OBJECT, newline=first_nl)
        for obj in objects[1:]:
            self.write(" ,")
            if not isinstance(obj, BNode):
                self.write("\n" + self.indent(1))
            self.path(obj, OBJECT, newline=True)
        self.depth -= depthmod
```

**Comment by nicholascar** [comment]
I think this issue has been addressed by PR https://github.com/RDFLib/rdflib/pull/2700 but that fix is currently only in the HEAD of this repo, not an RDFlib release yet. It should appear in 7.0.1 or 7.1.0 in the next few weeks when we make that release which will fix a bunch of small things.

**Comment by mschiedon** [comment]
> I think this issue has been addressed by PR #2700 but that fix is currently only in the HEAD of this repo, not an RDFlib release yet. It should appear in 7.0.1 or 7.1.0 in the next few weeks when we make that release which will fix a bunch of small things.

Excellent! I can confirm this addresses the issue. Looking forward to the next `rdflib` release then 👍

**Comment by danielpcampagna** [comment]
Are there any updates on this issue?

**Comment by edmondchuc** [comment]
I think the changes made in that PR were inadvertently reverted by https://github.com/RDFLib/rdflib/pull/2731/commits/beda4faa0da5ec455239fad1c411ded74de091c6 in PR https://github.com/RDFLib/rdflib/pull/2731. 

From memory, mypy was failing and complaining that the else block was unreachable code. We may have to re-submit the PR again and add some annotations to instruct mypy to ignore the error.

**Comment by mschiedon** [comment]
> I think the changes made in that PR were inadvertently reverted by [beda4fa](https://github.com/RDFLib/rdflib/commit/beda4faa0da5ec455239fad1c411ded74de091c6) in PR #2731.
> 
> From memory, mypy was failing and complaining that the else block was unreachable code. We may have to re-submit the PR again and add some annotations to instruct mypy to ignore the error.

Yes, that may be the commit where the fix was regressed. If the `mypy` complaint was about the `elif` in below code, that was probably a legitimate complaint, since something that is **not** a `BNode` would include an `IRI` and `Literal`, so the `elif` would then never trigger for the `Literal`.

```python
            if not isinstance(objects[0], BNode):
                self.write("\n" + self.indent(1))
            elif isinstance(objects[0], Literal):
                self.write(" ")
```

Note that the above code would not have fixed the missing space separator between the predicate and the blank node identifier. The code from #2700 would, which I would hope (*expect*) `mypy` would not have an issue with:

```python
            if not isinstance(objects[0], BNode):
                self.write("\n" + self.indent(1))
            else:
                self.write(" ")
```
