### ISSUE TITLE
regenerate _DOAP.py

### ISSUE THREAD

**Issue by raboof** [RDFLib/rdflib#2811]
The definition at http://usefulinc.com/ns/doap has been updated since the previous generation (for example it now contains `security-contact` and `security-policy` properties).

Unfortunately when I `python3 ./rdflib/tools/defined_namespace_creator.py doap.xml http://usefulinc.com/ns/doap# DOAP` the generated result does not look correct to me - but perhaps I'm misusing it?

**Comment by nicholascar** [comment]
Were you getting a shell error, perhaps:

```bash
no matches found: http://usefulinc.com/ns/doap#
```

try quoting (") the IRI:

```bash
python3 ./rdflib/tools/defined_namespace_creator.py doap.xml "http://usefulinc.com/ns/doap#" DOAP
```

If you regenerate DOAP, please inspect it and fix ant small issues by hand and consider submitting a PR to update the version in RDFLib

**Comment by raboof** [comment]
> please inspect it and fix any small issues - inconsistent languages etc. - by hand

Gotcha. It seems the definition has descriptions in several languages. Should all languages be kept or just the English one?

**Comment by raboof** [comment]
> consider submitting a PR to update the version in RDFLib

#2869
