### ISSUE TITLE
Add xsd:duration sparql functionality

### ISSUE THREAD

**Issue by cameronmore** [RDFLib/rdflib#2865]
Are you able to add xsd:duration functionality to the SPARQL function?

**Comment by nicholascar** [comment]
Do you mean does RDFLib's SPARQL processing support the `TIMEZONE` SPARQL function as per https://www.w3.org/TR/sparql12-query/#func-timezone? That's the only reference to "duration" I can find in SPARQL.

Or do you mean can RDFLib support date arithmetic?

If you mean can you use duration as a datatype then yes: `Literal("P20M", datatype=XSD.duration)` which is 20 months

**Comment by cameronmore** [comment]
I think I meant arithmetic, adding some "P20M"^^xsd:duration to "2018-05-28T12:14:45Z"^^xsd:datetime, described [here](https://github.com/w3c/sparql-dev/issues/32), but now I realize I may be looking for something which is not outlined in sparql 1.1
