### ISSUE TITLE
Lacking plugin for sparql query results of format application/json

### ISSUE THREAD

**Issue by daghovland** [RDFLib/rdflib#2887]
SPARQL Query results can be formatted in json, as specified in [https://www.w3.org/TR/sparql11-results-json/](https://www.w3.org/TR/sparql11-results-json/ )

The specification states that the Content-Type should be 'application/sparql-results+json'. 

The sparql query result plugins, registered on [plugin.ph](https://github.com/RDFLib/rdflib/blob/main/rdflib/plugin.py), lines 555-615, includes a plugin for 'json' in addition to the required 'application/sparql-results+json'. 

However, there is no plugin for 'application/json'. 

Fixed in PR #2893

**Comment by ashleysommer** [comment]
@daghovland 
The registration of simply "json" is used as a shorthand for  `application/sparql-results+json`. This is just the same way that "turtle" is registered as a shorthand for `text/ttl`.

The content-type `application/json` is not a valid return type for SPARQL query results, so should not be registered in the list of query result plugins.

**Comment by daghovland** [comment]
Ok.
