### ISSUE TITLE
Update some defined namespaces

### ISSUE THREAD

**Issue by ashleysommer** [RDFLib/rdflib#2902]
Some warnings I've seen in the last few weeks while working with GeoSPARQL and SOSA Defined Namespaces.

```
 UserWarning: Code: FeatureCollection is not defined in namespace GEO
  feature_finder = g.subjects(RDF.type, GEO.FeatureCollection)
UserWarning: Code: hasDefaultGeometry is not defined in namespace GEO
  elif pred in [GEO.hasGeometry, GEO.hasDefaultGeometry]:
Code: asGeoJSON is not defined in namespace GEO
  coords = g.value(obj, GEO.asGeoJSON)
UserWarning: Code: hasMember is not defined in namespace SOSA
  if pred == SOSA.hasMember:
```

I understand the newer versions of GeoSPARQL and SOSA are in a constantly evolving state, and some new proposed or accepted properties may not yet have made it into any official ontology release. What is our stance on implementing new features into existing Defined Namespaces?

**Comment by nicholascar** [comment]
I don't understand the GEO issues as the tree elements mentioned are already in the DefinedNamespace:

* `FeatureCollection`: [L37](https://github.com/RDFLib/rdflib/blob/main/rdflib/namespace/_GEO.py#L37)
* `hasDefaultGeometry`: [L84](https://github.com/RDFLib/rdflib/blob/main/rdflib/namespace/_GEO.py#L84)
* `asGeoJSON`: [L46](https://github.com/RDFLib/rdflib/blob/main/rdflib/namespace/_GEO.py#L46)

The SOSA one is part of [SOSA Ext.](https://www.w3.org/TR/vocab-ssn-ext/), so those elements I can add.

**Comment by ashleysommer** [comment]
Ah, I see. The GEO 1.1 parts were added in March this year, so it's not part of the current v7 release.
https://github.com/RDFLib/rdflib/commit/52e2461fa14d4e4e27f8ea9f3195378a1f8ed41b

Similarly, the SOSA update was added not long after the last release.
https://github.com/RDFLib/rdflib/commit/ecad1e35dda8e3388287c6b65186f36fba9139ae

That's why I'm seeing the errors, so I can go ahead and close this.
