### ISSUE TITLE
No plugin registered for `text/rdf+n3`

### ISSUE THREAD

**Issue by sindikat** [RDFLib/rdflib#340]
I can't dereference URIs that start from "http://dbpedia.org/ontology/":

```
>>> g.parse('http://dbpedia.org/ontology/Person')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rdflib/graph.py", line 1025, in parse
    parser = plugin.get(format, Parser)()
  File "/usr/local/lib/python2.7/dist-packages/rdflib/plugin.py", line 103, in get
    "No plugin registered for (%s, %s)" % (name, kind))
rdflib.plugin.PluginException: No plugin registered for (text/rdf+n3, <class 'rdflib.parser.Parser'>)
```

Is this DBPedia's problem (content-type `text/rdf+n3`?) or `Graph.parse` problem?

**Comment by nicholascar** [comment]
This issue has had no comments for 6+ years so I'm closing in an effort to tidy up Issues generally.

The substantive point - handling of `text/rdf+n3` has gone away since many years have now passed with an official Media Type of `text/n3` being widely known.
