### ISSUE TITLE
sparql update performance

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib#369]
I'm currently experimenting with nose-timer as some of the tests seem to take a very long time in all of the travis runs.

This one in particular:
test.test_dawg.test_dawg(RDFTest(uri=rdflib.term.URIRef('http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-update-2/manifest#syntax-update-other-01'), name='syntax-update-other-01', comment=None, data=None, graphdata=None, action='file:///home/travis/build/joernhees/rdflib/build/src/test/DAWG/data-sparql11/syntax-update-2/large-request-01.ru', result=None, syntax=True),): 31.8953s

To me it seems that https://github.com/RDFLib/rdflib/blob/master/test/DAWG/data-sparql11/syntax-update-2/large-request-01.ru adds about 1000 triples. Even though this is a "large-request" i think it should take less than 30s.

(yes, travis vms have different speeds, but this isn't about the absolute 30s but the relative test case times (most test cases are << 1s in the same test run))

**Comment by gjhiggins** [comment]
It's a pytest timer plugin these days: `pip install pytest-timer` and according to the run, this is no longer an issue (longest time is `test/test_graph.py::GraphTestCase::testGuessFormatForParse` at 2.3843s
