### ISSUE TITLE
Parsing error for Unicode in freebase

### ISSUE THREAD

**Issue by rosshorne** [RDFLib/rdflib#415]
Parsing fails for certain literals. For example, the following curl returns apparently fine ntriples.
curl https://www.googleapis.com/freebase/v1/rdf/m/012s3l

However, the following code using rdflib results in a parse error.
g.parse("https://www.googleapis.com/freebase/v1/rdf/m/012s3l", format="n3")

I'm reproducing the relevant error below, which indicates that there is a parse problem with "^\xab" that appears in a literal.

rdflib.plugins.parsers.notation3.BadSyntax: at line 14 of <>:
Bad syntax (bad escape) at ^ in:
"...438\u043d \u0437 \u0442\u0432\u043e\u0440\u0446\u0456\u0432 ^\xab\u0448\u043a\u0456\u043b\u044c\u043d\u043e\u0457 \u0456\..."

Since this URI is for freebase, we can't change the data. Would it be possible to fix the parser? I notice there are sever comments elsewhere about problems parsing Unicode, so this problem probably applies to a class of escape characters.

**Comment by joernhees** [comment]
closing this for now, please re-open if needed
