### ISSUE TITLE
Trig parser can creating multiple contexts for the default graph

### ISSUE THREAD

**Issue by dschallis** [RDFLib/rdflib#432]
If TriG containing triples in the default graph are specified with and without braces, they end up in 2 separate contexts, e.g.:

    import rdflib

    data = """
    @prefix : <http://example.com/> .
    <> <b> <c> .
    { <d> <e> <f> . }
    """
    g = rdflib.ConjunctiveGraph()                                                  
    g.parse(data=data, format='trig')                                              
    print len(list(g.contexts()))

Prints:

    2

whereas it should contain only 1 context, i.e. a single default graph that both those triples should belong to.

I've added a unit test for this to https://github.com/RDFLib/rdflib/pull/431 .

**Comment by niklasl** [comment]
I fixed this similarly to the fix in #536 (for #535). The remaining issue is #436, concerning the `default_context` attribute in relation to how `parse(...)` dermines target graph using the `source` and `publicID` parameters.
