### ISSUE TITLE
python3 code seems shockingly inefficient

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib#440]
Comparing the typical travis run times of py2 and py3 tests it seems py3 is on avg. taking 2x as long.
This only partially seems to be due to the 2to3 runs and a wild guess of me is that it has to do with some `items()` -> `list(items())` transformation.

It seems this becomes most apparent in this test: 

Python3.4: 86 seconds

``` python
test.test_dawg.test_dawg(RDFTest(uri=rdflib.term.URIRef('http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-update-2/manifest#syntax-update-other-01'), name='syntax-update-other-01', comment=None, data=None, graphdata=None, action='file:///home/travis/build/RDFLib/rdflib/build/src/test/DAWG/data-sparql11/syntax-update-2/large-request-01.ru', result=None, syntax=True),): 86.3655s
```

Python2.7: 49 seconds

``` python
test.test_dawg.test_dawg(RDFTest(uri=rdflib.term.URIRef(u'http://www.w3.org/2009/sparql/docs/tests/data-sparql11/syntax-update-2/manifest#syntax-update-other-01'), name=u'syntax-update-other-01', comment=None, data=None, graphdata=None, action=u'file:///home/travis/build/RDFLib/rdflib/test/DAWG/data-sparql11/syntax-update-2/large-request-01.ru', result=None, syntax=True),): 49.0514s
```

Todos:
- [ ] check why test is so slow in general (profiler-runs)
- [ ] check if it can be decomposed

**Comment by gromgull** [comment]
Here: py2 test in 2m09s - py3 in 4-6 minutes :( 

https://travis-ci.org/RDFLib/rdflib/builds/196356635

(ignoring that one test failed, it's unrelated)

**Comment by gromgull** [comment]
They are comparable now: https://travis-ci.org/RDFLib/rdflib/builds/447210434

**Comment by ashleysommer** [comment]
This was closed as resolved, (I don't know if it resolved itself over time, with updates in Python3, or a fix was made in rdflib). I'm changing milestone from 6.0.0 to 5.0.0 for inclusion in the 5.0.0 changelog.
