### ISSUE TITLE
RDF 1.1 tests & support

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib#450]
we should properly test & support RDF 1.1.

I see the following TODOs: (help welcome)
- [ ] integrate test cases into our test suite: http://www.w3.org/TR/2014/NOTE-rdf11-testcases-20140225/ ( or check if they're integrated already:
  - [ ] Turtle
  - [ ] TriG
  - [ ] N-Triples
  - [ ] N-Quads
  - [ ] XML
  - [ ] JSON-LD

As discussed in #400 backwards compatibility would be nice.
- For parsers this hopefully means that the new version can still parse the old one.
- For serializers we should probably provide a way to write the old style RDF 1.0 files in the specified format and default to writing the new style RDF 1.1 files.

Any thoughts on this welcome @RDFLib/rdflib

**Comment by niklasl** [comment]
+1. Solving #436 is probably part of this work.

**Comment by gjhiggins** [comment]
As far as I can tell from the W3's [What's New in RDF 1.1](https://www.w3.org/TR/rdf11-new/)  RDFLib now fully supports it.

**Comment by aucampia** [comment]
I'm not sure we are running all these test suites, and even if we are I think we are skipping large amounts of them.

**Comment by gjhiggins** [comment]
I guess it's worth checking that the desired coverage is achieved. grepping for `read_manifest` turns up, for example, https://github.com/RDFLib/rdflib/blob/57f993d770725a871e4b0f66889208c7d9e91457/test/test_trig_w3c.py#L92 and the tests in the [corresponding folder](https://github.com/RDFLib/rdflib/tree/master/test/w3c/trig) match those of the [W3 test suite](https://www.w3.org/2013/TrigTests/)

Elsewhere, these tests call `read_manifest` and run the corresponding tests:

> test/test_trig_w3c.py
> test/test_parsers/test_nquads_w3c.py
> test/test_parsers/test_turtle_w3c.py
> test/test_parsers/test_nt_w3c.py

Seem to be missing the 1.1 rdfxml tests (the rdfxml 1.0 tests don't use `read_manifest` but `test/test_rdfxml.py` instead) and the RDF 1.1 Semantics tests.

Most of the skipped tests (in `skiptests.list`) are sparql11 tests

**Comment by gjhiggins** [comment]
Further to this. I'm working on collecting up the test suites into a single `test_suites` directory to live in `consistent_test_data` and it appears that `tests/n3` is unused apart from a couple of specific tests because renaming`n3` to `_n3` only produces these two failures:
```
FAILED test/test_n3.py::TestN3Case::test_issue156 - FileNotFoundError: [Errno 2] No such file or directory: '.../test/n3/issue156.n3'
FAILED test/test_misc/test_parse_file_guess_format.py::FileParserGuessFormatTest::test_n3 - FileNotFoundError: [Errno 2] No such file or directory: '.../test/n3/example-lots_of_graphs.n3'
```

**Comment by aucampia** [comment]
I will hold off with fixing reporting then. I would prefer we do open a new issue for this though. Also I think it may make sense to just put test data in 'test/data/' as that already implies that is test data and it should be consistent from the outset.

**Comment by aucampia** [comment]
Maybe we should make an issue for tracking test reorg also to discuss layout.

**Comment by gjhiggins** [comment]
> Also I think it may make sense to just put test data in 'test/data/' as that already implies that is test data and it should be consistent from the outset.

Agreed.
