### ISSUE TITLE
testConjunctiveDefault for sparqlupdatestore fails locally

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib#460]
if you run a local sparql store e.g. with `fuseki-server --mem --update /ukpp` the tests in https://github.com/RDFLib/rdflib/blob/master/test/test_sparqlupdatestore.py will run (and not be skipped as by default on travis).

One of the existing tests in there seems to fail:
```
FAIL: testConjunctiveDefault (test.test_sparqlupdatestore.TestSparql11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/joern/coding/git/rdflib/rdflib/test/test_sparqlupdatestore.py", line 86, in testConjunctiveDefault
    'default union graph contains three triples')
AssertionError: 3 != 0 : default union graph contains three triples
```

Can someone verify?

**Comment by joernhees** [comment]
@gjhiggins sorry to ping you again, seems you wrote that test as well...

maybe i should investigate if we can somehow set travis to run these tests as well...

**Comment by gjhiggins** [comment]
np.
I'm seeing 9/9 tests passing for test_sparqlupdatestore.py under Python 3.4 and fuseki 1.1.0.
And I agree, it should be feasible to get travis to make available a local instance of fuseki, I shall give it a go.

**Comment by joernhees** [comment]
hmm weird, i was running them with `./run_tests.py test/test_sparqlupdatestore.py` on Python 2.7 on the 4.2.1-dev version, but i had 10 tests...

**Comment by uholzer** [comment]
I'm pretty sure that the result of this test depends on the SPARQL endpoint. As far as I know, the SPARQL protocol leaves it to the endpoint whether the default graph is the union of all named graphs or whether it is a seperate graph. ([There is a way to specify the default graph][1] as the merge of several named graphs, but it does not seem to be possible to have the merge of _all_ graphs.)

[1]: http://www.w3.org/TR/2013/REC-sparql11-query-20130321/#specifyingDataset

**Comment by joernhees** [comment]
@gromgull told me the same. I think i fixed it over in #466 by running `fuseki` with `--memTDB --set tdb:unionDefaultGraph=true`.

**Comment by joernhees** [comment]
hmm,  actually after the tests ran through it seems that ConjunctiveGraph and Dataset need two different behaviors from the endpoint.

**Comment by uholzer** [comment]
Yes, I suspect this is the case. Actually, Dataset is better suited to use with SPARQLStore, as it is based on SPARQL's definition of a Dataset. ConjunctiveGraph requires the default graph to be the merge of all graphs, which is not necessary for Dataset. So, I would recommend to use the SPARQL store only with Dataset. Also, the developer should be aware that the behaviour of the default graph of such a Dataset may be different for different endpoints.

**Comment by joernhees** [comment]
i see at least to possible ways out of this:
 1. we remove the tests for the specific behavior of ConjunctiveGraph (i somehow don't like removing tests)
 2. we just run two local endpoints with different behaviors.

For now i've implemented 2 in #466.

@uholzer, @gjhiggins is that ok / enough or do we need to warn developers?

**Comment by uholzer** [comment]
I like the solution you implemented.

Maybe the documentation of SPARQL(Update)Store should include a warning that the behaviour of the default graph depends on the endpoint. Also, I think we should recommend to avoid using it with ConjunctiveGraph for exactly this reason.

**Comment by joernhees** [comment]
ok, i expanded the docstrings of SPARQLStore & SPARQLUpdateStore a bit, see 3a706e2c6aded68cf12e56c9937d0c1800146ecd

i think i'll merge #466 soon...

**Comment by uholzer** [comment]
Now it's perfect! Thanks.
