### ISSUE TITLE
decrease number of skipped tests

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib#461]
currently a lot of tests are skipped (98 as in https://travis-ci.org/RDFLib/rdflib/jobs/52130178) .
- [ ] find out why so many are skipped
- [x] see if travis environments can be configured to run more (e.g., local sparql endpoints)
- [ ] re-enable what's possible

**Comment by gjhiggins** [comment]
Yup.
commit https://github.com/gjhiggins/rdflib/commit/7d3c58ede43125fcceff03f91727c3301e75ab5f
and travis job 
https://travis-ci.org/gjhiggins/rdflib/jobs/52323760
confirming your observation of a test failure for sparqlupdatestore.

Worth a PR or would prefer to integrate it by hand?

**Comment by joernhees** [comment]
wow, cool, thanks for figuring that out.

sure, always worth a pull request... just refer this issue in it

**Comment by gjhiggins** [comment]
Expired.
