### ISSUE TITLE
should we provide wheels?

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib#478]
http://pythonwheels.com/

**Comment by uholzer** [comment]
Only if they are round.

Wait. Does this mean that rdflib is among the top 360 most-downloaded packages on PyPI? Hurray!

**Comment by uholzer** [comment]
Joking aside: I didn't know about wheels until now. In fact, I care more about Debian packages. However, packaging.python.org says that wheels are the right thing to create, so, I would say that yes, we should provide wheels.

**Comment by gromgull** [comment]
Thanks to @joernhees now we do!
