### ISSUE TITLE
DESCRIBE query not working

### ISSUE THREAD

**Issue by nvitucci** [RDFLib/rdflib#479]
Apparently DESCRIBE queries are not fully implemented yet? This is what I get with two different queries:
###### 

1) g.query('DESCRIBE http://www.example.org/a')
...
/usr/lib/python2.7/site-packages/rdflib/plugins/sparql/algebra.pyc in translate(q)
    530 
    531     # all query types have a where part
--> 532     M = translateGroupGraphPattern(q.where)
    533 
    534     aggregate = False

/usr/lib/python2.7/site-packages/rdflib/plugins/sparql/algebra.pyc in translateGroupGraphPattern(graphPattern)
    261     """
    262 
--> 263     if graphPattern.name == 'SubSelect':
    264         return ToMultiSet(translate(graphPattern)[0])
    265 

AttributeError: 'NoneType' object has no attribute 'name'

2) g.query('DESCRIBE ?s WHERE {?s ?p ?o FILTER (?s = http://www.example.org/a)}')

...
/usr/lib/python2.7/site-packages/rdflib/plugins/sparql/evaluate.pyc in evalPart(ctx, part)
    260 
    261     elif part.name == 'DescribeQuery':
--> 262         raise Exception('DESCRIBE not implemented')
    263 
    264     else:

Exception: DESCRIBE not implemented
###### 

The graph is created via this sequence:

import rdflib
from rdflib import RDF

ex = rdflib.Namespace('http://www.example.org/')
g = rdflib.Graph()
g.add((ex['a'], RDF['type'], ex['Cl']))

**Comment by gromgull** [comment]
As the exception says `DESCRIBE` queries are not supported. It should be easy enough to implement, PRs are as always welcome :) 

Without checking, but I think the first query should be `DESCRIBE <http://example.org/a>.` then you should get an exception saying it's not implemented there as well :)

**Comment by joernhees** [comment]
describe needs CBDs, so should be based on the solution to #123

**Comment by fardokhtsadat** [comment]
Hello,

I am using rdflib version 6.0.2, and for describe queries, I get the following error:
`Exception: DESCRIBE not implemented`

Is this issue fixed or describe the queries are still not implemented in rdflib?

Best regards,
Fardokht

**Comment by ms1901** [comment]
Hey!
As mentioned in the conversation above, DESCRIBE query implementation would require the use of CBDs. I have been working on implementing the DESCRIBE query, which returns a SPARQL result containing all triples with the query as our subject and object, along with the resolution of triples containing blank nodes. This implementation will return the result for `DESCRIBE <http://example.org/a>`.

**Comment by aucampia** [comment]
See also:
- https://github.com/RDFLib/rdflib/issues/813

**Comment by gargayush18** [comment]
Hey , I would also like to work on this issue.

**Comment by gargayush18** [comment]
One of the possible for this could be use of the multiple Select queries to find the solution for the Describe Query. 
This will lead to the use of the exactly 2 select Queries. 
Could be better explained with an example: 
Example: 
  PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
  DESCRIBE ?x
  WHERE    { ?x foaf:name "Alice" }

Now here we can use first Select Query to find the exact values of ?x.
this could be achieved through the Query: 

PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
  SELECT ?x
  WHERE    { ?x foaf:name "Alice" }


Lets suppose we get ?x as "www.example.org/Alice"

now can breakdown this? x into the prefix and corresponding value let's say : prefix: Alice in this case

Now run the query 
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
  SELECT ?p ?q
  WHERE    {prefix:Alice ?p ?q }

This will return all the results related to the Alice and then this result can be formatted to produce the result .

**Comment by gjhiggins** [comment]
That approach could work but an implementation that aims to conform to [SPARQL 1.1](https://www.w3.org/2021/12/rdf-star.html#sparql-star-ebnf) spec would also have to observe SolutionModifier constraints:

```
DescribeQuery | ::= | "DESCRIBE" ( VarOrIri+  \| "*")  DatasetClause*  WhereClause?  SolutionModifier
```
