### ISSUE TITLE
Why when I add a Literal(False).n3() in a triple I got an error?

### ISSUE THREAD

**Issue by cryptid11** [RDFLib/rdflib#485]
Erorr I get:
```

AssertionError: Subject "false"^^<http://www.w3.org/2001/XMLSchema#boolean> must be an rdflib term
```

What I do:
```

from rdflib import URIRef, Variable
from rdflib import Graph, URIRef, Literal
g = Graph()
g.add((URIRef("http://www.w3.org/exmple"),URIRef("http://www.w3.org/2000/01/rdf-schema#label"),Literal(False).n3()))
```

Any hint? What's the problem?

**Comment by niklasl** [comment]
RDFLib complains about adding a native string instead of a Literal instance. You shouldn't turn the Literal into an n3 representation string. Just do:

    g.add((URIRef("http://www.w3.org/exmple"), URIRef("http://www.w3.org/2000/01/rdf-schema#label"), Literal(False)))

(Tip: `from rdflib import RDFS` and:
`g.add((URIRef("http://www.w3.org/exmple"), RDFS.label, Literal(False)))`)

**Comment by cryptid11** [comment]
Thanks, but so the example here is to mislead?
https://rdflib.readthedocs.org/en/latest/apidocs/rdflib.html#rdflib.term.Literal.n3

And if I have also to use things like: Literal(2, datatype=URIRef("http://qudt.org/vocab/unit#Meter")).n3() ? What to do in this case?

**Comment by niklasl** [comment]
No, the examples show how to use the `n3` method on `Literal`instances to get a native string representation of the literal in Notation 3 format (which for these objects is equivalent to the Turtle format).

You are not supposed to use this method at all when adding values to a `Graph` instance, as that uses instances of the rdflib term types themselves.

So if you need to add a literal typed with the qudt:Meter datatype, just use the instance created by:

    Literal(2, datatype=URIRef("http://qudt.org/vocab/unit#Meter"))

**Comment by cryptid11** [comment]
Thanks it works, my fault! :dart: 
I really have to try more things before asking...
