### ISSUE TITLE
installing rdflib as egg on py3 seems to skip 2to3 setup step, resulting in NameError: name 'unichr' is not defined

### ISSUE THREAD

**Issue by douglas-larocca** [RDFLib/rdflib#487]
[The commit](https://github.com/RDFLib/rdflib/commit/b8845b52f9e7a40cf96b04cadb7964316a06fdbc). The python2 `unichr` builtin will raise `NameError` on python3.

**Comment by joernhees** [comment]
Can you elaborate on that? The [tests](https://travis-ci.org/RDFLib/rdflib) are passing and currently the files are still run through 2to3 which should replace those occurrences.

**Comment by douglas-larocca** [comment]
With a clean env
<pre>
douglas-larocca@testbox ~ » virtualenv -p /usr/bin/python3.4 rdflib_test_venv
Running virtualenv with interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in rdflib_test_venv/bin/python3.4
Also creating executable in rdflib_test_venv/bin/python
Installing setuptools, pip...done.
</pre>
that's activated
<pre>
douglas-larocca@testbox ~ » source rdflib_test_venv/bin/activate
</pre>
and working
<pre>
(rdflib_test_venv)douglas-larocca@testbox ~ » which python
/home/larocca/rdflib_test_venv/bin/python
</pre>
with the right version
<pre>
(rdflib_test_venv)douglas-larocca@testbox ~ » python
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
</pre>
install latest rdflib
<pre>
(rdflib_test_venv)douglas-larocca@testbox ~ » pip install -e git+git://github.com/RDFLib/rdflib#egg=RDFLib
Obtaining RDFLib from git+git://github.com/RDFLib/rdflib#egg=RDFLib
  Cloning git://github.com/RDFLib/rdflib to ./rdflib_test_venv/src/rdflib
  Running setup.py (path:/home/larocca/rdflib_test_venv/src/rdflib/setup.py) egg_info for package RDFLib
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*$py.class' found anywhere in distribution
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma

    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*$py.class' found anywhere in distribution
  Installing extra requirements: 'egg'
Downloading/unpacking isodate (from RDFLib)
  Downloading isodate-0.5.1.tar.gz
  Running setup.py (path:/home/larocca/rdflib_test_venv/build/isodate/setup.py) egg_info for package isodate

Downloading/unpacking pyparsing (from RDFLib)
  Downloading pyparsing-2.0.3-py2.py3-none-any.whl
Installing collected packages: RDFLib, isodate, pyparsing
  Running setup.py develop for RDFLib
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*$py.class' found anywhere in distribution
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma

    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*$py.class' found anywhere in distribution
    Creating /home/larocca/rdflib_test_venv/lib/python3.4/site-packages/rdflib.egg-link (link to .)
    Adding rdflib 4.2.1-dev to easy-install.pth file
    Installing rdfgraphisomorphism script to /home/larocca/rdflib_test_venv/bin
    Installing csv2rdf script to /home/larocca/rdflib_test_venv/bin
    Installing rdf2dot script to /home/larocca/rdflib_test_venv/bin
    Installing rdfpipe script to /home/larocca/rdflib_test_venv/bin
    Installing rdfs2dot script to /home/larocca/rdflib_test_venv/bin

    Installed /home/larocca/rdflib_test_venv/src/rdflib
  Running setup.py install for isodate
    Fixing build/lib/isodate/isoduration.py build/lib/isodate/isotzinfo.py build/lib/isodate/isodates.py build/lib/isodate/tzinfo.py build/lib/isodate/__init__.py build/lib/isodate/isostrf.py build/lib/isodate/isoerror.py build/lib/isodate/isotime.py build/lib/isodate/duration.py build/lib/isodate/isodatetime.py build/lib/isodate/tests/test_datetime.py build/lib/isodate/tests/test_strf.py build/lib/isodate/tests/test_date.py build/lib/isodate/tests/__init__.py build/lib/isodate/tests/test_duration.py build/lib/isodate/tests/test_pickle.py build/lib/isodate/tests/test_time.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    Fixing build/lib/isodate/isoduration.py build/lib/isodate/isotzinfo.py build/lib/isodate/isodates.py build/lib/isodate/tzinfo.py build/lib/isodate/__init__.py build/lib/isodate/isostrf.py build/lib/isodate/isoerror.py build/lib/isodate/isotime.py build/lib/isodate/duration.py build/lib/isodate/isodatetime.py build/lib/isodate/tests/test_datetime.py build/lib/isodate/tests/test_strf.py build/lib/isodate/tests/test_date.py build/lib/isodate/tests/__init__.py build/lib/isodate/tests/test_duration.py build/lib/isodate/tests/test_pickle.py build/lib/isodate/tests/test_time.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma

Successfully installed RDFLib isodate pyparsing
Cleaning up...
</pre>
and try to use it
<pre>
(rdflib_test_venv)douglas-larocca@testbox ~ » python
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdflib import Graph
INFO:rdflib:RDFLib Version: 4.2.1-dev
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/larocca/rdflib_test_venv/src/rdflib/rdflib/__init__.py", line 85, in <module>
    unichr(0x10FFFF)
NameError: name 'unichr' is not defined
>>>
</pre>

**Comment by douglas-larocca** [comment]
The only exception class caught here is `ValueError` so `NameError` will still raise.

```python
try:
    unichr(0x10FFFF)
except ValueError:
    import warnings
    warnings.warn(
        'You are using a narrow Python build!\n'
        'This means that your Python does not properly support chars > 16bit.\n'
        'On your system chars like c=u"\\U0010FFFF" will have a len(c)==2.\n'
        'As this can cause hard to debug problems with string processing\n'
        '(slicing, regexp, ...) later on, we strongly advise to use a wide\n'
        'Python build in production systems.',
        ImportWarning)
    del warnings
```

**Comment by joernhees** [comment]
hmm, ok, i can reproduce this, but it seems to be a problem of installing rdflib from git as an egg
```
pip install -e git+git://github.com/RDFLib/rdflib#egg=RDFLib
```

If you instead run
```
pip install rdflib
```
or even
```
pip install git+git://github.com/RDFLib/rdflib
```
it should work as expected. My guess is that when building the egg 2to3 is not run correctly.

**Comment by joernhees** [comment]
to explain this a bit more:

fixing this one problem with `unichr` would not fix the problem in general as it's only the first python3 incompatibility that is encountered, but we have hundreds of them (as any project that uses 2to3).
There are two ways to fix this:
 - make the egg correctly run 2to3 for now
 - wait for #438 (which removes the need for 2to3 completely)

**Comment by gromgull** [comment]
pip has removed the `-e` syntax anyway, so this is dead.
