### ISSUE TITLE
default-graph-uri parameter with SPARQLUpdateStore

### ISSUE THREAD

**Issue by glibersat** [RDFLib/rdflib#489]
Hi,

I'm using fuseki as a triple store with SPARLUpdateStore backend.
When performing a store.triples(), everything is fine.
When using store.query() and issuing a correct query, a parameter "default-graph-uri" is added to the request (it was NOT when using triples()), thus the returned set is empty.

Am I missing something or is this behaviour inconsistent between the two methods?

Thx!

**Comment by gjhiggins** [comment]
Unable to replicate, long since fixed.
