### ISSUE TITLE
Message "INFO:rdflib:RDFLib Version: 4.2.0"

### ISSUE THREAD

**Issue by tobiasschweizer** [RDFLib/rdflib#490]
This is not a problem, I am just curious: Where is this message coming from?

> INFO:rdflib:RDFLib Version: 4.2.0

It seems to be caused by this import statement:

```
from rdflib import Namespace, RDF, RDFS, Graph, URIRef, term
```

**Comment by gromgull** [comment]
https://github.com/RDFLib/rdflib/blob/master/rdflib/__init__.py#L81

You can configure logging to ignore messages from rdflib if you want.

**Comment by tobiasschweizer** [comment]
Ok, got it. Thanks for the fast answer! :-)
