### ISSUE TITLE
Support <bnode:> SPARQL extension in plugins.stores.sparqlstore

### ISSUE THREAD

**Issue by ssssam** [RDFLib/rdflib#511]
Hello!
Right now the 'plugins.stores.sparqlstore' module has a big warning saying "The SPARQL Store does not support blank-nodes!" because they can't be expressed in SPARQL.

Playing with the 4Store triple store, I've found that it does actually let you represent blank nodes in SPARQL by using a special URI form, like this: `<bnode:b000012>`

In the process of getting the rdflib-web module to browse a 4Store triple store using the 'plugins.stores.sparqlstore' module, I hacked support for these blank nodes into the code, and it seems to be working fine. Without this change, rdflib-web can't be used on my data, it raises an exception as soon as it starts due to there being blank nodes in the data.

I noticed that the sparqlstore constructor takes a 'bNodeAsURI' flag which is completely unused, I thought maybe this is what it's meant for so I used that as a way of enabling this functionality.

**Comment by joernhees** [comment]
see #512 for further discussion
