### ISSUE TITLE
Bad relative URI resolution in SPARQL

### ISSUE THREAD

**Issue by pchampin** [RDFLib/rdflib#523]
When using an explicit base URI in SPARQL queries, relative URIs are not correctly resolved.
Instead, the relative URI is simply appended at the end of the base URI.

Example:
```python
import rdflib

g = rdflib.Graph()
r = g.query("SELECT (<../baz> as ?test) WHERE {}",
            base=rdflib.URIRef("http://example.org/foo/bar"))
print r.serialize(format="csv")

# expected result:
#test
#http://example.org/baz

# actual result;
#test
#http://example.org/foo/bar../baz
```

**Comment by joernhees** [comment]
yupp, seems like a bug: http://www.w3.org/TR/sparql11-query/#relIRIs
