### ISSUE TITLE
chained calls to Graph.value

### ISSUE THREAD

**Issue by AlbericC** [RDFLib/rdflib#530]
when navigating a graph, I often use a chain of relations through a recursive function. Maybe its equivalent could be included in the rdflib.Graph methods ?

```python
def chained_values(graph,source,*relations):
    """Follow the path of successive `relations` in `graph`, starting from `source`"""
    if not relations:
        return source
    else:
        r, *rest = relations
        return chained_values(graph, graph.value(source,r) , *rest)
```

this crude code is not robust against multiple paths, though.

**Comment by gromgull** [comment]
You can do: 

```py
graph.objects(source, pred1/pred2/pred3)
```

See http://rdflib.readthedocs.org/en/stable/apidocs/rdflib.html?highlight=path#module-rdflib.paths
and 
https://github.com/RDFLib/rdflib/blob/master/examples/foafpaths.py

If you combine this with resource, you can write quite nice compact code. 

```py
> bob = graph.resource(URIRef('urn:bobs_uri')
> bob[foaf.knows/foaf.name] 
<list of bob's friends names ...>

etc. 
```

**Comment by AlbericC** [comment]
Thank you very much. I admit that I spent a lot of time browsing the docs, yet it was not very productive time... 

I close the issue, thanks again.
