### ISSUE TITLE
BUG/ENH: OrderedDict to preserve [local] ordering

### ISSUE THREAD

**Issue by westurner** [RDFLib/rdflib#538]
Things should be in lists, but for simple local projects, it's really useful to preserve source order.
- [ ] Replace internal/local `dict`s with `collections.OrderedDict` where necessary
  (`HashMap` / `OrderedHashmap`)

References:
- https://wrdrd.com/docs/consulting/knowledge-engineering#rdf-interfaces

**Comment by gromgull** [comment]
We need a bit more detail than "Things" - Where are you thinking?

**Comment by westurner** [comment]
from "/knowledge-engineering#rdf-interfaces

> rdflib is not order-preserving at this time, because internally Graphs are represented as dict and not yet collections.OrderedDict (for which there is a now C-implementation in the Python 3.5 standard library); so output may not be in the same sequence as input (or a rdflib.store.Store, even) even when there are no changes made to the graph.
> It would be preferable to maintain the input source order (though, especially for large distributed queries which merge triples into one context, sorted / source order is not a good assumption to make).

* rdf:List are ordered.
* rdf:List with Turtle / N3:
```turtle

# the data in these lists are ordered according to spec
# but the output order is non-deterministic
# (e.g. not according to source-order, according to dict.keys() somewhere, presumably
#   (e.g. actually according to PYTHONHASHSEED and PYTHONHASHRANDOMIZE))
<#thing1> a rdfs:Resource;
    :attr [ "uno"@es, "one"@en ] ;
    :another-attr [ "three"@en, "four" ];
    :yaattr "yet another attr"@en;
    .
```




> "RDFS does not require that there be only one first element of a list-like structure, or even that a list-like structure have a first element." --  http://www.w3.org/TR/rdf-schema/#ch_list

```turtle
<#rdf-list-predicates> rdf:object [ rdf:first, rdf:rest, rdf:nil ] ;
```


``rdf:List`` with JSON-LD \@context:

* http://www.w3.org/TR/json-ld/#lists-and-sets

Example:

```javascript
{
"@context": {
  "attr": {
    "@container": "@list"
  }
},
"@graph": [
 {"@id": "#thing1",
  "@type": "http://schema.org/Thing",
  "attr": ['one', 'two'],
  "another-attr": {
    "@list": ['three', 'four'],
  },
  "yaattr": "yet another attr",
]}
```

So, when I read these in with rdflib, I may get back:

```python
>>> import itertools
>>> attrs = ['attr', 'another-attr', 'yaattr']
>>> possible_dict_key_orderings = list(itertools.product(attrs, attrs, attrs))

>>> from pprint import pprint
>>> pprint(possible_dict_key_orderings)
[('attr', 'attr', 'attr'),
 ('attr', 'attr', 'another-attr'),
 ('attr', 'attr', 'yaattr'),
 ('attr', 'another-attr', 'attr'),
 ('attr', 'another-attr', 'another-attr'),
 ('attr', 'another-attr', 'yaattr'),
 ('attr', 'yaattr', 'attr'),
 ('attr', 'yaattr', 'another-attr'),
 ('attr', 'yaattr', 'yaattr'),
 ('another-attr', 'attr', 'attr'),
 ('another-attr', 'attr', 'another-attr'),
 ('another-attr', 'attr', 'yaattr'),
 ('another-attr', 'another-attr', 'attr'),
 ('another-attr', 'another-attr', 'another-attr'),
 ('another-attr', 'another-attr', 'yaattr'),
 ('another-attr', 'yaattr', 'attr'),
 ('another-attr', 'yaattr', 'another-attr'),
 ('another-attr', 'yaattr', 'yaattr'),
 ('yaattr', 'attr', 'attr'),
 ('yaattr', 'attr', 'another-attr'),
 ('yaattr', 'attr', 'yaattr'),
 ('yaattr', 'another-attr', 'attr'),
 ('yaattr', 'another-attr', 'another-attr'),
 ('yaattr', 'another-attr', 'yaattr'),
 ('yaattr', 'yaattr', 'attr'),
 ('yaattr', 'yaattr', 'another-attr'),
 ('yaattr', 'yaattr', 'yaattr')]
```

Whereas if the local Store was ordered, and rdflib parser generated ``collections.OrderedDicts``,
the output attribute order would be the same as the source order (plus concatenation, or other proejction artificats):

```
minimum_keyset = ['attr', 'another-attr', 'yaattr']
```

**Comment by joernhees** [comment]
It's true that rdflib's stores (and probably some parsers and serializers) are in general not preserving the insert order of triples.

The reason for this is that we're talking about graphs composed of `(s, p, o)` triples. As the data-model doesn't have a field for `n-th triple`, it would be weird to require the underlying stores to invent one. Also relying on that order would be highly confusing (if not wrong) and inconsistent for example with SPARQL where there are no guarantees about the order either.

So unless you really have a convincing use-case i guess the priority of this is quite low.

**Comment by westurner** [comment]
I suppose one different way to look at it is that if the output order is not the same as the source order, there is additive noise -- which may or may not be necessary.

> So unless you really have a convincing use-case i guess the priority of this is quite low.

| https://github.com/RDFLib/rdflib/blob/master/rdflib/store.py
| https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/memory.py#L24

Is there a need for a performance justification / parametrization?
TBH, I'm inclined to backport

* [ ] ``dict,{} --> collections.OrderedDict``
* IOMemoryOrdered, OrderedIOMemory
* os.environ[RDFLIBORDEREDDICT]

**Comment by westurner** [comment]
``collections.OrderedDict``:


* https://docs.python.org/2/library/collections.html#collections.OrderedDict
* https://docs.python.org/3/library/collections.html#collections.OrderedDict
* https://hg.python.org/cpython/file/tip/Lib/collections/__init__.py #OrderedDict

.

* Python 3.5+ C OrderedDict: https://bugs.python.org/issue16991
* https://docs.python.org/3.5/library/collections.html#collections.OrderedDict
  * https://hg.python.org/cpython/file/tip/Include/odictobject.h
  * https://hg.python.org/cpython/file/tip/Objects/odictobject.c

**Comment by westurner** [comment]
Python 3.6+ dicts are ordered; which should solve this issue for Python 3.6+.

**Comment by koo5** [comment]
python 3.6 or 3.7 didnt remove the randomness, so i wrote a simplistic Store that works for me:
https://github.com/koo5/univar/blob/eb016be73e937e26c004f5175bbe867d086d00f9/pyin/ordered_rdflib_store.py

**Comment by gjhiggins** [comment]
Timed out. koo5's simplistic Ordered Store noted, added to in-progress Cookbook.
