### ISSUE TITLE
ENH: RDF Interfaces, RDF-Ext API

### ISSUE THREAD

**Issue by westurner** [RDFLib/rdflib#539]
RDF Interfaces
----------------------------
| Standard: http://www.w3.org/TR/rdf-interfaces/
| Docs: http://www.w3.org/TR/rdf-interfaces/#high-level-api

RDF Interfaces is an open source standard
for RDF APIs (e.g. as implemented by RDF libraries
and `triplestores`.

* ``createBlankNode`` --> ``BlankNode``
* ``createNamedNode`` --> ``NamedNode``
* ``createLiteral`` --> ``Literal``
* ``createTriple`` --> ``Triple``
  (``RDFNode`` s, ``RDFNode`` p, ``RDFNode``, o)
* ``createGraph`` --> ``[]Triple``
* ``createAction`` --> ``TripleAction`` (``TripleFilter``, ``TripleCallback``)
* ``createProfile`` --> ``Profile``
* ``createTermMap`` --> ``TermMap``
* ``createPrefixMap`` --> ``PrefixMap``

Implementations of RDF Interfaces:

* Javascript and/or Node.js implementations of RDF Interfaces:

  http://www.w3.org/community/rdfjs/wiki/Comparison_of_RDFJS_libraries

  + https://github.com/Acubed/node-rdf
  + https://github.com/antoniogarrote/rdfstore-js
  + https://github.com/bergos/rdf-ext

* [ ] **rdflib (python) mappings to RDF Interfaces:**

  + ``BlankNode`` -> ``rdflib.term.BNode``
  + ``NamedNode`` -> ``rdflib.term.URIRef``, ``rdflib.term.Variable`` ? TODO
  + ``Literal`` -> ``rdflib.term.Literal``
  + ``Triple`` ->  ``tuple()``
  + ``Graph`` -> ``rdflib.graph.Graph``,
    ``rdflib.graph.ConjunctiveGraph``,
    ``rdflib.graph.QuotedGraph``, ``list()``
  + ``Action`` -> _____ TODO
  + ``TripleFilter`` / ``TripleCallback`` ->
    ``rdflib.store.TripleAddedEvent`,
    ``rdflib.store.TripleRemovedEvent``

  + https://rdflib.readthedocs.org/en/latest/apidocs/rdflib.html#rdflib.term.Node
  + ``Profile`` -> ______ TODO
  + ``TermMap`` ->  ____ TODO
  + ``PrefixMap`` -> ``rdflib.namespace.NamespaceManager``
    https://rdflib.readthedocs.org/en/latest/apidocs/rdflib.html#rdflib.namespace.NamespaceManager

Adapted from https://wrdrd.com/docs/consulting/knowledge-engineering#rdf-interfaces

**Comment by gromgull** [comment]
I can haz some prose?

**Comment by niklasl** [comment]
RDF Interfaces is not a standard. It is a WG Note, which explicitly states, in the beginning of the document, that it is incomplete.

> This document is not finished.

And:

> A number of design issues have not been completely resolved. Developers wishing to implement this API should be aware of incomplete nature of the specification.

For instance, there are names in the spec which do not correspond to names for concepts in RDF 1.1 (like "nominalValue"), and ideas which have been further developed into specs (e.g. the notion of Profiles in this Note, to be compared with standardized JSON-LD Contexts).

(I have cautioned implementers of that Note of this fact before.) *If* the current RDFJS cooperation effort yields a stable and usable API, it might be valuable to have an implementation in Python. RDFLib might provide an implementation for that when that happens.

(Note that I think what RDF Interfaces attempted to to was very valuable, only that it is not complete. I fear that claiming that it is might cause confusion and impede effective interoperability (if interfaces do not conveniently support existing practices).)

**Comment by westurner** [comment]
So, routes forward for easy porting/**compatability** with whichever version of RDF Interfaces and RDF-Ext are finalized (or mostly-otherwise implemented):

* rdflib core feature branch: feature/rdf_interfaces
* " package (w/ version pinning?): rdflib-rdfinterfaces, rdflib-rdfi, rdflib-rdf-interfaces

```python
rdflib.<??>.{ #RDF-Interfaces}
rdflib.<??>.{ #RDF-Ext }

rdflib.rdfi.TripleCallback
```

**Comment by westurner** [comment]
RDF Ext

> Source: https://github.com/rdf-ext/rdf-ext
> Standard: **https://bergos.github.io/rdf-ext-spec/**

.. RDF-Ext extends RDF Interfaces

**Comment by gromgull** [comment]
Having taken part in defining "standard api layers" for RDF before - I am not entirely convinced that this is a useful exercise :) 

The beauty of RDFLib is that it allow more pythonic and powerful traversal and manipulation of RDF graphs, which means the API must necessarily be different. 

That being said, if this thing becomes a W3C standard we would welcome a PR that adds a compatibility layer in RDFLib!

Until then I will close :)

**Comment by westurner** [comment]
* RDFJS Interface specification:
  - https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md
  - streams
  - terminology
  - ease of porting
