### ISSUE TITLE
Iterating over resource.Resource.seq() throws TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Jeroen537** [RDFLib/rdflib#541]
Hi,

experimenting with the rdflib.resource.Resource class, I came upon what I think is an issue with Resource.seq(). This call returns an object of generator type, but iterating over that object gives an exception in some cases. It seems that a call to Resource.seq() can result in None, rather than a in generator that does not yield anything, which is what I would expect.

Is there an issue here, or do I misunderstand?

Example code follows (python 3.5, rdflib 4.2.1):

```python
from rdflib import Graph

g = Graph()

g.parse(data="""
<rdf:RDF
  xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'
  xmlns:vCard='http://www.w3.org/2001/vcard-rdf/3.0#'
   >

  <rdf:Description rdf:about="http://somewhere/JohnSmith/">
    <vCard:FN>John Smith</vCard:FN>
    <vCard:N rdf:parseType="Resource">
    <vCard:Family>Smith</vCard:Family>
    <vCard:Given>John</vCard:Given>
    </vCard:N>
  </rdf:Description>

  <rdf:Description rdf:about="http://somewhere/RebeccaSmith/">
    <vCard:FN>Becky Smith</vCard:FN>
    <vCard:N rdf:parseType="Resource">
    <vCard:Family>Smith</vCard:Family>
    <vCard:Given>Rebecca</vCard:Given>
    </vCard:N>
  </rdf:Description>

  <rdf:Description rdf:about="http://somewhere/SarahJones/">
    <vCard:FN>Sarah Jones</vCard:FN>
    <vCard:N rdf:parseType="Resource">
    <vCard:Family>Jones</vCard:Family>
    <vCard:Given>Sarah</vCard:Given>
    </vCard:N>
  </rdf:Description>

  <rdf:Description rdf:about="http://somewhere/MattJones/">
    <vCard:FN>Matt Jones</vCard:FN>
    <vCard:N
    vCard:Family="Jones"
    vCard:Given="Matthew"/>
  </rdf:Description>

</rdf:RDF>
""")

r = g.resource('http://somewhere/MattJones/')

print(r.identifier)
# prints "http://somewhere/MattJones/"

s = r.seq()

print(type(s))
# prints "<class 'generator'>"

for i in s:
    print(i)
# gives "TypeError: 'NoneType' object is not iterable"
```

**Comment by joernhees** [comment]
I think this is mostly an inconsistency between [`Graph.seq`](https://github.com/RDFLib/rdflib/blob/master/rdflib/graph.py#L888) and [`Resource.seq`](https://github.com/RDFLib/rdflib/blob/master/rdflib/resource.py#L426) via [`Resource._resources`](https://github.com/RDFLib/rdflib/blob/master/rdflib/resource.py#L440)...

**Comment by gromgull** [comment]
`seq` is a very specific method to deal with RDF Containers using the `Seq` class: http://www.w3.org/TR/REC-rdf-syntax/#section-Syntax-list-elements

The method returns `None` if the given resource doesn't have the correct type. 

If it does, it constructs a `Seq` object https://github.com/RDFLib/rdflib/blob/master/rdflib/graph.py#L1698 
which in turn is iterable.

**Comment by gromgull** [comment]
`seq` is a very specific method to deal with RDF Containers using the `Seq` class: http://www.w3.org/TR/REC-rdf-syntax/#section-Syntax-list-elements

The method returns `None` if the given resource doesn't have the correct type. 

If it does, it constructs a `Seq` object https://github.com/RDFLib/rdflib/blob/master/rdflib/graph.py#L1698 
which in turn is iterable. 

Your data has to Seq typed resources, so None is returned!

**Comment by Jeroen537** [comment]
OK, I see now that I misread the docs. Thanks for pointing out.

Jeroen.
