### ISSUE TITLE
Consistency Namespace vs. ClosedNamespace

### ISSUE THREAD

**Issue by mthag** [RDFLib/rdflib#542]
As I understand rdflib.Namespace and ClosedNamespace, they are both meant as auxiliaries to simplify the creation of URIRefs in Python code, e.g. `RDF.type` or `OWL.Class`. In addition, ClosedNamespace provides an additional vocabulary check, e.g., `RDF.spam` will raise an exception.

However, sometimes other uses of Namespace/ClosedNamespace can be useful, e.g., string comparison. At this stage, it is quite inconvenient that Namespace is derived from unicode, whereas ClosedNamespace is derived from the standard object, and the actual namespace string is an instance attribute (uri). In the interest of consistency, I propose that ClosedNamespace should also be derived from unicode (or even from Namespace).

Regards

**Comment by joernhees** [comment]
can you give us a use-case where you can't just compare `str(Namespace(...))` with `str(ClosedNamespace(...))`?

**Comment by gromgull** [comment]
I totally agree that it's weird that they derive from different things. It also looks trivial to fix. I've tried - let me see if Travis agrees :)

**Comment by niklasl** [comment]
Also totally agree, thanks for addressing this! :+1:

**Comment by joernhees** [comment]
the change mentioned in #551 is backwards incompatible and will be moved to rdflib 5.0.0 .
