### ISSUE TITLE
Windows, Python 3.4 error: "unable to import bsddb/bsddb3, store is unusable"

### ISSUE THREAD

**Issue by ikarth** [RDFLib/rdflib#544]
When using RDFLib under Windows 7 x64, Python 3.4 x64, any of my attempts to use a Sleepycat for persistence results in an error with the bsddb library:

        g = rdflib.Graph(store='Sleepycat')
    File "[...]\pyenv\lib\site-packages\rdflib\graph.py", line 312, in __init__
        self.__store = store = plugin.get(store, Store)()
    File "[...]\pyenv\lib\site-packages\rdflib\plugins\sleepycat.py", line 52, in __init__
        "Unable to import bsddb/bsddb3, store is unusable.")
    ImportError: Unable to import bsddb/bsddb3, store is unusable.

There seems to be some issues with bsddb3 and Windows, as ```pip install bsddb3``` also fails.

**Comment by gromgull** [comment]
You are right - this is a bsddb issue, and nothing rdflib can do to fix it. 

I've had some success with using leveldb bindings for persistence in the past, maybe that is easier on windows? 

https://github.com/RDFLib/rdflib-leveldb

**Comment by pbloem** [comment]
This error is what you get if BerkeleyDB is not installed. The docs don't make this very clear, but you need to install BerkelyDB separately, and then install the bsddb3 package manually before you can use the Sleepycat store.

Here's what worked for me on macos:
```brew install berkeley-db@4
BERKELEYDB_DIR=$(brew --prefix berkeley-db@4) pip install bsddb3
```
source: https://stackoverflow.com/questions/62457435/unable-to-install-bsddb3-python-package-on-macos-catalina-10-15-4
