### ISSUE TITLE
Selecting nothing returns one row!

### ISSUE THREAD

**Issue by gromgull** [RDFLib/rdflib#554]
```py
>>> g = rdflib.Graph()
>>> list(g.query('select ?whatever { }'))
[(None,)]
```

probably because of: https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/evaluate.py#L37-L39

**Comment by joernhees** [comment]
i tried this with
```python
        res = ctx.solution()
        if res:
            yield res
        return
```
but this causes a lot of other tests to fail...

**Comment by joernhees** [comment]
@gromgull could you review #592 ... the tests pass, but i'm not sure this doesn't cause other problems...
