### ISSUE TITLE
How to skip not valid uri?

### ISSUE THREAD

**Issue by cryptid11** [RDFLib/rdflib#558]
When it says 

```
Exception: " " does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?
```

Is there a way to automatically skip them and have an output?

**Comment by gromgull** [comment]
No: 

https://github.com/RDFLib/rdflib/blob/master/rdflib/term.py#L229-L230

Then you would not be able to parse your output again. 

I guess you could subclass URIRef, and write your own .n3 method that skips the check/exception if you are desperate.
