### ISSUE TITLE
Turtle serializer: @base directive isn't added

### ISSUE THREAD

**Issue by danmichaelo** [RDFLib/rdflib#559]
When doing `graph.serialize(stream, base='...')`, the `@base` directive isn't added. 

I found a mention of this in https://github.com/RDFLib/rdflib/issues/248#issuecomment-14715274 by @gromgull :

> I left it without @base directive now - this way you can quickly and easily 'rebase' some triples.

but I find this slightly counterintuitive.

**Comment by lrowe** [comment]
Neither is xml:base added when serializing as xml:

```python
>>> g = rdflib.Graph()
>>> g.add((rdflib.URIRef('http://example.com/foo'), rdflib.URIRef('http://example.com/term'), rdflib.URIRef('http://example.com/bar')))
>>> print(g.serialize(format='xml', base='http://example.com').decode('utf-8'))
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
   xmlns:ns1="http://example.com/"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>
  <rdf:Description rdf:about="/foo">
    <ns1:term rdf:resource="/bar"/>
  </rdf:Description>
</rdf:RDF>

```

**Comment by wikier** [comment]
any update on this?

**Comment by chrysn** [comment]
i do see use cases where having `@base ` would be good (for readability and compactness), but there are use cases when i very much prefer it not to be explicit, namely all situations in which statements are created by reasoning about local files and then exported in a `http://` and not a `file://` context.

if this issue does get fixed, i suggest that `@base` only gets added to the turtle serialization if an `explicit_base=True` argument is present.

**Comment by bhavye9499** [comment]
Hi...Can I work this issue? It seems interesting to me. I would love to communicate with the maintainers regarding the same.

**Comment by white-gecko** [comment]
If there are no objections to adding this feature, maybe as @chrysn suggests, you are welcome. We are happy about any pull-request helping us to fix bugs. We will have to see in which milestone it will be released.

**Comment by achaudhary997** [comment]
This issue seems to have been fixed. rdflib version 5.0
```
>>> from rdflib import graph
>>> g = rdflib.Graph()
>>> g.add((rdflib.URIRef('http://example.com/foo'), rdflib.URIRef('http://example.com/term'), rdflib.URIRef('http://example.com/bar')))
>>> print(g.serialize(format='ttl', base='http://example.com').decode('utf-8'))
@base <http://example.com> .
@prefix ns1: <http://example.com/> .

</foo> ns2:term ns2:bar .
```

**Comment by gjhiggins** [comment]
As observed by achaudhary997, no longer an issue
