### ISSUE TITLE
Turtle serializer: roundtrip error with prefix relative to base

### ISSUE THREAD

**Issue by danmichaelo** [RDFLib/rdflib#560]
Given the following data:

``` turtle
@base <http://data.me/> .
@prefix me: <onto#> .

<entity/1> me:acronym "ABC" .
```

When doing:

```
g = Graph()
g.load(data, format='turtle')
g.serialize(format='turtle', base='http://data.me/')
```

I get:

``` turtle
@prefix me: <http://data.me/onto#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<entity/1> ns1:acronym "ABC" .
```

so the `me` prefix is expanded to `http://data.me/onto#` upon loading, which is good, but not contracted again upon serializing. Also, note that the new `ns1` prefix is not included in the prefix list. 

Here's a ipython notebook with some variations over the same issue:

https://gist.github.com/danmichaelo/ca90e9a88297ecb9af16

**Comment by nicholascar** [comment]
Testing this out against current master release, 5.0.0-dev, I use this code:

```python
from rdflib import Graph

d = """
    @base <http://data.me/> .
    @prefix me: <onto#> .
    
    <entity/1> me:acronym "ABC" .
"""

g = Graph()
g.parse(data=d, format='turtle')

print(g.serialize(format='turtle').decode('utf-8'))
```

and I get:

```turtle
@prefix me: <http://data.me/onto#> .

<http://data.me/entity/1> me:acronym "ABC" .
```

If I then specify a base:

```python
print(g.serialize(format='turtle', base='http://data.me/').decode('utf-8'))
```

I get this:

```turtle
@prefix me: <http://data.me/onto#> .

<entity/1> ns1:acronym "ABC" .
```

So I'm satisfied the issues raised here are addressed now (it's been 5 yeas after all!) and will close.

**Comment by white-gecko** [comment]
I think a problem is, that the last serialization does not include a prefix definition of `ns1:`

```
@prefix me: <http://data.me/onto#> .

<entity/1> ns1:acronym "ABC" .
```
