### ISSUE TITLE
html5lib on python3

### ISSUE THREAD

**Issue by koenedaele** [RDFLib/rdflib#589]
When using the py3 versions of RDFlib, HTML5lib has to be installed manually. With the the py2 versions it's already there because it's included in setup.py. The py3 version adds it to tests_require, not to install_requires.

**Comment by gromgull** [comment]
probably fixed in 3032bff63dccabadfdb780fbc7644d2bd3d6eb4e

**Comment by joernhees** [comment]
see #671
