### ISSUE TITLE
closednamespace inheritance fix on 5.0.0-dev

### ISSUE THREAD

**Issue by joernhees** [RDFLib/rdflib#596]
the fix for #542 in #551 was backwards incompatible and thus not fit for the patch release 4.2.2 and reverted in #595

this issue is a reminder to either replay bccc76132a7ca19cfa979026e2d5f9ecd8ca6dcf and ae1f6397fe47be7bd6912dae8b08c4007eb9d2ac on top of 5.0.0-dev or maybe drop the unicode base-class for `Namespace` altogether...

@gromgull any preference?

**Comment by gromgull** [comment]
I would drop unicode for namespace, I cannot really see any use-cases why it is useful that it's a subclass at all? 

Then let `ClosedNamespace` inherit from `Namespace`

**Comment by niklasl** [comment]
:+1: Totally agree.

**Comment by joernhees** [comment]
please have a look at #597

**Comment by kernc** [comment]
>  I cannot really see any use-cases why it is useful that it's a subclass at all?

How does one filter for "properties" from `DCTERMS` namespace if not by:

```py
for p, o in g.predicate_objects(s):
    if p.startswith(DCTERMS):
        ...
```
