### ISSUE TITLE
Error parsing the RDF file: No plugin registered for

### ISSUE THREAD

**Issue by 92Barona** [RDFLib/rdflib#602]
Hi,

I'm trying to do some harvests in my localhost Ckan from some RDF data, and I'm using the plugin Dcat that works with RDFlib, 

The problem is that, when I try to harvest from Urls like 

http://datos.gob.es/sites/default/files/catalogo.rdf 
or 
http://gobiernoabierto.valencia.es/wp-content/themes/viavansi-ogov/proxyFile.php?url=http://gobiernoabierto.valencia.es/es/catalogo.rdf, 

I get this errors:
 
"Error parsing the RDF file: No plugin registered for (text/xml, <class 'rdflib.parser.Parser'>)" , 
"Error parsing the RDF file: No plugin registered for (text/rdf, <class 'rdflib.parser.Parser'>)",
"Error parsing the RDF file: No plugin registered for (application/octet-stream, <class 'rdflib.parser.Parser'>)"
...

How can i add plugins to parser these data? Is it possible?

Best regards,
Paco.

**Comment by joernhees** [comment]
how do you try to load them?

I guess the server is returning some non-standard mimetype, so you might have to define the format manually:

```g = Graph().parse('http://datos.gob.es/sites/default/files/catalogo.rdf', format='xml')```

btw: the `catalogo.rdf` contains invalid URIs (they contain spaces)...

feel free to reopen if you have more questions

**Comment by 92Barona** [comment]
Hi Jörn, Thanks for answering,

I installed the plugin DCAT to do harvesting of some RDF data, so I load
the source by the DCAT plugin.

I define the source, and do the harvest run.

Where I define this format? Do I have to change some document .py?

I'm sorry, but I'm so lost in python.
Thanks for your help,
Regards,
Paco.

2016-02-29 16:27 GMT+01:00 Jörn Hees <notifications@github.com>:
