### ISSUE TITLE
possible bug in SPARQL subqueries

### ISSUE THREAD

**Issue by pfps** [RDFLib/rdflib#607]
I think that SPARQL subqueries are not being correctly handled.  It appears that the wrong variables are being projected from the subqueries and as well that the wrong variables end up being bound at the top level.  

Here is a test file that shows the behaviour

```
query = """SELECT ?here ?there WHERE { ?here http://www.w3.org/ns/sh#p ?there }"""
print "\nDUMP property"
for row in testgraph.query(query): 
  print row

print "\nTwo chained triples"
query = """SELECT ?here ?there ?elsewhere
WHERE { ?here  http://www.w3.org/ns/sh#p ?there .
        ?there http://www.w3.org/ns/sh#p ?elsewhere . }"""
for row in testgraph.query(query): print row

print "\nSubquery"
query = """SELECT *
WHERE { ?here  http://www.w3.org/ns/sh#p ?there .
        { SELECT ?there
          WHERE { ?there http://www.w3.org/ns/sh#p ?elsewhere . } } } """
for row in testgraph.query(query): print row

print "\nSubquery"
query = """SELECT ?here ?there
WHERE { ?here  http://www.w3.org/ns/sh#p ?there .
        { SELECT ?there
          WHERE { ?there http://www.w3.org/ns/sh#p ?elsewhere . } } } """
for row in testgraph.query(query): print row

print "\nSubquery with variable renaming and disconnected variables"
query = """SELECT ?here ?there
WHERE { ?here  http://www.w3.org/ns/sh#p ?there .
        { SELECT (?here AS ?there)
          WHERE { ?here http://www.w3.org/ns/sh#p ?there . } } } """
for row in testgraph.query(query): print row
```
and the output on a very small graph
```
DUMP property
(rdflib.term.URIRef(u'http://www.w3.org/ns/sh#a'), rdflib.term.URIRef(u'http://www.w3.org/ns/sh#b'))
(rdflib.term.URIRef(u'http://www.w3.org/ns/sh#x'), rdflib.term.URIRef(u'http://www.w3.org/ns/sh#y'))
(rdflib.term.URIRef(u'http://www.w3.org/ns/sh#b'), rdflib.term.URIRef(u'http://www.w3.org/ns/sh#c'))

Two chained triples
(rdflib.term.URIRef(u'http://www.w3.org/ns/sh#a'), rdflib.term.URIRef(u'http://www.w3.org/ns/sh#b'), rdflib.term.URIRef(u'http://www.w3.org/ns/sh#c'))

Subquery
(rdflib.term.URIRef(u'http://www.w3.org/ns/sh#b'), None)

Subquery
(None, rdflib.term.URIRef(u'http://www.w3.org/ns/sh#b'))

Subquery with variable renaming and disconnected variables
(None, rdflib.term.URIRef(u'http://www.w3.org/ns/sh#b'))
(None, rdflib.term.URIRef(u'http://www.w3.org/ns/sh#y'))
(None, rdflib.term.URIRef(u'http://www.w3.org/ns/sh#c'))
```
I believe that the each of these should have a single solution, namely a projection of <a,b,c>.

**Comment by joernhees** [comment]
hmm, i have trouble to reproduce and understand what is actually expected and what is failing...

would be cool if you could write a minimal test case e.g. like https://github.com/RDFLib/rdflib/blob/master/test/test_issue579.py

**Comment by pfps** [comment]
Will do

**Comment by pfps** [comment]
OK, here is a file that OK, here is a file that shows an issue

Hmm.  I keep on getting "Something went really wrong, and we can't process that file", so I guess I'll just have to include it here.

import rdflib
from rdflib import Graph, URIRef, Literal, Namespace

SH = Namespace("http://bug/")

graph = Graph()
graph.bind('sh',SH)
graph.add((SH.a,SH.p,SH.b))
graph.add((SH.b,SH.p,SH.c))
graph.add((SH.x,SH.p,SH.y))

# finding a chain of length three
q1 = """SELECT ?here ?there ?elsewhere
WHERE { ?here  sh:p ?there .
        ?there sh:p ?elsewhere . }"""
r1 = graph.query(q1)
for row in r1 : r1r = row; print row

# also should find *and report* the chain, but doesn't report correctly
q2 = """SELECT ?here ?there ?elsewhere
WHERE { ?here  sh:p ?there .
        { SELECT ?there ?elsewhere WHERE { ?there sh:p ?elsewhere . } } }"""
r2 = graph.query(q2)
for row in r2: r2r = row; print row

# also should find *and report* the chain, and does
q3 = """SELECT ?here ?there ?elsewhere
WHERE { { SELECT ?there ?elsewhere WHERE { ?there sh:p ?elsewhere . } } 
	?here  sh:p ?there . }"""
r3 = graph.query(q3)
for row in r3: r3r = row; print row

assert r1r[0] == r2r[0]
assert r1r[1] == r2r[1]
assert r1r[2] == r2r[2]

assert r3r[0] == r2r[0]
assert r3r[1] == r2r[1]
assert r3r[2] == r2r[2]

**Comment by pfps** [comment]
[bug.txt](https://github.com/RDFLib/rdflib/files/175039/bug.txt)

And now it works!

**Comment by joernhees** [comment]
i took the liberty to edit your comment ... have a look at markdown syntax please (it will take you 2 minutes and make your reports so much more readable)

i made a test to reproduce this in #610

**Comment by pfps** [comment]
Thanks for the editing.  I tried to attach the bug code but it didn't work the first time so I just shoved it in the message, which I guess triggered some markdown proccessing.

I have another report coming.  I'll try to get it formatted better from the beginning.

**Comment by gromgull** [comment]
doh - I added the test twice. Well, if they now BOTH pass we know it worked! :D

**Comment by gromgull** [comment]
total chaos. It worked locally - but I had some uncommitted changes. This will teach me not to do a PR.
