### ISSUE TITLE
Collection constructor is very slow with large lists

### ISSUE THREAD

**Issue by hsolbrig** [RDFLib/rdflib#609]
The collection constructor uses the append method, which iterates to the end of the list for every addition.  This results in a n! performance.  Propose replacing:

```
    for item in seq:
         self.append(item)
```

with:

```
    if seq:
        nxt = self.uri
        for item in seq:
            graph.add((nxt, RDF.first, item))
            nxt2 = BNode()
            graph.add((nxt, RDF.rest, nxt2))
            nxt = nxt2
        graph.add((nxt, RDF.first, RDF.nil))
```

in the constructor

**Comment by joernhees** [comment]
it's O(n^2), but i agree that it's unnecessary... if you make a pull request, i'll accept it.

**Comment by gromgull** [comment]
I went for a fix without the _end caching issues. Now there is a `__iadd__` method that lets you do `my_collection += [ Literal(1), Literal(2) ]` and this will be efficient. Repeat calls to append remain inefficient, but this is safer!
