### ISSUE TITLE
sorting in turtle serializer breaks with datetime

### ISSUE THREAD

**Issue by satra** [RDFLib/rdflib#613]
if one represents a graph like the one below

```
    ex:gen1 a prov:End ;
        prov:time "2016-03-20T18:11:44.996521"^^xsd:dateTime,
            "2012-12-03T21:08:16.686000+00:00"^^xsd:dateTime .
```

the following line:
https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/serializers/turtle.py#L106

raises the following error:

`TypeError: can't compare offset-naive and offset-aware datetimes`

this should do a lexical sort rather than a numeric or datatype sort.

**Comment by satra** [comment]
from a turtle perspective a sort isn't necessary at all.

**Comment by gromgull** [comment]
fixed in https://github.com/RDFLib/rdflib/commit/13ce988925b4dd919c8713f9a890acb8d962370c
