### ISSUE TITLE
first sparql parse is very slow

### ISSUE THREAD

**Issue by drewp** [RDFLib/rdflib#618]
ConjunctiveGraph().query('SELECT ?x WHERE {  }') takes 2.8 sec on my fast box, 18 sec on raspberry pi 3, and 60sec+ on raspberry pi 1. rdflib-4.2.1, pyparsing-2.1.1, python 2.7.10 on linux.

Queries after the first one are fast. This is not a big problem for long-running servers or on fast computers, but a 60 sec wait at startup is pretty rough when you're testing deployments on rpi1 :)

https://bigasterisk.com/post/rdflib-first-parse.txt shows the pyinstrument (statistical profiler) output, revealing a ton of calls to 'streamline' methods. 

Calling pyparsing.ParserElement.enablePackrat() has no effect.

Test code:

```
# import pyparsing; pyparsing.ParserElement.enablePackrat()
from rdflib import ConjunctiveGraph
from pyinstrument import Profiler

graph = ConjunctiveGraph()

def parse():
    graph.query('SELECT ?x WHERE {  }')

#parse()  # turn this on to get a warmup query

profiler = Profiler()
profiler.start()

parse()

profiler.stop()
print(profiler.output_text(unicode=True, color=True))
```

**Comment by joernhees** [comment]
definitely not nice, but i guess the whole thing was never written for performance :-/

**Comment by nicholascar** [comment]
Since this Issue has been sitting here for 4+ years and no one seems to want to do anything about it, I'm going to close this. Consider this a "won't fix" unless someone else puts up their hand to do something about this.
