### ISSUE TITLE
another filter problem

### ISSUE THREAD

**Issue by pfps** [RDFLib/rdflib#619]
Filters in subqueries only appear to work correctly if they in the first subquery.
I put together a several small examples to show the problem.

[Again, uploading problems - I'll put the example in a separate comment.]

**Comment by pfps** [comment]
import rdflib

dataGraph = rdflib.Graph()

print "SINGLE QUERY"
query = """SELECT  ?this  WHERE {  
	VALUES ?this { <http://ex.com/a> "HI" }
	FILTER ( ! isBlank(?this) ) 
}"""
result = dataGraph.query(query)
for row in result : print row
assert len(result) > 0

print "NO FILTER"
query = """
SELECT  ?this
WHERE { 
	{ SELECT ?this WHERE {  
		VALUES ?this { <http://ex.com/a>  "HI"  }
	  } } 
	{ SELECT ?this WHERE {  
		VALUES ?this { <http://ex.com/a> "HI" }
	  } } 
}"""
result = dataGraph.query(query)
for row in result : print row
assert len(result) > 0

print "FILTER in first subquery"
query = """
SELECT  ?this
WHERE { 
	{ SELECT ?this WHERE {  
		VALUES ?this { <http://ex.com/a>  "HI"  }
		FILTER ( isIRI(?this) )
	  } } 
	{ SELECT ?this WHERE {  
		VALUES ?this { <http://ex.com/a> "HI" }
	  } } 
}"""
result = dataGraph.query(query)
for row in result : print row
assert len(result) > 0

print "FILTER in second subquery"
query = """
SELECT  ?this
WHERE { 
	{ SELECT ?this WHERE {  
		VALUES ?this { <http://ex.com/a> "HI" }
	  } } 
	{ SELECT ?this WHERE {  
		VALUES ?this { <http://ex.com/a>  "HI"  }
		FILTER ( isIRI(?this) )
	  } } 
}"""
result = dataGraph.query(query)
for row in result : print row
assert len(result) > 0

**Comment by gromgull** [comment]
Thanks a lot for a very clearly diagnosed problem @pfps !

Fixed in https://github.com/RDFLib/rdflib/commit/acc6ed3e3548a75541607ec753d05d5061028465
