### ISSUE TITLE
Invalid uri characters include | ?

### ISSUE THREAD

**Issue by jimmccusker** [RDFLib/rdflib#620]
I'm doing work with the BTC2014 dataset and the graph http://didactalia.net/comunidad/materialeducativo/recurso/La-teoria-de-la-relatividad-en-ingles/eb95e40e-937f-4447-a68d-5f1a3fbc97ff has the following URI in it:

http://fonts.googleapis.com/css?family=Nunito|Open%20Sans:300,400,600,700&amp;subset=latin

That led me to the _is_valid_uri function and the list of invalid uri chars, which includes `|`. I can't find anything in the URI spec that says this character is disallowed. I think we should review those characters or find a concrete place where they are disallowed and document that in the exception that's returned.

**Comment by joernhees** [comment]
i think rdflib is right in this case...

according to the [URI RFC](https://tools.ietf.org/html/rfc3986#appendix-A) and the [IRI RFC](https://tools.ietf.org/html/rfc3987#section-2.2) no part of a URI/IRI can contain contain a `|` (ASCII hex 7C).

As far as i can see this also holds true for the others in
```
_invalid_uri_chars = '<>" {}|\\^\`'
```
(just double checked them and those seem to be all of the printable ASCII chars which are invalid)

It's possible (and likely) though, that we don't catch all/any ASCII control chars with the mentioned check... maybe that should be added / we should just rely on underlying / third party libs to parse the URIs...

**Comment by joernhees** [comment]
closing this in favor of #625
