### ISSUE TITLE
sparql, group by and count of null values with `optional`

### ISSUE THREAD

**Issue by wrobell** [RDFLib/rdflib#631]
This is based on example from https://www.w3.org/TR/sparql11-query/#optionals.

Consider the two SPARQL queries in the example below.
1. First query returns two rows for Alice - she has two e-mails.
2. First query returns one row for Bob - he has no e-mails and `?mbox` is null.
3. The second query counts number of mailboxes and returns `2` for Alice.
4. The second query also returns `1` for Bob.

Should the 2nd query return `0` for Bob? That would be the case if we implemented this in SQL. Should we expect the same in SPARQL?

```
data = """
@prefix foaf:       <http://xmlns.com/foaf/0.1/> .
@prefix rdf:        <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

_:a  rdf:type        foaf:Person .
_:a  foaf:name       "Alice" .
_:a  foaf:mbox       <mailto:alice@example.com> .
_:a  foaf:mbox       <mailto:alice@work.example> .

_:b  rdf:type        foaf:Person .
_:b  foaf:name       "Bob" .
"""

import rdflib
import io

graph = rdflib.Graph()

f = io.StringIO(data)
graph.parse(f, format='n3')

result = graph.query("""
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?name ?mbox
WHERE  {
    ?x foaf:name  ?name .
    OPTIONAL { ?x  foaf:mbox  ?mbox }
}
""")

result = graph.query("""
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?name (COUNT(?mbox) AS ?count)
WHERE  {
    ?x foaf:name  ?name .
    OPTIONAL { ?x  foaf:mbox  ?mbox }
}
GROUP BY ?name
""")
```

**Comment by gromgull** [comment]
This now works in master!
