### ISSUE TITLE
Missing conversion for xsd:gYear and similar

### ISSUE THREAD

**Issue by white-gecko** [RDFLib/rdflib#635]
RDFlib has no conversion of Literal values to python datatypes for xsd:gYear, xsd:gDay, xsd:gMonth, xsd:gMonthDay and xsd:gYearMonth

I think the relevant part is here:
https://github.com/RDFLib/rdflib/blob/ec93eeddb10b960a943db4a7f2ab664a8f88e049/rdflib/term.py#L1439

**Comment by gromgull** [comment]
It's semi-random what is in and not, but they are not part of SPARQL, so
they are not required.

Also, if I remember correctly, some SPARQL unit tests will make sure you do
NOT understand too many XSD data-types.

We're not opposed to extending the list of supported types, so add what you
need and make a PR!
