### ISSUE TITLE
Cannot install rdflib4.2.1 in windows 10

### ISSUE THREAD

**Issue by pragnadas23** [RDFLib/rdflib#637]
Why I cannot download and install rdflib4.2.1 in windows 10 using:
conda install -c ioos rdflib=4.2.1

I am getting the following error:

C:\Program Files>conda install -c ioos rdflib=4.2.1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
.Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
.Could not connect to https://repo.continuum.io/pkgs/free/win-64/
.Could not connect to https://conda.anaconda.org/ioos/noarch/
Could not connect to https://conda.anaconda.org/ioos/win-64/
...
Solving package specifications: .
Error:  Package missing in current win-64 channels:
- rdflib 4.2.1*

You can search for this package on anaconda.org with

```
anaconda search -t conda rdflib 4.2.1*
```

I checked the proxy, proxy settings are correct. Moreover, I have tried with networks which does not have proxy and firewall. There also, I am getting the same error. Please help, I need to install rdflib urgently in my windows 10 machine

**Comment by gromgull** [comment]
We don't do anything to support conda - please try installing with `pip` - this is the supported way.
