### ISSUE TITLE
Aggregate queries not working

### ISSUE THREAD

**Issue by jimmccusker** [RDFLib/rdflib#645]
The following query does not parse:

```sparql
select ?class (group_concat(?superClass," ") as ?types)
where {
  ?class rdfs:subClassOf ?superClass.
  ?superClass a owl:Class.
} group by ?class limit 100
```

I get the following error:

```
ParseException: Expected "{" (at char 148), (line:6, col:15)
```

This is a valid query that runs successfully at [DBpedia](http://dbpedia.org/sparql).

**Comment by joernhees** [comment]
virtuoso is very lax with its SPARQL parsing... your `group_concat` isn't really standard conform (you need a `; separator=" "` in there): https://www.w3.org/TR/sparql11-query/#rAggregate

closing this, feel free to reopen

**Comment by KonradHoeffner** [comment]
I get this error both with version 5 as installed via pip as well as the current master branch when I leave out the "AS" part.

**Comment by white-gecko** [comment]
As of SPARQL 1.1 this query is not correct, it has to be:

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?class (group_concat(?superClass; separator=" ") as ?types)
where {
  ?class rdfs:subClassOf ?superClass.
  ?superClass a owl:Class.
} group by ?class limit 100
```

Tip: check with [yasgui](https://yasgui.triply.cc/) if a query parses first.
