### ISSUE TITLE
Namespace prefix not used in relative URI

### ISSUE THREAD

**Issue by arnikz** [RDFLib/rdflib#647]
Hi,

I'm using RDFLib version 4.2.1. The following code snippet
<pre>from rdflib import Graph, Literal
from rdflib.namespace import Namespace, RDFS
BASE=Namespace('http://example.com/')

g = Graph()
g.bind('', BASE)
g.add( (BASE.term('customer'), RDFS.label, Literal('Customer', lang='en')) )
g.add( (BASE.term('customer/1'), RDFS.label, Literal('Customer 1', lang='en')) )
print(g.serialize(format='turtle'))</pre>

results in two triples
@prefix : <http://example.com/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:customer rdfs:label "Customer"@en .
<http://example.com/customer/1> rdfs:label "Customer 1"@en .

In the last line I would expect a shorter version with  _:customer/1_ subject. B.t.w. using the _base_ parameter in _serialize()_ does not seem to work (@base missing from namespace). Any suggestions?

**Comment by joernhees** [comment]
this is implied by the xml qname specs... localpart can't contain `/` chars

see https://www.w3.org/2001/tag/doc/qnameids and https://www.w3.org/TR/REC-xml-names/#NT-QName

reopen if i'm wrong

**Comment by jmacura** [comment]
Hello there,

I am replying here, because I am encountering the very same problem now.

E.g.:
```
NS = rdflib.Namespace("http://gis.zcu.cz/tag/")
g = rdflib.Graph()
subj = rdflib.URIRef(NS + "source#Bing")
g.add(subj, rdflib.RDF.type, rdflib.OWL.Class)
g.bind("ns", NS)
g.bind("owl", rdflib.OWL)
g.serialize(format='turtle')
```

URIRefs with "#", "?", " ", """, "'", "=" and other characters does not resolve to prefix+localpart, but will remain in a form of full URI. Even if properly url-encoded.
I was reading through the linked W3C docs but didn't find any answer, if this behaviour is demanded by specs or if it is a RDFLib's bug.
