### ISSUE TITLE
Unstable RDF/XML serialization

### ISSUE THREAD

**Issue by nvitucci** [RDFLib/rdflib#665]
I noticed that the RDF/XML serialization is unstable, possibly yielding different results across several runs. I tried this example:

```
import rdflib

g = rdflib.Graph()
g.parse('http://xmlns.com/foaf/spec/index.rdf', format='xml')
g.serialize('/tmp/foaf1.ttl', format='turtle')
g.serialize('/tmp/foaf1.rdf', format='xml')

g = rdflib.Graph()
g.parse('http://xmlns.com/foaf/spec/index.rdf', format='xml')
g.serialize('/tmp/foaf2.ttl', format='turtle')
g.serialize('/tmp/foaf2.rdf', format='xml')
```

After running this, I ran Linux `diff` on the resulting files:
`diff /tmp/foaf1.ttl /tmp/foaf2.ttl` -> no difference
`diff /tmp/foaf1.rdf /tmp/foaf2.rdf` -> quite different

The same happens with `pretty-xml`. Can the RDF/XML serialization be made stable?

**Comment by joernhees** [comment]
the reason for this is that there is no simple intrinsic order to a graph that we could use for serialization... in theory one could sort all triples (performance impact) before serialization, but think about BNodes and you end up at graph canonicalization (much higher performance impact).

so in general one shouldn't expect RDF serializations to be stable.

i'm torn here, as many times this would easily be possible... (if there are no BNodes for example). Sorted files lead to smaller diffs, better compression etc. However making this only partially stable leads to dangerous assumptions.

**Comment by nvitucci** [comment]
Uhm. So why Turtle serialization appears to be more stable?

**Comment by joernhees** [comment]
probably cause it does some kind of sorting for better readability... one should however not rely on this, as it won't be stable wrt. BNodes.

**Comment by gromgull** [comment]
This is intentional, if you want a stable output I recommend ntriples or nquads and sorting the file yourself. And avoid blank nodes :)
