### ISSUE TITLE
Put html5lib and/or sparqlwrapper in extra_requires

### ISSUE THREAD

**Issue by arthurlogilab** [RDFLib/rdflib#671]
I noticed using the debian package https://packages.debian.org/jessie/python-rdflib with --no-install-recommends that python-pkg-ressources does not find html5lib and sparqlwrapper and thus fails. Are these really required for rdflib to be used. If not they could probably be put in extra_requires (cf docutils example in http://setuptools.readthedocs.io/en/latest/pkg_resources.html?highlight=requires#overview & http://setuptools.readthedocs.io/en/latest/pkg_resources.html?highlight=requires#requirements-parsing)

Starting the same discussion on debian packaging, will add URL here.

**Comment by arthurlogilab** [comment]
cf http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845643

**Comment by chrysn** [comment]
the referenced debian bug has sparked a follow-up in keepalive (https://github.com/RDFLib/sparqlwrapper/pull/79).

what's interesting here is that in python3, html5lib is already only in `tests_require` (and thus even weaker than extras_require). the correct way to declare the dependencies in my opinion is that both sparqlwrapper and html5lib should be in tests_require, and there should be an `extras_require={'sparql': ['SPARQLWrapper'], 'html': ['html5lib']}` ('html' could be split into 'rdfa' and 'microformats' both depending on 'html5lib', but that's probably too fine grained).
