### ISSUE TITLE
Long SPARQL queries need POST instead of GET

### ISSUE THREAD

**Issue by SeguinBe** [RDFLib/rdflib#672]
Hello,

Getting into RDF and this lib is awesome!

So right now, when you instantiate a `SPARQLStore` as backend, it's not possible to perform long queries (like retrieving information about 100 long URIs at the same time), because of the size limitation of GET requests.

Trying something like 
```python
import SPARQLWrapper
graph = Graph('SPARQLUpdateStore', identifier='http://localhost:8890/WGA') 
graph.store.setMethod(SPARQLWrapper.POST)
```
does not work because the HTTP method is reset (with `resetQuery`) before every query.

That make it impossible to be able to perform a query involving an important set of URI :-(

**Comment by joernhees** [comment]
closed in #673
