### ISSUE TITLE
trig export of multiple graphs assigns wrong prefixes to prefixedNames

### ISSUE THREAD

**Issue by engsterhold** [RDFLib/rdflib#679]
It seems, that trig export does not handle prefixes and named graphs very well (or at all). Trying to export a dataset with multiple graphs overwrites already assigned prefixes, produces different prefix assignments, wrong graph prefixes or prefixNames on different runs.

Testcase:
```python
from rdflib import URIRef, Literal,  Graph, Dataset
def trig_export_test():
    graphs = [(URIRef("urn:tg1"),"A"), (URIRef("urn:tg2"), "B")]
    ds = Dataset()
    for i, n in graphs:
        g = Graph(identifier=i)
        a = URIRef("urn:{}#S".format(n))
        b = URIRef("urn:{}#p".format(n))
        c = Literal(chr(0xf23f1))
        d = Literal(chr(0x66))
        e = Literal(chr(0x23f2))
        g.add((a,b,c))
        g.add((a,b,d))
        g.add((a,b,e))
        ds.graph(g)

    for n,k in [ ("json-ld","jsonld"),
                 ("nquads", "nq"), ("trix", "trix"), ("trig", "trig")]:
        ds.serialize("ds.{}".format(k), format=n)

trig_export_test()

```
Can produce the following 

```
@prefix ns1: <urn:> .
@prefix ns2: <urn:B#> .
@prefix pns1: <urn:x-rdflib:> .
@prefix pns2: <urn:A#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

pns1:tg2 {
    pns2:S pns2:p "f",
            "⏲",
            "󲏱" .
}

pns1:tg1 {
    pns2:S pns2:p "f",
            "⏲",
            "󲏱" .
}

{}
```
or
```
@prefix ns1: <urn:x-rdflib:> .
@prefix ns2: <urn:A#> .
@prefix pns1: <urn:> .
@prefix pns2: <urn:B#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

{}

pns1:tg1 {
    pns2:S pns2:p "f",
            "⏲",
            "󲏱" .
}

pns1:tg2 {
    pns2:S pns2:p "f",
            "⏲",
            "󲏱" .
}
```
both are created with the same function

**Comment by jbaublitz** [comment]
I wanted to add that I see this behavior even in the case of parsing a dataset with a single graph in `nquads` format and serializing as `trig` with no special characters. This seems to be an issue serializing named graphs as `trig` even in cases with one named graph in the dataset. I can also verify that the same `nquads` parsing allows proper `nquads` serialization so it does not appear to be a data corruption issue in the `Graph` data structure.

**Comment by gromgull** [comment]
I've fixed the broken trig output, but it remains ugly. 

The underlying issue is #698 - since you do: 
```
g = Graph(identifier=i)
[ ... add data ... ]
ds.graph(g)
```

you end up with a Graph instance with it's own namespace manager. So each subgraph generates it's own independent space of prefix mappings during trig serialisation. 

It's actually much worse than this - these graphs do not share a store. So if you tried to persist the dataset, nothing would work. 

It's our fault, passing a graph instance to `DataSet.graph` should probably raise an exception. 

Change the code to : 

```
g = ds.graph(i)
[... add data ...]
```
 and all is good.
