### ISSUE TITLE
`pip install rdflib` (as per README.md) gets OSError on Mint 18.1

### ISSUE THREAD

**Issue by tombaker** [RDFLib/rdflib#704]
I am setting up a new machine with Linux Mint (serena).  The installation command recommended in README.md, `pip install rdflib`, exits with:
`OSError: [Errno 13]: Permission denied: '/usr/local/lib/python2.7/dist-packages/isodate'`

On forums like Stackoverflow one finds disagreement about whether running `pip` with `sudo` is perfectly fine, or a terrible idea.  One common theme is that such modules should be installed in a virtual environment, but it is unclear whether to follow the advice for `virtualenv`, `pyvenv`, or `venv`.  [`venv`](https://docs.python.org/3.5/library/venv.html) seems to be the current favorite.

If others have this problem too, README.md could perhaps provide some guidance in this regard.

**Comment by gromgull** [comment]
This is sort of basic python packaging stuff. There is no correct answer, and depends on your goal and your workflow. 

On Mint you will need `sudo` to install globally. If that's what you want it is fine. As a  RDFLib user I like having it in any python I start, and I have it install globally. 
On MacOS (with homebrew), you do not need sudo to install globally, and in fact, it is sort of "harmful". 

If you work on a some project, you probably want to have a virtual environment, then you don't need sudo in either case.

**Comment by tombaker** [comment]
Thank you for the advice.  I understand your point, and had previously only installed RDFLib on OSX (with homebrew).  My point was really just that `pip install rdflib` will fail for the very common scenario (installing in Linux).  A sentence acknowledging this and saying that on some systems it may need to be installed with `sudo pip install rdflib`, or in a virtual environment, could help users like me.

**Comment by gromgull** [comment]
I added a note here: https://github.com/RDFLib/rdflib/commit/c01eede224059c13be3a649ea7ea0c0edbdcd16a

**Comment by tombaker** [comment]
On Sun, Jan 29, 2017 at 11:26:11AM -0800, Gunnar Aastrand Grimnes wrote:
> I added a note here: https://github.com/RDFLib/rdflib/commit/c01eede224059c13be3a649ea7ea0c0edbdcd16a

Very good - thank you!  (It also seems like a good idea to drop 
easy_install as an option.)

-- 
Tom Baker <tom@tombaker.org>
