### ISSUE TITLE
make doctest support py2/py3

### ISSUE THREAD

**Issue by gromgull** [RDFLib/rdflib#707]
without using https://github.com/RDFLib/rdflib/blob/master/rdflib/py3compat.py#L62-L74

Some hints here: 
https://dirkjan.ochtman.nl/writing/2014/07/06/single-source-python-23-doctests.html

**Comment by gromgull** [comment]
fixed in https://github.com/RDFLib/rdflib/commit/1d01e1ef7a0b321103cacee4c23838e8988a2a60

**Comment by joernhees** [comment]
(as part of #519)
