### ISSUE TITLE
Remove some/all default prefix bindings

### ISSUE THREAD

**Issue by niklasl** [RDFLib/rdflib#710]
In https://github.com/RDFLib/rdflib/blob/master/rdflib/namespace.py, there are currently some prefixes bound by default in `NamespaceManager`.

At least one of them, `xml`, should be removed, since that isn't an RDF vocabulary at all (but rather an old artifact stemming from RDF being nigh synonymous with RDF/XML in the past). This unnecessarily clutters all serialization output.

The other ones, `rdf`, `rdfs` and `xsd` are more relevant of course. It is still the case that neither `rdfs` nor `xsd` are used in every piece of serialized data though (schema.org comes to mind). And even if `rdf:type` is close to ubiquitous, it doesn't necessarily warrant the prefix being bound by default.

My thought is to remove all but `rdf`, unless anyone can argue for something else. They are relevant, AFAIK, only to serializations (and for relying on implicit bindings in SPARQL queries). In these cases, the source data and/or explicit bindings ought to give enough control over this.

I'll heartily do the removal; I just want to run it by you first. Is there any (conceivable) real usage depending on one of more of these being bound by default? Even if there are, it could be argued that such practice would be obscure, and that in any case, RDFLib 5 can mark a departure from that. Such usage might just as well expect `owl` or `skos` to be bound as well (or `dc`, `foaf`, `schema`...).

Thoughts?

**Comment by joernhees** [comment]
hmm, manually binding them is cumbersome, isn't it?

As long as they're lazily serialized, i'd actually prefer fallbacks to all in http://prefix.cc ;)

**Comment by niklasl** [comment]
Well, it's just a call to: `graph.namespace_manager.bind(pfx, ns)`. Or you could parse e.g. an empty turtle file with prefixes, which causes them to be bound in the namespace manager of the parsing graph.

They're not lazily serialized (at least not consistently). They appear in e.g. all turtle output. I jumped through some hoops to avoid them popping up by default in the json-ld serializer.

And then there is the issue of re-binding: #543. I guess it's not as common, but I think anyone wanting to use `xs` instead of `xsd` is hit by that.

For pretty serialization, it would be a boon to have lots of lazily bound prefixes over the generated ones, that I agree with. But I'd say that's a different feature: to use well-known prefixes over generating the `ns{i}` stuff. For one, it should not override a prefix given in the source, unless explicitly told so. In fact, that's yet another possible feature: providing control over whether to retain or discard prefixes in a source during parse time.

**Comment by gromgull** [comment]
I've also been annoyed by them lately, I use the SPARQLStore, and they are in every generated query for no reason. 

I would vote remove, but could make it so that if they are unbound and some serialised says "make up a prefix for `'http://www.w3.org/2001/XMLSchema#int` it knows to do `xsd` and not `ns0` for maybe ~top20 of the prefix.cc popular list?

**Comment by nicholascar** [comment]
Unused prefixes are removed in 5.0.0.
