### ISSUE TITLE
Any work on new distributed persistant backends?

### ISSUE THREAD

**Issue by mullenba** [RDFLib/rdflib#721]
I really like the rdflib package, but I would like to learn more about large scale solutions.  Are there any projects working with Cassandra or HBase?  Are there any projects with better documentation of the rdflib store package to provide a starting point to kick off a new extension?

**Comment by gjhiggins** [comment]
> Are there any projects working with Cassandra or HBase?
Not that I'm aware of, so it's very unlikely.

> Are there any projects with better documentation of the rdflib store package to provide a starting point to kick off a new extension?
No, but that will be addressed in the upcoming RDFLib documentation overhaul
