### ISSUE TITLE
The N-triple serializer incorrectly encodes URIs and Literals

### ISSUE THREAD

**Issue by RinkeHoekstra** [RDFLib/rdflib#729]
N-triple serializers incorrectly encode URIs and Literals in the object position.

For instance, a URIRef `http://data.socialhistory.org/resource/hisco/DDB1/packmästare` as subject, predicate and object is rendered as:

`<http://data.socialhistory.org/resource/hisco/DDB1/packm\u00E4stare> <http://data.socialhistory.org/resource/hisco/DDB1/packm\u00E4stare> <http://data.socialhistory.org/resource/hisco/DDB1/packm\u00E4stare>`

A literal has the same issue. As of RDFLib v4.2.2 this works fine for NQuads (in 4.2.1 both NQuads and N-Triples incorrectly encoded URIs in the object position). Turtle serialiser works fine in both versions.

To replicate:

```
from rdflib import Dataset, URIRef, Literal

uri = u"http://data.socialhistory.org/resource/hisco/DDB1/packmästare"
literal = u"packmästare"

g = Dataset()

s = URIRef(uri)
p = URIRef(uri)
o = URIRef(uri)
l = Literal(literal)

g.add((s,p,o))
g.add((s,p,l))

with open("encoding-test.nq",'w') as f:
    g.serialize(f, format='nquads')
    
with open("encoding-test.nt",'w') as f:
    g.serialize(f, format='nt')
    
with open("encoding-test.ttl",'w') as f:
    g.serialize(f, format='turtle')
```

**Comment by joernhees** [comment]
as so many issues in RDFLib this is historically grown... we still serialize with the old `7bit` ascii ntriples 1.0 format by default. ntriples 1.1 still allows this: https://www.w3.org/TR/n-triples/#grammar-production-IRIREF (so it's not a bug, but more compatible).

There's also already a [NT1.1Serializer](https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/serializers/nt.py#L36). Still this issue shows, that as mentioned in #400 and #450 we certainly should go forward, make NT1.1 the default and write utf-8 encoded ntriples. It should still however be possible to generate NT1.0 for older systems...

**Comment by gjhiggins** [comment]
Unable to replicate using the provided test.
