### ISSUE TITLE
SPARQL queries being slow because of exhaustive search instead of Join/CTE

### ISSUE THREAD

**Issue by sfkeller** [RDFLib/rdflib#735]
I'm new to rdflib and mapping of SPARQL-to-SQL. We're re-running the well-known Berlin benchmark (adapted version here [1]), starting with 27'886 Triples (scale1000.nt). Now looking at the log of the following simple Query 1:
```
  PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
  PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  SELECT DISTINCT ?product ?label
    WHERE {
      ?product rdfs:label ?label .
      ?product rdf:type <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType2> .
      ?product bsbm:productFeature <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature12> .
      ?product bsbm:productFeature <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature20> .
      ?product bsbm:productPropertyNumeric1 ?value1 .
      FILTER (?value1 > 348)
      }
  ORDER BY ?label
  LIMIT 10
```
.. rdflib obviously generates subsequent queries of about 15'000(!) times in case of scale1000.nt.
This obviously becomes inacceptable slow, compared to native triple stores and Graph databases.

AFAIK it's easy to write a proper SQL query using join, union and ev. recursive CTE which would be much more performant and scalable.

Can someone explain if current behaviour of rdflib is caused by implementation issues (SPARQL-to-SQL-Mapper, OR-Mapper/SQLAlchemy), storage and/or architectural issues - or is this a fundamental issue of mapping SPARQL-to-SQL?

[1] Berlin Benchmark: https://github.com/geometalab/MSE-Database-Seminar-Triple-Stores/
[2] Queries: https://github.com/geometalab/MSE-Database-Seminar-Triple-Stores/blob/master/rdflib/queries.py

**Comment by sfkeller** [comment]
After some investigation I came to the conclusion that this behaviour of the famous rdflib (issueing thousands of queries depending of the data) is due to a serious implementation issue of rdflib. 

Given rdflib generated a standard triple type schema (subject, predicate , object), IMHO Query 1 given above can be translated to SQL using few JOINs.

Pls. don't take this too much as a critique but rather as a misunderstanding of the usage on my side and/or documentation of "Cases not covered by rdflib" or so. It seems that I have to rearrange the BSBM benchmark in any case. bu still, I'd be very grateful if somebody could comment on this rdflib issue (@gromgull ?).

**Comment by gromgull** [comment]
Hi @sfkeller - as you've noticed, RDFLib doesn't make any attempt to do any SPARQL-to-SQL mapping. That is, our SPARQL engine is implemented on top of the RDFLib store interface, where only spo-queries are possible. 

I don't think we claim anything about SPARQL-to-SQL anywhere? Where did you get this from?

It is however _possible_ to provide custom algerbra evaluation points for our query engine, so for instance the rdflib-sqlalchemy project could provide a way to at least join simply BGP patterns into a single query. 

An older RDFLib version had a different query engine, this did not support SPARQL 1.1, and was a bit messy, but did have a SQL mapping to MySQL. This lived on in the layercake fork for a while, but I cannot find a link for it now.

**Comment by sfkeller** [comment]
Many thanks for your explanations. 

These RDFLib related docs mention BSBM explicitly [1] + [2], and on the other hand RDB are mentioned here [3]. Somebody else seems to have had a similar misunderstanding as I had [4].

Actually, I'm a still little bit confused since the queries "worked". It seems, that I should have opened this issue in rdflib-sqlalchemy project, which is my fault. 

[1] http://rdfextras.readthedocs.io/en/latest/store/
[2] https://github.com/RDFLib/rdflib-benchmark/blob/master/bsbm/queries/explore/query10.txt
[3] http://wifo5-03.informatik.uni-mannheim.de/bizer/berlinsparqlbenchmark/
[4] http://stackoverflow.com/questions/41820363/how-can-i-speed-up-sparql-query-from-python-rdflib
