### ISSUE TITLE
Slow parsing

### ISSUE THREAD

**Issue by ciromoraismedeiros** [RDFLib/rdflib#743]
Hi,

I'm running performance tests with complete graphs (containing all possible triples for a given set of resources), but parsing is taking too long. I've found [this similar issue](https://github.com/RDFLib/rdflib/pull/318), but it talks about serialization. In my case, the data is in memory.

This is the function which generates the complete graph. `data` is just a string in turtle format containing the triples.
```
def full_database(n, prefix='%s'):
    data = ''
    for i in range(1,n+1):
        for j in range(1,n+1):
            for k in range(1,n+1):
                data += '<'+(prefix%i) +'> <'+ (prefix%j) +'> <'+ \
                (prefix%k) + '> .\n'
    return data
```
This is the main code, which measures time.
```
if __name__ == '__main__':
    D = Graph()
    size = int(sys.argv[1])
    start = time.time()
    D.parse(data=full_database(size), format="n3")
    end = time.time()
    
    print size, end-start
```
And the results were:
```
size    triples   time
   0          0     0.0100710391998
  10       1000     0.644206047058
  20       8000     5.14649105072
  30      27000    17.3461780548
  40      64000    40.205548048
  50     125000    82.2172880173
  60     216000   139.274574041
  70     343000   218.672528982
  80     512000   326.651834011
  90     729000   462.141964912
```
The amount of triples is `size`^3. 

Is this time normal for this input?

**Comment by joernhees** [comment]
hehe ;)

took me a while, but i guess you found that you actually generated `size**3` triples yourself in the thrice nested loop in your `full_database` function
