### ISSUE TITLE
xsd:gYear and xsd:gYearMonth error

### ISSUE THREAD

**Issue by satra** [RDFLib/rdflib#747]
although support for xsd:gYear was added in #636 it appears to interpret things improperly:
(schema details here: https://www.w3.org/TR/xmlschema-2/#gYear)

```python
Literal('2002', datatype='http://www.w3.org/2001/XMLSchema#gYear')
```
returns:
```python
rdflib.term.Literal('2002-01-01', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#gYear'))
```
and
```python
Literal('2002-01', datatype='http://www.w3.org/2001/XMLSchema#gYearMonth')
```
returns:
```python
rdflib.term.Literal('2002-01-01', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#gYearMonth'))
```

**Comment by reeshabhkumarranjan** [comment]
I would like to work on this issue, seems interesting to me.

**Comment by aucampia** [comment]
@nicholascar just in case you missed it, as there was quite a bit of noise regarding this issue: This PR #1315 fixes this problem.
