### ISSUE TITLE
Parsing large sparql responses leads to lxml error: lxml.etree.XMLSyntaxError: internal error: Huge input lookup

### ISSUE THREAD

**Issue by artreven** [RDFLib/rdflib#749]
When I connect to an external SPARQL store and make a query that returns many results (more than 9.5 MB https://github.com/KimiNewt/pyshark/issues/75) the xmlparser throws the error: "lxml.etree.XMLSyntaxError: internal error: Huge input lookup"

**Comment by gjhiggins** [comment]
Addressed in https://github.com/RDFLib/rdflib/commit/6cb0dabce15a0d5dc81954ecb833e31b47a68e28
