### ISSUE TITLE
Parser exceptions should inherit from rdflib.exceptions.Error

### ISSUE THREAD

**Issue by aparamon** [RDFLib/rdflib#768]
Currently, not all exceptions raised by RDFLib are inherited from rdflib.exceptions.Error, e.g. rdflib.plugins.parsers.pyRdfa.RDFaError is subclassed directly from exceptions.Exception. It is suboptimal as it complicates client code needed for handling parser errors.
All exceptions raised by RDFLib directly should inherit from rdflib.exceptions.Error.

**Comment by gromgull** [comment]
The pyRdfa code is really not well aligned with RDFLib coding standards in many way, and we will move to having it in it's own repo in a future release. (It already has it's own independent releases)

But the point still holds - and there are probably examples outside of the rdfA package.

**Comment by gromgull** [comment]
We've moved RDFa out of core rdflib, so closing this. See https://github.com/RDFLib/rdflib/pull/828
