### ISSUE TITLE
ENH: sniff() method to detect RDFa, Microdata, or JSONLD in (X)HTML

### ISSUE THREAD

**Issue by westurner** [RDFLib/rdflib#770]

**Comment by westurner** [comment]
https://github.com/codelucas/newspaper/issues/448

**Comment by westurner** [comment]
Bikeshedding: sniff() or detect_metadata()?

https://en.wikipedia.org/wiki/Content_sniffing

**Comment by gromgull** [comment]
We've moved RDFa out of core rdflib, so closing this. See https://github.com/RDFLib/rdflib/pull/828

**Comment by westurner** [comment]
How does moving things to plugin close this issue?

There could be a detect/heuristic plugin interface to support this functionality.

**Comment by westurner** [comment]
Extruct is the best tool for accomplishing this, IMHO
https://github.com/scrapinghub/extruct
