### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by tisdall** [RDFLib/rdflib#772]
I'm new to this library so I tried the example in the README:
```
>>> import rdflib
INFO:rdflib:RDFLib Version: 4.2.2
>>> g=rdflib.Graph()
>>> g.load('http://dbpedia.org/resource/Semantic_Web')
>>> 
>>> for s,p,o in g:
...     print s,p,o
... 
http://dbpedia.org/resource/Semantic_Web http://dbpedia.org/ontology/wikiPageExternalLink http://www.w3.org/standards/semanticweb/
http://dbpedia.org/resource/Semantic_Web http://www.w3.org/2002/07/owl#sameAs http://de.dbpedia.org/resource/Semantic_Web
http://dbpedia.org/resource/Nigel_Shadbolt http://dbpedia.org/ontology/field http://dbpedia.org/resource/Semantic_Web
http://dbpedia.org/resource/Semantic_Web http://www.w3.org/2000/01/rdf-schema#label Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

I was able to get it to work by changing `o` to `o.encode('utf-8')`:
```
import rdflib
g=rdflib.Graph()
g.load('http://dbpedia.org/resource/Semantic_Web')

for s,p,o in g:
    print s,p,o.encode('utf-8')
```

**Comment by joernhees** [comment]
hmm, i think this is rather a problem with python not correctly guessing the encoding of your terminal (as it usually would for print)...

- what happens if you just try to print a unicode string? (in python: `print u'äöüß'`)
- what system are you running on?
- in bash:
  - what does `echo $LANG` say?
  - what does `echo $LC_ALL` say?
  - what does `echo $PYTHONIOENCODING` say?
- if you put your code into a `test.py` file and add `# -*- coding: utf-8 -*-` as first line, does it work?

**Comment by tisdall** [comment]
You're probably right...   I'm accessing the interpreter via ssh.

- If I try to paste `print u'äöüß'` is looks like `print u''`.  If I do the `encode` change I mention I see non-ascii characters like "语义网".
- I'm using python 2 on a debian docker instance
- looking at `env` only `LANG=en_CA.UTF-8` is set (of possible encoding/lang settings)
- I get the same error  (well, it changes slightly due to the result order on each execution, sometimes it says `UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 38: ordinal not in range(128)` but it's the same issue)

I also managed to get it to work by using `PYTHONIOENCODING=utf-8 python` but `LC_ALL=en_CA.UTF-8 python` did not work...

I guess this is a non-issue...  I was just hoping to help the next person to run into this issue...
