### ISSUE TITLE
Setting the base IRI of a graph

### ISSUE THREAD

**Issue by noorbakerally** [RDFLib/rdflib#778]
A graph may contain resources having relative IRIs. When this is the case, when the graph is loaded, the absolute IRIs of resources having relative IRIs becomes the location where the graph is on disk concatenate with the relative IRI of the resource. Is it possible to prevent this and set the base IRI using some way so that the absolute IRI become the base IRI concatnate with the relative IRI ?

**Comment by joernhees** [comment]
should work like this:
```python
g = Graph().parse(..., publicID="http://my.base/uri/")
```
