### ISSUE TITLE
Is there any quick way to obtain a Graph object from result of a construct query

### ISSUE THREAD

**Issue by noorbakerally** [RDFLib/rdflib#779]
To obtain the resulting graph from a construct query, do we have to iterate on every triples and add it to a new Graph or is there any quick way to obtain the result directly as a graph ?

**Comment by noorbakerally** [comment]
the answer is on this [page](http://rdfextras.readthedocs.io/en/latest/working_with.html) http://rdfextras.readthedocs.io/en/latest/working_with.html

**Comment by joernhees** [comment]
note that the page is pretty outdated though...
