### ISSUE TITLE
Error parsing N-Triple file using RDFlib

### ISSUE THREAD

**Issue by ReshmaDangol** [RDFLib/rdflib#782]
I am trying the load the triples from a Linked data dump into my local triplestore using RDFlib. 
An example triple in my file:
` <http://SubjectURL> <http://propertyURL>   "Some detail about the subject"@EN .`
Snippet of the code:
`g.parse(path_of_the_file, format="nt")`

Error Message:
`File "/usr/local/lib/python2.7/dist-packages/rdflib/graph.py", line 1039, in parse parser.parse(source, self, **args)
File "/usr/local/lib/python2.7/dist-packages/rdflib/plugins/parsers/nt.py", line 26, in parse
parser.parse(f)
File "/usr/local/lib/python2.7/dist-packages/rdflib/plugins/parsers/ntriples.py", line 142, in parse
raise ParseError("Invalid line: %r" % self.line)
rdflib.plugins.parsers.ntriples.ParseError: Invalid line: u'@EN .'`

Also, I got error same invalid line error for this triple:
`<http://data.archiveshub.ac.uk/id/extent/archbox/60> <http://data.archiveshub.ac.uk/def/archbox>	60.0 . `

**Comment by ReshmaDangol** [comment]
Just found out that the language restriction is case sensitive.

**Comment by joernhees** [comment]
hmm, the first (`"somestring"@EN`) looks like an actual bug in rdflib's ntriples parser: The [N-Triples spec allows for upper-cased lang-tags](https://www.w3.org/TR/n-triples/#grammar-production-LANGTAG), even though i have to say that i'd strongly discourage using `@EN` in favor of `@en` (everyone else does and your and their literals won't match!).

The second part `60.0` is not a bug, but correctly complains as according to [N-Triples spec the literal is always quoted](https://www.w3.org/TR/n-triples/#grammar-production-literal).

**Comment by ReshmaDangol** [comment]
@joernhees Thank you for clarifying. A data dump I am trying to use has such triples with unquoted literal. Could there be any way to tackle this situation? Are there any tools that can "clean" linked datasets?

**Comment by joernhees** [comment]
@ReshmaDangol you can use a turtle parser instead... ntriples is a sub-set of it, but allows for literal abbreviations like `60.0` (without quotes) (`g.parse(..., format='ttl')`). Please notify your data provider of the problem, they're not producing valid ntriples, so maybe they should switch from `.nt` to `.ttl`...
