### ISSUE TITLE
Error while running SPARQL query over an endpoint

### ISSUE THREAD

**Issue by ReshmaDangol** [RDFLib/rdflib#783]
I have encountered a very strange issue. The endpoint I am using is [http://ring.ciard.net/sparql1](http://ring.ciard.net/sparql1).

I am running a very basic query:
`select * where
            {
            ?s ?p ?o .
            }
        Limit 1 offset 12803`

Code:
```
url = "http://ring.ciard.net/sparql1"
query =""" select * where
            {
            ?s ?p ?o .
            }
        Limit 1 offset 12803"""
 
endpoint = SPARQLWrapper(url)
endpoint.setQuery(query)
endpoint.setReturnFormat(JSON)
```

This is the error I get:
```
Traceback (most recent call last):
  File "query_endpoint.py", line 39, in <module> 
    results = endpoint.query().convert()   
  File "/usr/local/lib/python2.7/dist-packages/SPARQLWrapper/Wrapper.py", line 751, in convert
    return self._convertJSON()
  File "/usr/local/lib/python2.7/dist-packages/SPARQLWrapper/Wrapper.py", line 675, in _convertJSON
    return json.loads(self.response.read().decode("utf-8"))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 24 column 1757 (char 2128)
```

Could anyone help me understand and solve this issue?

**Comment by joernhees** [comment]
hmm, while this is actually an issue for https://github.com/RDFLib/SPARQLWrapper, some quick testing tells me that the endpoint you have there doesn't reply with valid json, as it escaped the final `"`:
```
In [20]: t[2120:2135]
Out[20]: 'bases.\\"\n      '
```

Please notify the providers. To maybe update their endpoint. As a quick workaround maybe simply try another result format (or simply don't specify one and let the endpoint decide)?

I'll close this, please re-open in https://github.com/RDFLib/SPARQLWrapper/issues if necessary.
