### ISSUE TITLE
Remove unused prefixes from serialization

### ISSUE THREAD

**Issue by noorbakerally** [RDFLib/rdflib#794]
I have a rdflib.Graph object to which I bind several namespaces. The issue is that when serializing the graph, many of the binded namespaces are not used but are still in the serialized text. I want only the used prefixes to be serialized. How is this possible ?

For example, the graph below is generated by rdflib and many unused prefixes are serialized together:

```
@prefix child: <http://opensensingcity.emse.fr/ldpdfend/paris/d1/catalog/> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix parent: <http://opensensingcity.emse.fr/ldpdfend/paris/d1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

parent:catalog a ldp:BasicContainer,
        ldp:Container,
        ldp:RDFSource ;
    ldp:contains child:datasets ;
    foaf:primaryTopic <https://opendata.paris.fr/api/v2/catalog/exports/ttl> .

<https://opendata.paris.fr/api/v2/catalog/exports/ttl> a dcat:Catalog ;
    dcterms:Language <http://id.loc.gov/vocabulary/iso639-1/en>,
        <http://id.loc.gov/vocabulary/iso639-1/fr> ;
    dcterms:description "Parisdata Catalog" ;
    dcterms:publisher <http://www.opendatasoft.com> ;
    dcterms:title "Parisdata's catalog" ;
    dcat:themeTaxonomy <https://opendata.paris.fr/concept-scheme/themes> ;
    foaf:homepage <https://opendata.paris.fr> .
```

**Comment by joernhees** [comment]
I think atm this is mostly done so that prefixes are listed first and as we might not know which of the bound namespaces is actually used. The current store backend might not give us this informaiton in a cheap way, requiring us to run a full pre-iteration of the data to be serialized.

That said, i'd also like options to drop unused prefixes and maybe even have inline prefix serialization...

**Comment by noorbakerally** [comment]
yes, i agree, it may not be cheap, I haven't look at the source code, but is it not possible to set a boolean the moment a prefix is used and discards prefixes where say boolean is false because in some sense for using the prefix, at some time, an operation must be performed using the prefix object and the IRI, it may be possible to set the boolean during this operation... ?

**Comment by niklasl** [comment]
It would be nice to add some optionals for these scenarios (and or check the graph/dataset size for an automatic feature). Also somewhat related to #710.

**Comment by nicholascar** [comment]
Unused prefixes are removed in 5.0.0.

**Comment by wmelder** [comment]
It appears that the serialization is giving back many common prefixes, although the data in the graph is not using them. From the GH issues I take it that returning a long list of prefixes for graph.namespaces() is intented behaviour.
But I want the serialization to be shorter and in fact now injected a small piece of code in my repo that I now need to copy and paste to another repo. It is ugly and error prone, because it just uses a static list of prefixes. Wouldn't it be nicer if graph.serialize automatically does remove namespaces that aren't used?
```
    def remove_unused_prefixes(self):
        """ Clean up the long list of namespaces rdflib produces.
        """
        context = dict(self.graph.namespaces())
        used_prefixes = ['rdf', 'rdfs', 'sdo', 'skos', 'xml', 'xsd']
        return {p: context[p] for p in used_prefixes}
```
Now I call this before serialization:

```
            context_used = self.remove_unused_prefixes()
            return self.graph.serialize(
                format=return_format,
                context=context_used,
                auto_compact=True
            )
```
Maybe add graph.used_namespaces tot the Class? So that it is possible to choose to only put used namespaces into the context argument?

**Comment by wmelder** [comment]
Now things do seem to work as I want:
```
  return self.graph.serialize(
                format=return_format,
                context=dict(self.graph.namespaces()),
                auto_compact=True
            )
```
this only serializes the namspaces used. Not the long list. I am confused because it worked different yesterday and I have no explanation. I think that the comment and request can be withdrawn then and marked solved.
I am using rdflib 6.1.1, by the way.

**Comment by aucampia** [comment]
@wmelder thanks for the update, please do let us know if you ever see it again, even if you can't reproduce it reliably, and it would be best to open a new issue so we don't loose track of it, can reference this one in there for provenance.

**Comment by wmelder** [comment]
@aucampia Thanks I will have to open a new one, because the behaviour is back. And I think I understand why: because of browser caching and broken VPN connection. The data wasn't refreshed properly, but a cached version was served.

**Comment by nicholascar** [comment]
I really struggle with this issue. With 6.1.1, this code:

```python
from rdflib import Graph

g = Graph()
g.parse(
    data='''
        PREFIX foaf: <http://xmlns.com/foaf/0.1/>
        <a:> a <b:> ;
             foaf:name "Nick" .
        ''',
    format="turtle"
)

print(g.serialize())
```

produces:

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

<a:> a <b:> ;
    foaf:name "Nick" .
```

So where are the unused prefixes there?

@wmelder can you perhaps show the full code you are using that results in data with unused prefixes in it as I'm not seeing it.
