### ISSUE TITLE
jsonld file not loading

### ISSUE THREAD

**Issue by noorbakerally** [RDFLib/rdflib#799]
I have a valid jsonld file at https://data.hikob.com/osc/parking but rdflib is not loading it. Just to check that the jsonld is valid, i also tried converting it to turtle using http://rdfvalidator.mybluemix.net/. My codes are:

```
>>> from rdflib import Graph, plugin
INFO:rdflib:RDFLib Version: 4.2.1
>>> g = Graph().parse("https://data.hikob.com/osc/parking",format="json-ld")
>>> g.serialize()
'<?xml version="1.0" encoding="UTF-8"?>\n<rdf:RDF\n   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n>\n</rdf:RDF>\n'
```

**Comment by niklasl** [comment]
This only affects RDFLib/rdflib-jsonld (and is also reported there as RDFLib/rdflib-jsonld#53), so I'm closing it here. For reference, it is dependent on RDFLib/rdflib#436.
