### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by skyfully** [RDFLib/rdflib#815]
when i use rdflib,i get an error like this “ValueError: malformed node or string: <_ast.Call object at 0x000001A8783DF2B0>” .I have no idea of this ,hope someone can help me 
My code is ：   

import rdflib
g = rdflib.Graph()
result = g.parse("http://www.w3.org/People/Berners-Lee/card")

print("graph has %s statements." % len(g))
# prints graph has 79 statements.

for subj, pred, obj in g:
   if (subj, pred, obj) not in g:
       raise Exception("It better be!")
s = g.serialize(format='n3')

**Comment by nicholascar** [comment]
This error is no longer valid. When I run this code, no error:

```python
import rdflib
g = rdflib.Graph()
result = g.parse("http://www.w3.org/People/Berners-Lee/card")

print("graph has %s statements." % len(g))

for subj, pred, obj in g:
    if (subj, pred, obj) not in g:
        raise Exception("It better be!")
s = g.serialize(format='n3')
```

So I'm closing the Issue.
