### ISSUE TITLE
rdflib.plugins.stores.sparqlstore.SPARQLStore remove returnFormat=XML

### ISSUE THREAD

**Issue by wonkydonky** [RDFLib/rdflib#819]
The class `SPARQLStore` calls this `init` from the `NSSPARQLWrapper` superclass

`super(SPARQLStore, self).__init__(endpoint, returnFormat=XML, **sparqlwrapper_kwargs)`

the problem is that this doesn't allow any other return format other than XML (for example, JSON). The reason is:

- `returnFormat=XML` sets the default returnFormat upstream to XML
- the `query()` functions resets the query setup at every query, using `self.resetQuery()`

so, even if I call `setReturnFormat()` from the base class `SPARQLWrapper`, it has no effect. Results always return as XML. By removing `returnFormat=XML`, I should be allowed to call `SPARQLStore` like this

`SPARQLStore (endpoint='...', returnFormat=JSON`

**Comment by wonkydonky** [comment]
Looks like there is more going on than that. The problem remains though, it's impossible to request any other format than XML.

**Comment by gromgull** [comment]
closing this as we've removed SPARQLWrapper in RDFLib 5.0, see: https://github.com/RDFLib/rdflib/pull/744
