### ISSUE TITLE
from_n3 interprets \[a-f0-7] as a hex

### ISSUE THREAD

**Issue by kefo** [RDFLib/rdflib#838]
When submitting a string to `from_n3` that contains a backslash character that is immediately followed by a, b, c, d, e, f, 0, 1, 2, 3, 4, 5, 6, or 7, instead of the backslash being escaped (\\), the characters are converted to a hex value (or perceived to be a hex value when encoded).

The code is here:

https://github.com/RDFLib/rdflib/blob/master/rdflib/util.py#L182-L185

Line 185 is actually where the problem occurs.  Here it is isolated in the console:

```console
>>> "\b".encode("raw-unicode-escape").decode("unicode-escape")
'\x08'
>>> "\b".encode("raw-unicode-escape")
b'\x08'
>>> 
```
Note that it is the call to `encode("raw-unicode-escape")` that is the culprit.

I'm not sure where to go from here.  This is a bug in `from_n3` but it is also, obviously, something that is, or likely is, incorrect in the Python encoding codec.

The line in question (185) was added back in 2011 by @takluyver: https://github.com/RDFLib/rdflib/commit/3a62086bb08bb7e083fe22778eb2da7b773f451e#diff-b4eb8b008f7771bbbe2a9c3930853fe4

Does anyone here recall what problem was trying to be solved with the introduction of this call to encode and decode the string?

I'm not against submitting a fix, but this is pretty deep in the rdflib stack, the note describes it as a hack, and I want a better understanding of the issues that preceded the 2011 addition.

Thoughts?

**Comment by takluyver** [comment]
If it happens with all those characters, I think you're looking at the wrong line, because:

```
>>> "\\e".encode("raw-unicode-escape").decode("unicode-escape")
'\\e'
```

(Note that `"\\e"` with a double backslash is correct, because the backslash is an escape character in Python string literals - so e.g. `"\b"` is a one character string containing an ASCII backspace).

Although I added the line, the essential functionality was there before - the `.decode("unicode-escape")` converts a sequence like `\u20ac` into `€`. I'm not sure if I ever knew why that was important (it was >6 years ago!), but I was aiming to add Python 3 support without changing the existing functionality. And if what you show is the problem, it was already there before:

```
# Python 2.7
>>> "\\b".decode("unicode-escape")
u'\x08'
```

**Comment by kefo** [comment]
My mistake.  I looked at a and b and then jumped to f and g.  It happened for a, b, and f, but not g, and so I erroneously concluded it was a hex thing.  Here's the definitive list:

a, b, f, v, 1, 2, 3, 4, 5, 6, 7

The 'v' demonstrates that this is not a hex thing; I hope that didn't mislead.  I ran each letter and number through the below:

```console
# Python 3.6.5
>>> "\q".encode("raw-unicode-escape")
b'\\q'
```
<br/>

Anyways, I'm wondering if, perhaps, the best thing to do is add a switch that effectively only invokes this code

```python
value = value.encode("raw-unicode-escape").decode("unicode-escape")
```
only when running Python 2.7.  If running Python3, because `value` is already unicode, it is unnecessary (?).

I think the below example faithfully demonstrates the use cases for the existence of encode/decode line.  In this case, for my Python3 test, I commented out locally the encode/decode line:

```console
# Python 3.6.5
>>> s=u'"Hello \u1256\u1254 Johnny, How are 五十音 $50\\00"'
>>> s
'"Hello ቖቔ Johnny, How are 五十音 $50\\00"'
>>> from_n3(s)
rdflib.term.Literal('Hello ቖቔ Johnny, How are 五十音 $50\\00')
>>> str(from_n3(s))
'Hello ቖቔ Johnny, How are 五十音 $50\\00'
>>> print(str(from_n3(s)))
Hello ቖቔ Johnny, How are 五十音 $50\00
```

To your recollection @takluyver , does that represent the reasons for the encode/decode line from way back in 2011 (and, believe me, the time since then is not lost on me - I'd have a hard time remembering myself!)?

**Comment by takluyver** [comment]
The effect of the line is that you can use unicode escapes in input, without the input being a string literal in Python source code. E.g. if the input is coming from something a user types in, or a file on disk, it can contain `\u20ac` and get converted to `€`.

As far as I can see, both that desired effect and your undesired one appear to be the same on Python 2 and 3, so I don't think making the behaviour different by Python version is a good solution.

I can't tell you how important the desired effect is, unfortunately. I suspect I never knew - I just figured out what it did on Python 2 and made it work on Python 3.

**Comment by joernhees** [comment]
sorry for not responding for so long, but it's not really clear to me if this is a bug-report, a question or just confusion...

n3 (at least in modern forms) can be encoded as utf-8 or be plain ascii and use `\uXXXX` escape sequences for non-ascii chars, hence both need to be treated, which is what the hack does...

all else (as already pointed out) seems to be confusion about how python itself treats string values entered in code or interactive mode (i.e., compare `print('hi\n')` vs `print('hi\\n')`)

i'll close this for now, re-open if there's a problem
