### ISSUE TITLE
remove logging from rdflib in production code

### ISSUE THREAD

**Issue by mertzjames** [RDFLib/rdflib#839]
Please remove the logging within rdflib for released software.  Currently, due to having logging enabled, autocompletes from tools such as ipython does not work properly.

**Comment by aucampia** [comment]
Can you provide any more info here? I don't quite understand why this should happen. I don't think logging should be removed. Maybe cleaned up or improved, but if done right it should not cause you any troubles, and I had a quick glance and I don't see anything that immediately looks wrong with usage of logging.

**Comment by mertzjames** [comment]
Basically whenever I'm using iPython to work interactively with the library, tabbing for autocompletion of the libraries contents would cause logging prints to occur.  It's probably better to limit logging to just a file system instead so as to not interrupt the user in this case.  

Additionally, when running with a script, the logging output is displayed which isn't always something that I want to be done as it may confuse my customers.
