### ISSUE TITLE
Unable to parse RDF file Invalid property element URI

### ISSUE THREAD

**Issue by 01baftb** [RDFLib/rdflib#849]
I am new to the RDF but I am trying to do a simple task of reading a RDF file that was generated by Zotero (https://www.zotero.org/). 

I am having an issue with rdflib not being able to parse the RDF file. I think the problem is something related to the original RDF data not being validated. However, what can I do to fix it? All I am trying to do is read the RDF file that was generated by another program so I can extract some information out of it. 

Below is the my Python code similar to the rdflib documentations: https://rdflib.readthedocs.io/en/4.2.2/gettingstarted.html. This is the example RDF file that I am trying to read https://gist.github.com/01baftb/f57dc47ff764c7a566dcf9308c3cbfec 

```
import rdflib 
myfile = 'myRDFfile.rdf'
g = rdflib.Graph()
g.parse(myfile)
```

**Problem:**
When I run the parse function, I get the following error below. 

```
Traceback (most recent call last):
  File "C:\Users\MyUsername\myPythonCode.py", line 7, in <module>
    g.parse(myfile)
  File "C:\Users\MyUsername\Anaconda2\lib\site-packages\rdflib\graph.py", line 1039, in parse
    parser.parse(source, self, **args)
  File "C:\Users\MyUsername\Anaconda2\lib\site-packages\rdflib\plugins\parsers\rdfxml.py", line 577, in parse
    self._parser.parse(source)
  File "C:\Users\MyUsername\Anaconda2\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Users\MyUsername\Anaconda2\lib\xml\sax\xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "C:\Users\MyUsername\Anaconda2\lib\xml\sax\expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "C:\Users\MyUsername\Anaconda2\lib\xml\sax\expatreader.py", line 373, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "C:\Users\MyUsername\Anaconda2\lib\site-packages\rdflib\plugins\parsers\rdfxml.py", line 157, in startElementNS
    current.start(name, qname, attrs)
  File "C:\Users\MyUsername\Anaconda2\lib\site-packages\rdflib\plugins\parsers\rdfxml.py", line 351, in property_element_start
    self.error("Invalid property element URI: %s" % name)
  File "C:\Users\MyUsername\Anaconda2\lib\site-packages\rdflib\plugins\parsers\rdfxml.py", line 185, in error
    raise ParserError(info + message)
rdflib.exceptions.ParserError: file:///C:/Users/MyUsername/myRDFfile.rdf:64:8: Invalid property element URI: http://www.w3.org/1999/02/22-rdf-syntax-ns#resource
```
When I used the RDF Validator (https://www.w3.org/RDF/Validator/) it said the following: 

```
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 64, Column = 103]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 104, Column = 118]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 155, Column = 81]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 212, Column = 147]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 218, Column = 93]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 269, Column = 167]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 314, Column = 148]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 320, Column = 148]
Error: {E205} rdf:resource is not allowed as an element tag here.[Line = 365, Column = 101]

```

**Comment by nicholascar** [comment]
You need to specify the format of the RDf for rdflib to be able to read the file so, in this case, use:

```
import rdflib 
myfile = 'myRDFfile.rdf'
g = rdflib.Graph()
g.parse(myfile, format='xml')
```
where the addition is the `format='xml'`.

This issue get me many times...

**Comment by Swannbm** [comment]
Hello 01baftb,

I think, the error is in Zotero, not RDFLib. Do you mind if we close this issue ?

Swann

**Comment by 01baftb** [comment]
@Swannbm @nicholascar 

Yes, you may close the issue. However, do you have any suggestions on how I can move forward troubleshooting this issue? 

I noticed that if I convert my RDF file to turtle using http://www.easyrdf.org/converter, then RDFLib does NOT give me any issues when reading the RDF  if I do `g.parse(myfile, format='turtle')`

**Comment by Swannbm** [comment]
You might parse the text file and change bad formated lines with something like :
```
output_file = open('new_file.txt', 'w')
whith open('file.txt', 'r') as f :
    line = readline()
    if line == 'error line':
         line = 'new line using data from old line'
    output_file.write(line)
output_file.close()
```

I can't close (or I don't see where is the closing button). Anyone else can ?

**Comment by nicholascar** [comment]
Closing issue and suggest the Python workaround (thanks @Swannbm) and pushing a bug to zotero!
