### ISSUE TITLE
import rdflib error in run module

### ISSUE THREAD

**Issue by Haari237** [RDFLib/rdflib#850]
![image](https://user-images.githubusercontent.com/37784658/46669731-4e13ec80-cb9e-11e8-90a4-0099cbea2bd2.png)
you can see from screen shot, it run fine in shell script but gives error in Run Module

**Comment by gromgull** [comment]
the problem is you have a local file called `calendar.py` (c:\python) which is on your PYTHON_PATH and shadows the builtin module called calendar. 

Remove that file and it will work.

**Comment by Haari237** [comment]
thanks resolved
