### ISSUE TITLE
May this possible install rdflib with unziped files?

### ISSUE THREAD

**Issue by bluecoinbear** [RDFLib/rdflib#851]
There is a few problem pushed me to do this.
Not exactly an issue

Thanks

**Comment by bluecoinbear** [comment]
================== RESTART: C:\Python\rdflib-4.2.2\setup.py ==================
no previously-included directories found matching 'docs\_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*$py.class' found anywhere in distribution

does not really work

**Comment by GillesVandewiele** [comment]
Hmm, are you on Windows? Could you go there with your cmd prompt/terminal and run python setup.py install from cmd line, then copy paste the log to there please.

I would say these are just warnings and that it probably did succeed...

You can test this by opening a python shell (preferably from another directory than the rdflib one) and trying to import rdflib.

**Comment by bluecoinbear** [comment]
same error run under the admin CMD:
C:\Python\rdflib-4.2.2>C:\Python\Python37-32\python setup.py
no previously-included directories found matching 'docs\_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*$py.class' found anywhere in distribution

**Comment by bluecoinbear** [comment]
C:\Python\rdflib-4.2.2>C:\Python\Python37-32\python setup.py
no previously-included directories found matching 'docs\_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*$py.class' found anywhere in distribution
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by bluecoinbear** [comment]
Thanks a lot. Here is my note for the dependencies according to the "error", couldn't go much forward on the 3rd
https://pypi.org/simple/pyparsing/pyparsing-2.2.2.tar.gz
https://pypi.python.org/simple/isodate/isodate-0.6.0.tar.gz
https://pypi.python.org/simple/
https://pypi.python.org/simple/six/

**Comment by gromgull** [comment]
installing python packages without pip / network connection isn't really an rdflib issue.

**Comment by Haari237** [comment]
I mentioned at very beginning
