### ISSUE TITLE
How can I do the same in rdflib python?

### ISSUE THREAD

**Issue by bluecoinbear** [RDFLib/rdflib#853]
plant.ttl
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
@prefix plant: <http://www.example.com/plant#>
@prefix thing: <http://www.example.com/thing#>

plant:fruit rdf:type rdfs:Class .
plant:fruit rdfs:label "A classification of fruit" .

plant:nut rdf:type rdfs:Class .
plant:nut rdfs:label "A classification of nut" .

plant:vegetable rdf:type rdfs:Class .
plant:vegetable rdfs:label "A classification of vegetable" .

plant:enName rdf:type rdf:Property .
plant:enName rdfs:label "The plant English name" .

plant:frName rdf:type rdf:Property .
plant:frName rdfs:label "The plant French name" .

plant:laName rdf:type rdf:Property .
plant:laName rdfs:label "The plant latin name" .

plant:sunflower rdf:type plant:nut. 
plant:sunflower plant:laName "Helianthus".
plant:sunflower plant:frName "tournesol".

**Comment by akuckartz** [comment]
Maybe this helps:
https://www.oclc.org/developer/news/2016/making-sense-of-linked-data-with-python.en.html
