### ISSUE TITLE
Consider limiting cache size for namespace manager

### ISSUE THREAD

**Issue by gromgull** [RDFLib/rdflib#868]
Currently we save every URI ever qname'd forever in here: https://github.com/RDFLib/rdflib/blob/master/rdflib/namespace.py#L289

If you serialize a big graph in a store that is off disk, we may run out of memory. 

Either: 
* Add a lru_cache (from py3 functools + [this 2.7 implementation](http://code.activestate.com/recipes/578078-py26-and-py30-backport-of-python-33s-lru-cache/)
* Depend on https://cachetools.readthedocs.io/

**Comment by tgbugs** [comment]
Related https://github.com/RDFLib/rdflib/issues/739

**Comment by joernhees** [comment]
as long as we have py2 support, i'd say cachetools is the way to go...

**Comment by gjhiggins** [comment]
Addressed in RDFLib 5.0.0.
