### ISSUE TITLE
An exception while parsing a query containing an expression coming from RDF/OWL serialization

### ISSUE THREAD

**Issue by jpotoniec** [RDFLib/rdflib#871]
Hi,
I believe the following code should be executed without problems, but instead an exception is thrown.
```
q = '''
 prefix owl: <http://www.w3.org/2002/07/owl#>        
SELECT ?x WHERE { ?sw rdfs:subClassOf owl:Thing ,
                     [                        
                        owl:onProperty [];
                        owl:someValuesFrom ?x
                     ] }
'''
rdflib.plugins.sparql.processor.prepareQuery(q) 
```
In particular, the traceback ends with the following:
```
/usr/lib/python3/dist-packages/rdflib/plugins/sparql/algebra.py in triples(l)
    127     l = reduce(lambda x, y: x + y, l)
    128     if (len(l) % 3) != 0:
--> 129         raise Exception('these aint triples')
    130     return reorderTriples((l[x], l[x + 1], l[x + 2])
    131                           for x in range(0, len(l), 3))

Exception: these aint triples
```

**Comment by arushi019** [comment]
Hi! I ran your code on my local machine and after a minor change, the code ran without any errors. `import rdflib
from rdflib.plugins.sparql import prepareQuery
q = '''
 prefix owl: <http://www.w3.org/2002/07/owl#>        
SELECT ?x WHERE { ?sw rdfs:subClassOf owl:Thing ,
                     [                        
                        owl:onProperty [];
                        owl:someValuesFrom ?x
                     ] }
'''
prepareQuery(q) `
I hope this helps :)

**Comment by gjhiggins** [comment]
Unable to reproduce,
