### ISSUE TITLE
RDF namespace does not allow rdf:Seq valid terms

### ISSUE THREAD

**Issue by albertmeronyo** [RDFLib/rdflib#873]
Hi,

According to the [RDFS recommendation](https://www.w3.org/TR/rdf-schema/#ch_collectionvocab), elements of an rdf:Seq can be ordered by using predicates of the form:

`C rdf:_nnn O`

"where `nnn` is the decimal representation of an integer greater than 0 with no leading zeros". However in rdflibish notation these do not work:

```
>>> RDF["_1"]
Exception: term '_1' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
>>> RDF._1
Exception: term '_1' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
```

My current workaround is to mint new URIRefs for these, but I guess a more elegant solution could be provided?

Thanks,
Albert

**Comment by iddan** [comment]
Encountered the same problem as well

**Comment by reeshabhkumarranjan** [comment]
@nicholascar Me, @guvi007 @prince17080 would like to work on this issue, can we go forward.

**Comment by reeshabhkumarranjan** [comment]
I tried running both of them, they seem to work now.

**Comment by mwatts15** [comment]
This seems to be a regression on 6.0.0.

**Comment by nicholascar** [comment]
Oh dear, I wonder what we broke. I suppose we must not have had suitable tests in place to realise that we broke sometihng.

@mwatts15 can you make/show a test for the error?

**Comment by mwatts15** [comment]
@nicholascar I made a PR. IIUC, the code generation was a one time thing, so I figure it's OK to modify the generated _RDF.py
