### ISSUE TITLE
Py3 incompatibility in turtle serializer

### ISSUE THREAD

**Issue by jottinger** [RDFLib/rdflib#884]
When starting to write a document with turtle, the serializer does a `text.encode` which changes the type from a `str` to `bytes` - which itself causes a failure in `write()`.

As `rdflib` already uses `six`, it should just be a matter of checking the types and converting appropriately.

**Comment by gjhiggins** [comment]
“6.0.0 is a major stable release that drops support for Python 2 and Python 3 < 3.7”, no longer an issue, closing.
