### ISSUE TITLE
Order of information in RDF files

### ISSUE THREAD

**Issue by vporton** [RDFLib/rdflib#887]
Can I expect that the order I get triples is the same as the information appears say in a Turtle file?

It should be documented whether the order is stable and whether it conforms to the order of information in RDF files.

**Comment by jimmccusker** [comment]
No, there is no ordering in graphs, and since a graph can load from multiple files as well as be manipulated programmatically, maintaining order is problematic at best. RDF graphs are defined as sets of statements, and sets do not have a defined order either.

**Comment by gjhiggins** [comment]
Answered
