### ISSUE TITLE
TypeError (input parameter) when not providing context for Graph.triples()

### ISSUE THREAD

**Issue by themmes** [RDFLib/rdflib#899]
I could not find this error in the issues yet, following the docs it should be possible "If triple pattern does not provide a context, all contexts will be searched.".

**Example**
```
import rdflib
graph = rdflib.Graph()
graph.triples()
```

**Setup**
```
Python 3.6.7 (default, Oct 25 2018, 09:16:13)
rdflib==4.2.2
Linux 16.04 Xenial
```

**Error**
Seems like something that should not be included in a Pypi release.
`TypeError: triples() missing 1 required positional argument: 'xxx_todo_changeme2'`

**Comment by sirspock** [comment]
I have the same issue.

```
>>> import rdflib
INFO:rdflib:RDFLib Version: 4.2.2
graph = rdflib.Graph()
graph.triples()
>>> graph = rdflib.Graph()
>>> graph.triples()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: triples() missing 1 required positional argument: 'xxx_todo_changeme2'
```

**Comment by bgyori** [comment]
Related to #917

**Comment by mwatts15** [comment]
The documentation for this method is misleading and incomplete. Both should be resolved in the next release.

In any case `rdflib.graph.Graph::triples()` _only_ accepts a triple pattern, but the sub-class method `rdflib.graph.ConjunctiveGraph::triples()` accepts either a quad with the context (i.e., named graph identifier) as the fourth member or a `context` keyword param. See this [doc](https://rdflib.readthedocs.io/en/latest/intro_to_graphs.html#basic-triple-matching) (from the latest development version) for more some examples of for `Graph`.

**Comment by sanyam19106** [comment]
if you can use 
import rdflib
graph = rdflib.Graph()
graph.triples(())
It gives no error beacuse you are not give any triple so take if deafault

**Comment by gjhiggins** [comment]
> The documentation for this method is misleading and incomplete. Both should be resolved in the next release.

Noted, closing.
