### ISSUE TITLE
cannot clone it on windows

### ISSUE THREAD

**Issue by loveJasmine** [RDFLib/rdflib#901]
C:\ub16_prj>git clone https://github.com/RDFLib/rdflib
Cloning into 'rdflib'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 20819 (delta 16), reused 30 (delta 15), pack-reused 20779
Receiving objects: 100% (20819/20819), 12.29 MiB | 751.00 KiB/s, done.
Resolving deltas: 100% (13280/13280), done.
error: unable to create file test_reports/rdflib_nquads-2013-12-22T19:22:34.ttl: Invalid argument
error: unable to create file test_reports/rdflib_nt-2013-12-22T19:12:25.ttl: Invalid argument
error: unable to create file test_reports/rdflib_sparql-2013-12-22T19:36:48.ttl: Invalid argument
error: unable to create file test_reports/rdflib_trig-2013-12-22T19:31:52.ttl: Invalid argument
error: unable to create file test_reports/rdflib_trig-2013-12-30T15:56:57.ttl: Invalid argument
error: unable to create file test_reports/rdflib_turtle-2013-12-22T19:13:51.ttl: Invalid argument
Checking out files: 100% (4439/4439), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by kinow** [comment]
Probably due to colon (`:`) in the file name, which is an illegal character in Windows: https://stackoverflow.com/questions/5991805/how-do-i-clone-files-with-colons-in-the-filename

**Comment by loveJasmine** [comment]
so, maybe we should change it compatible with windows

**Comment by joernhees** [comment]
hmm, not sure if simply changing the files is enough, as they're probably generated and might be referenced by name somewhere... will reopen this as even though it's annoying, we actually should support windows...

**Comment by white-gecko** [comment]
They are used here:

```
$ ack test_reports
test/test_dawg.py
616:        earl_report = 'test_reports/rdflib_sparql-%s.ttl' % now
619:        report.serialize('test_reports/rdflib_sparql-latest.ttl', format='n3')

test/testutils.py
99:        earl_report = 'test_reports/%s-%s.ttl' % (earl_report_name, now)
102:        report.serialize('test_reports/%s-latest.ttl'%earl_report_name, format='n3')

```

**Comment by white-gecko** [comment]
They might be relevant for the W3C implementation reports https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-turtle/reports/index.html.
@gromgull you have submitted them back than. Is it important to stick to the naming scheme of using the ISO date in the filename?

**Comment by gromgull** [comment]
I guess being able to clone on windows is in any case more important than w3c reports :D

Only `test_dawg` will write reports (they are only relevant for SPARQL) 

https://github.com/RDFLib/rdflib/blob/master/test/test_dawg.py#L616-L620
