### ISSUE TITLE
Is xml default namespace missing a trailing slash?

### ISSUE THREAD

**Issue by DaniFdezAlvarez** [RDFLib/rdflib#904]
I am using rdflib with Python 2.7. When I explore the namespaces that are already mapped to a prefix in a new graph, I get the following:

g = Graph()
for a_prefix_namespace_tuple in g.namespaces():
    print a_prefix_namespace_tuple

\# ('xml', rdflib.term.URIRef(u'http://www.w3.org/XML/1998/namespace'))
\# ('rdf', rdflib.term.URIRef(u'http://www.w3.org/1999/02/22-rdf-syntax-ns#'))
\# ('xsd', rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#'))
\# ('rdfs', rdflib.term.URIRef(u'http://www.w3.org/2000/01/rdf-schema#'))

I am missing a trailing slash in xml namespace

**Comment by gjhiggins** [comment]
> I am missing a trailing slash in xml namespace

No, the XML namespace does not have a trailing slash: https://www.w3.org/XML/1998/namespace:

> The namespace whose name is `http://www.w3.org/XML/1998/namespace` is bound by definition to the prefix `xml:`
