### ISSUE TITLE
Parse SPARQLResult

### ISSUE THREAD

**Issue by mavrovgeorgi** [RDFLib/rdflib#907]
Hello,

I am able to read the RDF and send queries to it, but I cannot find a solution for parsing the SPARQLResult to XML or JSON.

Here is my result from the query.
`result = graph.query(my_query)`

Is there any way to parse the result?

Thanks!

**Comment by nicholascar** [comment]
Sorry but you'll have to implement your own solution here cycling through the SPARQLResult obkect. If you do this:

```
from rdflib import Graph
import json
d = """
    <a:> a <c:> .
    <d:> a <c:> .
    <g:> a <k:> .
"""
g = Graph().parse(data=d, format="turtle")

q = """SELECT ?s WHERE { ?s ?p <c:>  .}"""

# try to print to JSON
print(json.dumps(g.query(q)))
```

you will get:

```
TypeError: Object of type SPARQLResult is not JSON serializable
```

Yep, we've not implemented a SPARQLResult JSOn serializer! you would need something like this:

```
class SPARQLResultJSONEncoder(json.JSONEncoder):
    def default(self, obj):
        try:
            # do things in here to serilize the SPARQLResult object
        exception:
            return json.JSONEncoder.default(self, obj)
```

Then call it:

```
encoder = SPARQLResultJSONEncoder()
print(encoder.encode(g.query(q)))
```

**Comment by gromgull** [comment]
We actually have a JSON Result Serializer :D 

https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/results/jsonresults.py#L31

**Comment by nicholascar** [comment]
Gunnar to the rescue, thanks @gromgull! 

So, as above, then

```
encoder = JSONResultSerializer()
print(encoder.encode(g.query(q)))
```

OK, we've not addressed XML serialization but the question did say "SPARQLResult to XML **or** JSON" so I'm going to close this in keep with trying to get questions answered out of the open Issues list!
