### ISSUE TITLE
lax rdfa parser - when html5 parser missing, please suggest the exact library needed

### ISSUE THREAD

**Issue by ghost** [RDFLib/rdflib#91]
danbrick...@gmail.com, 2009-12-29T13:38:25.000Z

<pre>
(sudo) easy_install html5lib ... worked for me, but I had to figure out
which library it wanted first. 

g = rdflib.graph.ConjunctiveGraph().parse('http://example.org/foo/',
format='rdfa', lax=True)

gave 'rdflib.syntax.parsers.rdfa.RDFaError: XHTML Parsing error in input
file: not well-formed (invalid token): line 104, column 600. Though parsing
is lax, HTML5 parser not available'
 as an error message. The library name 'html5lib' is worth mentioning;
perhaps also a reminder about 'easy_install'?

Comment 1 by ed.summers
huh i guess commit for r1730 didn't close the ticket :-(

Comment 2 by danbrick...@gmail.com
sure it does! didn't know you'd fixed already :)
</pre>

**Comment by danbri** [comment]
damn, I was trying to parse RDFa in a Python notebook, here today in 2018. Apparently my former self knew something about this, and I remember nothing.  I'm getting "html5lib is not installed, cannot use RDFa and Microdata parsers." despite pip installing html5lib.
