### ISSUE TITLE
SPARQL: UNION with two identical branches returns only result for one branch

### ISSUE THREAD

**Issue by cygri** [RDFLib/rdflib#910]
This SPARQL query should return two solutions, both identical, binding variable `?a` to string `"a"`:
```sparql
SELECT * {
    { BIND ("a" AS ?a) }
    UNION
    { BIND ("a" AS ?a) }
}
```
But it returns only one of the two solutions. The same effect—only the first union returns any results—happens when the unions have more than one variable or more than one solution each. The problem is triggered by the _results_ being identical, not just by the _graph patterns_ being identical. This one also just returns one solution:
```sparql
SELECT * {
    { BIND ("a" AS ?a) }
    UNION
    { VALUES ?a { "a" } }
    UNION
    { SELECT ("a" AS ?a) {} }
}
```
The problem goes away as soon as there is any difference between the results of the two union branches.

**Comment by abhivandan1999** [comment]
I am interested in solving this issue.

**Comment by kushagr08** [comment]
@nicholascar 
I would like to make a pull request to solve this issue. The result returned by select queries involving union should contain results of both the branches, even if they are identical, as per the w3c union cardinality documentation.
https://www.w3.org/TR/sparql11-query/#defn_algUnion

**Comment by nicholascar** [comment]
@kushagr08 please, go ahead! @abhivandan1999: you might like to assist.

Please both of you please metion @cygri in your PR so he can review (of course up rdflib maintainers will review as well!)

**Comment by nicholascar** [comment]
Oh! @kushagr08, you've already done it in PR #1057! I've added the close statement to that PR description. 

Will review that PR shortly.
