### ISSUE TITLE
Incorrect comparison of literals

### ISSUE THREAD

**Issue by DhanshreeA** [RDFLib/rdflib#915]
I have two duration literals and I created them like this:
`
duration1 = Literal("P10Y0M0D", datatype=XSD.duration)
duration2 = Literal("P5Y0M0D", datatype=XSD.duration)
`
and for some reason `duration1 < duration2` is True in the python interpreter. I know that the `year` and `month` designators needn't be present if their corresponding values are zero, however keeping them still doesn't form an invalid xs:duration literal, right? 
The strange things is that literal comparison works fine for most other literals. Even literal pairs like P1Y0M0D, P2Y, or any other combination of this. Can someone explain this behavior?

**Comment by tgbugs** [comment]
https://github.com/RDFLib/rdflib/blob/81d2e61c90756fcca0b3531c61e5d3b686e02090/rdflib/term.py#L751 Is where the comparison is implemented. This issue is probably due to the fact that your underlying python type is a string. If you use a time delta for those then I think it should work.

**Comment by DhanshreeA** [comment]
> https://github.com/RDFLib/rdflib/blob/81d2e61c90756fcca0b3531c61e5d3b686e02090/rdflib/term.py#L751
> Is where the comparison is implemented. This issue is probably due to the fact that your underlying python type is a string. If you use a time delta for those then I think it should work.

@tgbugs Umm, I don't understand. A time delta how? Can you please share an example here? I've only ever made literal terms out of python strings, or numbers when using a numeric type.

**Comment by mwatts15** [comment]
Value comparisons of ISO-8601 durations aren't fully supported yet in RDFLib Literals. I think it's pretty straight-forward to add though.

**Comment by tgbugs** [comment]
@DhanshreeA see https://docs.python.org/3/library/datetime.html#timedelta-objects

You would need to convert your strings into python timedelta objects.

**Comment by mwatts15** [comment]
Looked into it more and comparing durations in value space isn't possible in general (e.g., a duration of 1 month isn't always the same). So, there could be a mapping to isodate `Duration` and *technically* could convert to `datetime.timedelta`, though I think that's not correct in general.

**Comment by tgbugs** [comment]
Does this mean that some `xsd:duration`s are not orderable?

**Comment by mwatts15** [comment]
Yes. However, the master branch actually has an implementation of this already (I had only looked at the latest released version). `dayTimeDuration` should always be convertible to `timedelta`, so should always be comparable. @Tpt is responsible for the addition.

**Comment by gjhiggins** [comment]
According to discussion, fixed in [ef896173bdc7f0bbb50e46dbc1ca0356f6](https://github.com/RDFLib/rdflib/commit/8b3214ef896173bdc7f0bbb50e46dbc1ca0356f6), closing.
