### ISSUE TITLE
wheel distribution of 4.2.2 full of xxx_todo_changeme arguments

### ISSUE THREAD

**Issue by metazool** [RDFLib/rdflib#917]
I was startled to see this, after some digging around it looks like an artefact of the python 2to3 conversion process being run during the setup phase. After either installing the wheel via pip, or downloading the source from pypi and rebuilding the wheel with `python setup.py bdist_wheel`, all the tuple arguments are converted into an odd `xxx_todo_changeme` single argument form.
To see this in the wheel distribution:

- `wget https://files.pythonhosted.org/packages/3c/fe/630bacb652680f6d481b9febbb3e2c3869194a1a5fc3401a4a41195a2f8f/rdflib-4.2.2-py3-none-any.whl`
- `wheel unpack rdflib-4.2.2-py3-none-any.whl`
- `grep -r xxx_todo rdflib-4.2.2/*`

Resulting in this experience
```
>>> from rdflib import Graph
INFO:rdflib:RDFLib Version: 4.2.2
>>> g = Graph()
>>> g.triples()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: triples() missing 1 required positional argument: 'xxx_todo_changeme2'
```
Here's a related issue https://github.com/warner/python-ecdsa/issues/3 , I'm not sure there's a better way than changing the argument types at source. 

The `setup.py` with the conversion in it in the pypi source distribution looks quite different to the one in the repository here, though, and doesnt have the setup_python3 function? I tried rebuilding the wheel with python 3.6 and 3.7 https://github.com/RDFLib/rdflib/blob/master/setup.py

**Comment by mwatts15** [comment]
Granted, it's unexpected. What is the actual issue?

**Comment by bgyori** [comment]
I think the main issue that for users like me it's hard to figure out how to use these functions. For instance, I'd call e.g., graph.triples() and get
```
TypeError: triples() missing 1 required positional argument: 'xxx_todo_changeme2'
```
the argument makes no sense at all, so then I look up help and find
```
Signature: g.triples(xxx_todo_changeme2)
Docstring:
Generator over the triple store

Returns triples that match the given triple pattern. If triple pattern
does not provide a context, all contexts will be searched.
File:      [...]/python3.6/site-packages/rdflib/graph.py
Type:      method
```
without any explanation of how xxx_todo_changeme2 relates to the "triple pattern" being mentioned, and how said "triple pattern" needs to be formatted.

**Comment by sanyam19106** [comment]
if you can use
import rdflib
graph = rdflib.Graph()
graph.triples(())
It gives no error beacuse you are not give any triple so take if default

**Comment by gjhiggins** [comment]
No longer pertinent. Closing, having noted the documentation recommendations.
