### ISSUE TITLE
SPARQLConnector.update() does set content type

### ISSUE THREAD

**Issue by jimmccusker** [RDFLib/rdflib#919]
According to the [spec](https://www.w3.org/TR/sparql11-protocol/#update-bindings-http-examples), when posting `text/plain` data (which is what most web servers interpret a missing content-type as) to a SPARQL endpoint, you need to pass the update as a form-encoded dictionary. However, the current SPARQLConnector.update() function passes it as the data body, which would be fine if the content type were set to `application/sparql-update`. It's probably easier to set the content type correctly, but the current state will fail on SPARQL endpoints (like Blazegraph) that interpret this strictly.

**Comment by robcast** [comment]
Thanks for spotting this @jimmccusker! I just ran into the same problem with some obscure error messages when I tried to use RDFLib 5.0.0 with Blazegraph (worked fine with 4.2.2).

...looks like it's been fixed in da99d4e. Now if there would be a new release... :-)
