### ISSUE TITLE
4.2.2: test suite fails with python 3.7.4

### ISSUE THREAD

**Issue by kloczek** [RDFLib/rdflib#924]
<pre>+ /usr/bin/python3 setup.py test
no previously-included directories found matching &apos;docs/_build&apos;
warning: no previously-included files matching &apos;*.pyc&apos; found anywhere in distribution
warning: no previously-included files matching &apos;*$py.class&apos; found anywhere in distribution
Can&apos;t parse build/src/run_tests.py: ParseError: bad input: type=22, value=&apos;=&apos;, context=(&apos;&apos;, (71, 22))
running test
Searching for SPARQLWrapper
Reading https://pypi.org/simple/SPARQLWrapper/
Downloading https://files.pythonhosted.org/packages/b0/1d/d7c60a451a255fca655fe37eb3f6e3b3daa7d33fc87eeec0d8631d501e76/SPARQLWrapper-1.8.4-py3-none-any.whl#sha256=abc3e7eadcad32fa69a85c003853e2f6f73bda6cc999853838f401a5a1ea1109
Best match: SPARQLWrapper 1.8.4
Processing SPARQLWrapper-1.8.4-py3-none-any.whl
Installing SPARQLWrapper-1.8.4-py3-none-any.whl to /home/tkloczko/rpmbuild/BUILD/rdflib-4.2.2/.eggs
writing requirements to /home/tkloczko/rpmbuild/BUILD/rdflib-4.2.2/.eggs/SPARQLWrapper-1.8.4-py3.7.egg/EGG-INFO/requires.txt

Installed /home/tkloczko/rpmbuild/BUILD/rdflib-4.2.2/.eggs/SPARQLWrapper-1.8.4-py3.7.egg
Searching for networkx
Reading https://pypi.org/simple/networkx/
Downloading https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip#sha256=8311ddef63cf5c5c5e7c1d0212dd141d9a1fe3f474915281b73597ed5f1d4e3d
Best match: networkx 2.3
Processing networkx-2.3.zip
Writing /tmp/easy_install-mtvghs4o/networkx-2.3/setup.cfg
Running networkx-2.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mtvghs4o/networkx-2.3/egg-dist-tmp-9_mvrw9a
warning: no files found matching &apos;*.html&apos; under directory &apos;doc&apos;
warning: no files found matching &apos;*.css&apos; under directory &apos;doc&apos;
warning: no previously-included files matching &apos;*~&apos; found anywhere in distribution
warning: no previously-included files matching &apos;*.pyc&apos; found anywhere in distribution
warning: no previously-included files matching &apos;.svn&apos; found anywhere in distribution
no previously-included directories found matching &apos;doc/build&apos;
no previously-included directories found matching &apos;doc/auto_examples&apos;
no previously-included directories found matching &apos;doc/modules&apos;
no previously-included directories found matching &apos;doc/reference/generated&apos;
no previously-included directories found matching &apos;doc/reference/algorithms/generated&apos;
no previously-included directories found matching &apos;doc/reference/classes/generated&apos;
no previously-included directories found matching &apos;doc/reference/readwrite/generated&apos;
creating /home/tkloczko/rpmbuild/BUILD/rdflib-4.2.2/.eggs/networkx-2.3-py3.7.egg
Extracting networkx-2.3-py3.7.egg to /home/tkloczko/rpmbuild/BUILD/rdflib-4.2.2/.eggs

Installed /home/tkloczko/rpmbuild/BUILD/rdflib-4.2.2/.eggs/networkx-2.3-py3.7.egg
running egg_info
writing rdflib.egg-info/PKG-INFO
writing dependency_links to rdflib.egg-info/dependency_links.txt
writing entry points to rdflib.egg-info/entry_points.txt
writing requirements to rdflib.egg-info/requires.txt
writing top-level names to rdflib.egg-info/top_level.txt
reading manifest file &apos;rdflib.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
no previously-included directories found matching &apos;docs/_build&apos;
warning: no previously-included files matching &apos;*.pyc&apos; found anywhere in distribution
warning: no previously-included files matching &apos;*$py.class&apos; found anywhere in distribution
writing manifest file &apos;rdflib.egg-info/SOURCES.txt&apos;
running build_ext
Traceback (most recent call last):
  File &quot;setup.py&quot;, line 156, in &lt;module&gt;
    **kwargs
  File &quot;/usr/lib/python3.7/site-packages/setuptools/__init__.py&quot;, line 145, in setup
    return distutils.core.setup(**attrs)
  File &quot;/usr/lib64/python3.7/distutils/core.py&quot;, line 148, in setup
    dist.run_commands()
  File &quot;/usr/lib64/python3.7/distutils/dist.py&quot;, line 966, in run_commands
    self.run_command(cmd)
  File &quot;/usr/lib64/python3.7/distutils/dist.py&quot;, line 985, in run_command
    cmd_obj.run()
  File &quot;/usr/lib/python3.7/site-packages/setuptools/command/test.py&quot;, line 229, in run
    self.run_tests()
  File &quot;/usr/lib/python3.7/site-packages/setuptools/command/test.py&quot;, line 251, in run_tests
    exit=False,
  File &quot;/usr/lib64/python3.7/unittest/main.py&quot;, line 100, in __init__
    self.parseArgs(argv)
  File &quot;/usr/lib64/python3.7/unittest/main.py&quot;, line 124, in parseArgs
    self._do_discovery(argv[2:])
  File &quot;/usr/lib64/python3.7/unittest/main.py&quot;, line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File &quot;/usr/lib64/python3.7/unittest/main.py&quot;, line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File &quot;/usr/lib64/python3.7/unittest/loader.py&quot;, line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File &quot;/usr/lib64/python3.7/unittest/loader.py&quot;, line 406, in _find_tests
    full_path, pattern, namespace)
  File &quot;/usr/lib64/python3.7/unittest/loader.py&quot;, line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File &quot;/usr/lib/python3.7/site-packages/setuptools/command/test.py&quot;, line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File &quot;/usr/lib64/python3.7/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/tkloczko/rpmbuild/BUILD/rdflib-4.2.2/examples/custom_datatype.py&quot;, line 42
    print l2 
           ^
SyntaxError: Missing parentheses in call to &apos;print&apos;. Did you mean print(l2)?
error: Bad exit status from /var/tmp/rpm-tmp.lc1GuY (%check)
</pre>

**Comment by nicholascar** [comment]
Fixed in commit https://github.com/RDFLib/rdflib/commit/fbf32e11862ca4d07b745a36b4389e900c60c00d 3 years ago in master (post 4.2.2. release).
