### ISSUE TITLE
Can we inhance using Json to JSONLD to RDF Converters?

### ISSUE THREAD

**Issue by shafaypro** [RDFLib/rdflib#928]
I was going through the code, can there be an enhanced feature where we just load in the data in form of JSON (without semantic's and specify general types of key's, their data types and required or not required) which goes to rdflib, auto-generates the JSON-LD based on converting techniques which are extracted from jsonld.org and later referred to RDF mapping.

This is because most of the web data out there is less semantic, Even though for converting a JSON data to a Graph database or Sparql/ Triplet based its hard.
Since we need to rewrite the schema or maybe if someone can give me a hint. AS I am looking in to use AWS NEPTUNE and it accepts RDFXML  or triplets graph formats.

Any Thoughts or concepts?

**Comment by nicholascar** [comment]
Hi @shafaypro sorry but we can't support this Issue. RDFlib is a toolkit for manipulating RDF so we aren't going to include any converter tools to take otehr data and convert it to RDF in the core. A stand-alone tool could be written (e.g. see [pyTARQL](https://github.com/RDFLib/pyTARQL) for CSV) and perhaps even scripts in the RDFlib `tools/` folder, but we don't need an Issue open for this. If you are motivated, please supply a PR for such a tool!

(I suspect that if you had regular enough JSON for a tool to always work to convert it to JSON-LD, you would actually have... JSON-LD!!! The information content would necessarily be the same)

**Comment by rob-metalinkage** [comment]
@shafaypro - it is not there yet but the tool ProfileWiz  https://github.com/RDFLib/profilewiz is designed to generate JSON-LD contexts and schemas from an input ontology. 

It already allows for specification of a library of base ontologies to factor out of a mixed up ontology file

It wouldnt be a terribly big job to make it consume JSON instance or schema and automatically match elements with known classes and properties - and create a new ontology out of the elements it cant match.  Create a fork and send a PR if you want to have a go at this - or write an issue for profilewiz with sample inputs and outputs.
