### ISSUE TITLE
how to force rdflib for @prefix

### ISSUE THREAD

**Issue by shahidost** [RDFLib/rdflib#930]
I am using rdflib for my project. but I am facing some issue regarding @prefix. 
I want to create a .ttl file of some rdf graph that looks like this:

```
@prefix ks: <http://dkm.fbk.eu/ontologies/knowledgestore#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix vtkel: <http://vksflickr30k.fbk.eu/resource/> .
@prefix gaf: <http://groundedannotationframework.org/gaf#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

vtkel:23017628 a dcmit:Collection .

vtkel:23017628#40130 a ks:Entity,
        flickrOntology:people ;
    gaf:denotedBy vtkel:23017628C0#char=0,22 ,
        vtkel:23017628I #xywh=115,20,384,499 ;
    owl:hasPart vtkel:23017628C0/#tennis; 
    owl:sameAs vtkel:23017628C0/#player .
```
-------------------------------------------------------------------------------------------
but the resultant rdf graph from rdflib is giving me the following output:

```
<http://vksflickr30k.fbk.eu/resource/#23017628> a dcmit:Collection .
<http://vksflickr30k.fbk.eu/resource/23017628#40130> a ks:Entity,
            flickrOntology:people ;
        gaf:denotedBy <http://vksflickr30k.fbk.eu/resource/23017628C0/#char=0,22>,
            <http://vksflickr30k.fbk.eu/resource/23017628I/#xywh=115,20,384,499> ;
        owl:hasPart <http://vksflickr30k.fbk.eu/resource/23017628C0/#tennis> ;
        owl:sameAs <http://vksflickr30k.fbk.eu/resource/23017628C0/#player> .
```
-------------------------------------------------------------------------------------------------
I want to force the rdflib for @prefix vtkel, to avoid the uri:http://vksflickr30k.fbk.eu/resource/ and give me the prefix vtekl:something.

I will be very thankful for your help.
Thanks Shahi

**Comment by GillesVandewiele** [comment]
You can make use of Namespace and bind: https://rdflib.readthedocs.io/en/stable/namespaces_and_bindings.html

**Comment by shahidost** [comment]
I used both but still didn't work. a small portion of my code is given below.

from rdflib import Graph, URIRef, Literal, Namespace, ConjunctiveGraph

g1 = Graph()
vtkel = Namespace('http://vksflickr30k.fbk.eu/resource/')
g1.bind("vtkel",vtkel)
pikes_entity=image_id+'C'+str(j)+'/#'+'tennis'
pikes_entity=URIRef(vtkel[pikes_entity])
g1.add(( pikes_entity, URIRef(rdf['type']),URIRef(yago['Tennis1329543'])))

but still, the prefix vtekl not forcing to convert uri to prefix.

**Comment by GillesVandewiele** [comment]
Hmm strange, this seems to work:

```python3
from rdflib import Graph, URIRef, Namespace
chron = Namespace('http://example.com/')
g = Graph()
g.bind('chron', chron, override=True)
g.add((URIRef('http://example.com/Bob'), URIRef('http://xmlns.com/foaf/0.1/knows'), URIRef('http://example.com/Alice')))
g.serialize('test.ttl', format='turtle')
```

OUTPUT:

```
@prefix chron: <http://example.com/> .
@prefix ns1: <http://xmlns.com/foaf/0.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

chron:Bob ns1:knows chron:Alice .
```

**Comment by shahidost** [comment]
Like I am checking this:

`from rdflib import Graph, URIRef, Namespace
chron = Namespace('http://vksflickr30k.fbk.eu/resource/')
g = Graph()
g.bind('chron', chron, override=True)
g.add((URIRef('http://example.com/Bob'), URIRef('http://xmlns.com/foaf/0.1/knows'), URIRef('http://example.com/Alice')))
g.serialize('test.ttl', format='turtle')`

OUTPUT:
`@prefix ns1: <http://xmlns.com/foaf/0.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix vtkel: <http://vksflickr30k.fbk.eu/resource/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/Bob> ns1:knows <http://example.com/Alice> .`

**Comment by shahidost** [comment]
I want to change the uri: http://example.com/    like this:
http://example.com/caption0/Bob
http://example.com/caption1/Bob

g.add((URIRef('http://example.com/caption0/Bob'), URIRef('http://xmlns.com/foaf/0.1/knows'), URIRef('http://example.com/Alice')))

I am trying to force the prefix chron to work for both caption 0 and 1 for Bob. But it's not working for this.
Thanks

**Comment by tgbugs** [comment]
I suspect that the issue you are encountering here is that `#` is forcing the creation of a new prefix because of how [split_uri](https://github.com/RDFLib/rdflib/blob/af625d0bc48b656b614629b9ad56df63b88a0d17/rdflib/namespace.py#L498) in namespace.py works. There are a number of other chars that force the uri to split, and what the default behavior should be is still under discussion.

In your case in particular you may also be running into https://github.com/RDFLib/rdflib/pull/649#discussion_r228733170, which means that there is no way to shorten some of your uris.

**Comment by nicholascar** [comment]
@shahidost sorry that this issue's not resolved for now but since this is currently a *won't fix* scenario, can I please close this issue? You might like to then follow the discussion in issue #649 as @tgbugs suggested.

**Comment by shahidost** [comment]
Okay sure, I am closing the issue 
Thanks @nicholascar
