### ISSUE TITLE
DCTERMS.format not working

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#932]
When using the inbuilt DCTERMS namespace, `from rdflib.namespace import DCTERMS`, an error is thrown if the following triple is added to a graph:

```
g.add((r, DCTERMS.format, Literal('application/pdf')))
```
**error**: _AssertionError: Predicate <built-in method format of Namespace object at 0x10e8e2de0> must be an rdflib term_

Presumably there's a Python reserved word 'format' collision somewhere.

Have to do this as a workaround:
```
g.add((r, URIRef('http://purl.org/dc/terms/format'), Literal('application/pdf')))
```

**Comment by tgbugs** [comment]
Does `DCTERMS['format']` work?

**Comment by nicholascar** [comment]
Oh, I think it does. And, I think I’ve even used it in the past...

Happy to have this issue closed as it’s really, really minor unless someone’s really keen to deal with it for fun.

**Comment by nicholascar** [comment]
I'm closing my own issue here as it's very minor and two work-around are given in comments.
