### ISSUE TITLE
'en_US' is not a valid language tag!

### ISSUE THREAD

**Issue by wumpus** [RDFLib/rdflib#937]
rdflib validates langauge tags, and RFC 5646 is mentioned at the top of term.py. Dash is the only valid separator for things like "en-US" in this RFC.

In parsing the actual web, some small fraction of the web uses "en_US" with an underscore. This causes an exception deep in rdflib, and there's no easy way of fixing it up at runtime.

I'm not a fan of invalid input being silently fixed up, so I'd recommend it being an option and not the default.

term.py:_is_valid_langtag() is the thing that validates.

**Comment by mwatts15** [comment]
Can you provide a failing test case? The function you reference returns `False` for "en_US".

**Comment by wumpus** [comment]
```
diff --git a/test/test_nt_misc.py b/test/test_nt_misc.py
index d9f9e1f..6fb9ba6 100644
--- a/test/test_nt_misc.py
+++ b/test/test_nt_misc.py
@@ -36,6 +36,12 @@ class NTTestCase(unittest.TestCase):
         s = g.serialize(format="nt").strip()
         self.assertEqual(s, b('<foo> <foo> "test\\n"@en .'))
 
+    def testIssue937(self):
+        g = Graph()
+        g.add((URIRef("foo"), URIRef("foo"), Literal("test\n", lang="en_US")))
+        s = g.serialize(format="nt").strip()
+        self.assertEqual(s, b('<foo> <foo> "test\\n"@en-us .'))
+
     def test_sink(self):
         s = ntriples.Sink()
         self.assertTrue(s.length == 0)
```

```
        if lang and not _is_valid_langtag(lang):
>           raise Exception("'%s' is not a valid language tag!" % lang)
E           Exception: 'en_US' is not a valid language tag!
```

**Comment by mwatts15** [comment]
Ah, I see. I thought you were saying RDFLib is not following the spec. Validating the language tags from wherever you're getting them is a problem for your own application rather than RDFLib.

**Comment by wumpus** [comment]
I have a web crawler, I download web docs, and I parse them. There's no easy way with rdflib to deal with this particular issue, other than forking rdflib. I mean, it's fine if you don't care about this case, but it's certainly common that rdf documents are found in webpages, and people want to parse them.

**Comment by mwatts15** [comment]
It's less that I don't care about the use case and more that I don't think it's a good idea to make RDFLib more complex to support data that's out-of-spec. It makes more sense to me that an application, like your web crawler, would either clean up the language tags in the input or implement a more lenient parser that fixes the language tags while processing.

**Comment by niklasl** [comment]
I agree that it would be better to clean up the input prior to passing it to RDFLib, and that an option is an undesired complexity (unless this turns out to be an extremely common case in the wild).

To get by without that Right Now™, may I suggest a monkey-patch:
```python
>>> import rdflib.term
>>> rdflib.term._is_valid_langtag('en_US')
False
>>> _is_valid_langtag = rdflib.term._is_valid_langtag
>>> def lenient_is_valid_langtag(langtag):
...     return _is_valid_langtag(langtag.replace('_', '-')
...                              if isinstance(langtag, str) else langtag)
... 
>>> rdflib.term._is_valid_langtag = lenient_is_valid_langtag
>>> rdflib.term._is_valid_langtag('en_US')
True
```

Note that hacks like this are a Bad Idea™ in general (they're not guaranteed to survive even minor revisions to a library, especially when they're tampering with "_private" details like here). But they're quite effective for short-term workarounds (and often last longer than you might expect, for better or worse (you may never have to care again, but they may e.g. silently block altered and improved behaviour)).

**Comment by nicholascar** [comment]
I agree with @mwatts15 and with @niklasl 's first point that input fixups are best left out of rdflib (we've got enough serious internal issues to deal with!) so I'm going to close this as an "out-of-scope" issue.
