### ISSUE TITLE
Automate call to apidoc

### ISSUE THREAD

**Issue by mwatts15** [RDFLib/rdflib#938]
Currently the apidoc-generated autodoc files are version controlled and inconsistent with the result of the apidoc command in docs/docs.rst . This has resulted in the files being out-of-date. This situation can be resolved by running apidoc as part of the documentation build process. This is possible using the `sphinx.ext.apidoc` module and calling `main` in docs/conf.py

To resolve this issue, add that call to `sphinx.ext.apidoc.main()` to docs/conf.py with appropriate options so the generated docs go into the docs directory, remove the autodoc files checked-in to git, and add .gitignore entries for the files apidoc generates. An example is in [openworm/owmeta](https://github.com/openworm/owmeta).

**Comment by nicholascar** [comment]
@mwatts15 thanks for both pointing this issue out and indicating how to do it. I'm going to work up to a 5.0.0 release of rdflib soon now and will try and include this method of documentation.

**Comment by white-gecko** [comment]
@nicholascar did you fix that already in the current doc?
