### ISSUE TITLE
xml:base not serialized in RF/XML format

### ISSUE THREAD

**Issue by dfsantamaria** [RDFLib/rdflib#940]
Even if I use the 'bind' method, in the output serialization, the xml:base is completely missed.
Just use:

g = rdflib.Graph()
g.parse(data=value)
g.serialize(format='xml')

No xml:base entry will be serialized, even if  it is in the original RDF file.

Minimal example:

f = open(file, "r")
value=f.read()
g=rdflib.Graph();
g.parse(data=value);
g.serialize(destination='out.rdf' ,format='xml')

**Comment by gjhiggins** [comment]
Unreproducible as is
