### ISSUE TITLE
Only URIRefs or Paths can be in paths!

### ISSUE THREAD

**Issue by charbull** [RDFLib/rdflib#944]
Hello, 

I am trying to run the example in https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.extras.html

And the following error `Only URIRefs or Paths can be in paths!` keeps occurring at `anonClass = EX.someProp | some | classD `

```
EX = Namespace('http://example.com/')
namespace_manager = NamespaceManager(Graph())
namespace_manager.bind('ex', EX, override=False)
namespace_manager.bind('owl', OWL_NS, override=False)
g = Graph()
g.namespace_manager = namespace_manager
Individual.factoryGraph = g
classD = Class(EX.D)
 anonClass = EX.someProp | some | classD 
```

Thank you

**Comment by JervenBolleman** [comment]
@charbull is it because some is not defined? I expect you want to make an restriction like someValuesFrom D?

**Comment by gjhiggins** [comment]
I've been meaning to look into this for some time. It transpires that the SPARQL paths.py code is triggering on the `|` delimiters used for the Infix class, hence the unexpected Exception. Happily, there is an alternative pair of delimiters: `<<` and `>>` and the examples all work when `| some |` is replaced by `<< some >>`, similarly for `| max |` and `<< max >>`.
