### ISSUE TITLE
Can I use rdflib to identify semantically identical sparql queries?

### ISSUE THREAD

**Issue by entslscheia** [RDFLib/rdflib#949]
For example, the following two queries are semantically identical:
`SELECT ?x WHERE { ?x foaf:haha ?k .\n ?person foaf:knows ?x .}`
`SELECT ?s WHERE { ?person foaf:knows ?s .\n ?s foaf:haha ?k .}`
Is there any api for me to determine they are identical in rdflib?
Many thanks!

**Comment by redmer** [comment]
You could try and see if you can do something with the query algebra

```
import rdflib.plugins.sparql as sparql

q1 = "SELECT ?x WHERE { ?x <http://xmlns.com/foaf/0.1/haha> ?k .\n ?person <http://xmlns.com/foaf/0.1/knows> ?x .}"
q2 = "SELECT ?s WHERE { ?person <http://xmlns.com/foaf/0.1/knows> ?s .\n ?s <http://xmlns.com/foaf/0.1/haha> ?k .}"

preparedQ1 = sparql.prepareQuery(q1)
preparedQ2 = sparql.prepareQuery(q2)

sparql.algebra.pprintAlgebra(preparedQ1)  # or preparedQ1.algebra
sparql.algebra.pprintAlgebra(preparedQ2)  # or preparedQ2.algebra
```

The are at least in abstract query algebra not the same, because query execution times of both queries can vary greatly depending on whether `foaf:haha` or `foaf:knows` is more salient.

**Comment by white-gecko** [comment]
Maybe this is a good question for stackoverflow https://stackoverflow.com/questions/tagged/rdflib

**Comment by gaurav19063** [comment]
Query similarity checker python file gives a score for how much semantically similar two SPARQL queries are.
