### ISSUE TITLE
Support casting fractions.Fraction to owl:rational

### ISSUE THREAD

**Issue by LEW21** [RDFLib/rdflib#953]
Right now `Literal(Fraction('2/3'))` produces `Literal('2/3')`.

It should produce `Literal('2/3', datatype=rdflib.term.URIRef('http://www.w3.org/2002/07/owl#rational'))` instead.

**Comment by JervenBolleman** [comment]
There is no 'rational' in the [resolved file](http://www.w3.org/2002/07/owl). This is however mentioned in [the OWL 2 standard](https://www.w3.org/TR/owl2-syntax/#Datatype_Maps).

Otherwise this looks like a reasonable request.

**Comment by JervenBolleman** [comment]
Code wise looks trivial, so I opened a pull request with a fix. I hope someone will merge it.

**Comment by nicholascar** [comment]
@LEW21 I've merged @JervenBolleman PR. If this looks good to you, can you please close this Issue? Thanks.

**Comment by LEW21** [comment]
Thanks @JervenBolleman and @nicholascar!
