### ISSUE TITLE
Importing ABC directly from collections was removed in Python 3.9 in favor of collections.abc

### ISSUE THREAD

**Issue by tirkarthi** [RDFLib/rdflib#956]
https://github.com/RDFLib/rdflib/blob/e00480271a6de85ea3e24b63c177b34340a5c2dd/rdflib/plugins/sparql/sparql.py#L6

**Comment by tirkarthi** [comment]
I will add a PR for this.

**Comment by tgbugs** [comment]
There is already a pull for this. https://github.com/RDFLib/rdflib/pull/950

**Comment by tirkarthi** [comment]
Thanks for the link. It will break Python 2 compatibility. I will add my comment there.

**Comment by nicholascar** [comment]
This functionality is now in master from PR #959 and will come out in the 5.0.0 release shortly.  @tirkarthi you might now test master and see if everything you need is there, if so, please close!

**Comment by tirkarthi** [comment]
Closing. Thanks for the details @nicholascar .
