### ISSUE TITLE
Serialization drops unused namespaces

### ISSUE THREAD

**Issue by Abbe98** [RDFLib/rdflib#965]
Sterilization drops unused namespaces even when those are explicitly bound to the graph:

```python
graph = Graph()
SOCH = Namespace('http://kulturarvsdata.se/ksamsok#')
PRES = Namespace('http://kulturarvsdata.se/presentation#')
graph.bind('ksam', SOCH)
graph.bind('pres', PRES)
print(graph.serialize(format='xml'))
```

Output:
`b'<?xml version="1.0" encoding="UTF-8"?>\n<rdf:RDF\n   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n>\n</rdf:RDF>\n'`

**Comment by tgbugs** [comment]
See https://github.com/RDFLib/rdflib/pull/914.

**Comment by nicholascar** [comment]
Is this perhaps an RDF/XML issue only? When I run that code for Turtle output from rdflib 4.2.2 (are you running with a build from `master` perhaps?) , I see the namespaces:

```
from rdflib import Graph, Namespace

graph = Graph()
SOCH = Namespace('http://kulturarvsdata.se/ksamsok#')
PRES = Namespace('http://kulturarvsdata.se/presentation#')
graph.bind('ksam', SOCH)
graph.bind('pres', PRES)
print(graph.serialize(format='turtle').decode('utf-8'))
```

I get:

```
@prefix ksam: <http://kulturarvsdata.se/ksamsok#> .
@prefix pres: <http://kulturarvsdata.se/presentation#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
```

**Comment by tgbugs** [comment]
4.2.2 does not have the issue. The change is cause by https://github.com/RDFLib/rdflib/pull/832

**Comment by nicholascar** [comment]
@tgbugs thanks for the confirmation of version. 

As per the thoughts in Issue #948 that you've commented on, I think we need to review Turtle 1.1 parsing/serialization generally which, as you've indicated, might be dependent on deeper CURIE suffix handling.

I've labelled this Turtle 1.1 to keep those issues together.

**Comment by nicholascar** [comment]
As of 5.0.0, unused namespaces are removed so the results at the top of this issue are expected/correct behaviour and therefore we are closing this issue.

If you want a prefix to appear in a serialised graph, you need to have at least one node that uses the prefix!
