### ISSUE TITLE
rdflib doesn't take namespace ends with underscore

### ISSUE THREAD

**Issue by Hendricks27** [RDFLib/rdflib#975]
After binding both following namespace to the graph, the PrettyXMLSerializer will ditch the first one and only use the second namespace for all URI under both namespace.

namespace1 = Namespace("http://purl.domain.org/dir/something_")
namespace2 = Namespace("http://purl.domain.org/dir/")

graph.bind("na", namespace1)
graph.bind("nb", namespace2)

Examples:
http://purl.domain.org/dir/aaa -> nb:aaa
http://purl.domain.org/dir/something_aaa -> nb:something_aaa
http://purl.domain.org/dir/something_0001 -> nb:something_0001

For the last 2 examples, what I really want is na:aaa and na:0001
Any idea what tricks do I need to use for it to work?
Thanks.

**Comment by Hendricks27** [comment]
However it works perfectly fine when parsing in:
xmlns:na="http://purl.domain.org/dir/something_"
<na:A0001></na:A0001>

**Comment by tgbugs** [comment]
What version of rdflib are you using. This should be fixed on master now by https://github.com/RDFLib/rdflib/pull/649.

**Comment by Hendricks27** [comment]
> What version of rdflib are you using? This should be fixed on master now by #649.

python 2.7.15 + rdflib 4.2.2

**Comment by Hendricks27** [comment]
import rdflib

outputGraph = rdflib.Graph()
Namespace = rdflib.Namespace
Literal = rdflib.Literal

n1 = Namespace("http://purl.domain.org/sub/abc_")
n2 = Namespace("http://purl.domain.org/sub/")

outputGraph.bind("na", n1)
outputGraph.bind("nb", n2)

for ns in outputGraph.namespace_manager.namespaces():
    print ns

root = rdflib.URIRef("http://purl.obolibrary.org/obo/gno.owl")

outputGraph.add((root, n1["X0001"], Literal("namespace abc_")))
outputGraph.add((root, n2["X0001"], Literal("namespace sub/")))

print outputGraph.serialize(format="pretty-xml")

-------------- output --------------

('xml', rdflib.term.URIRef(u'http://www.w3.org/XML/1998/namespace'))
('rdfs', rdflib.term.URIRef(u'http://www.w3.org/2000/01/rdf-schema#'))
('na', rdflib.term.URIRef(u'http://purl.domain.org/sub/abc_'))
('nb', rdflib.term.URIRef(u'http://purl.domain.org/sub/'))
('rdf', rdflib.term.URIRef(u'http://www.w3.org/1999/02/22-rdf-syntax-ns#'))
('xsd', rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#'))
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
  xmlns:nb="http://purl.domain.org/sub/"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>
  <rdf:Description rdf:about="http://purl.obolibrary.org/obo/gno.owl">
    <nb:abc_X0001>namespace abc_</nb:abc_X0001>
    <nb:X0001>namespace sub/</nb:X0001>
  </rdf:Description>
</rdf:RDF>

**Comment by Hendricks27** [comment]
Thanks a lot.
I can confirm it is fixed now.

**Comment by Hendricks27** [comment]
One extra issue I found.
It looks like the ID of prefix:ID starts with a number could not be recognized by the longest namespace.
Could it relate to the URL spliter(not sure I am using the right term)?


----------------
import rdflib # python2 with the rdflib on the master branch

outputGraph = rdflib.Graph()
Namespace = rdflib.Namespace
Literal = rdflib.Literal

n1 = Namespace("http://purl.domain.org/sub/")
n2 = Namespace("http://purl.domain.org/sub/abc_")

outputGraph.bind("ns", n1)
outputGraph.bind("ns____abc", n2)

for ns in outputGraph.namespace_manager.namespaces():
    print ns

root = rdflib.URIRef("http://purl.domain.org/")

outputGraph.add((root, rdflib.URIRef("http://purl.domain.org/sub/abc_0001"), Literal("")))
outputGraph.add((root, rdflib.URIRef("http://purl.domain.org/sub/abc_A0001"), Literal("")))
outputGraph.add((root, n2["0002"], Literal("")))
outputGraph.add((root, n2["A0002"], Literal("")))
outputGraph.add((root, n1["abc_0003"], Literal("")))
outputGraph.add((root, n1["abc_A0003"], Literal("")))
outputGraph.add((root, n2["000x4"], Literal("")))
outputGraph.add((root, n2["A000x4"], Literal("")))

print outputGraph.serialize(format="pretty-xml")


----- output -----

('xml', rdflib.term.URIRef(u'http://www.w3.org/XML/1998/namespace'))
('rdfs', rdflib.term.URIRef(u'http://www.w3.org/2000/01/rdf-schema#'))
('ns____abc', rdflib.term.URIRef(u'http://purl.domain.org/sub/abc_'))
('rdf', rdflib.term.URIRef(u'http://www.w3.org/1999/02/22-rdf-syntax-ns#'))
('xsd', rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#'))
('ns', rdflib.term.URIRef(u'http://purl.domain.org/sub/'))
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
  xmlns:ns____abc="http://purl.domain.org/sub/abc_"
  xmlns:ns="http://purl.domain.org/sub/"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>
  <rdf:Description rdf:about="http://purl.domain.org/">
    <ns____abc:A000x4></ns____abc:A000x4>
    <ns____abc:A0003></ns____abc:A0003>
    <ns____abc:A0001></ns____abc:A0001>
    <ns:abc_0003></ns:abc_0003>
    <ns:abc_000x4></ns:abc_000x4>
    <ns:abc_0002></ns:abc_0002>
    <ns:abc_0001></ns:abc_0001>
    <ns____abc:A0002></ns____abc:A0002>
  </rdf:Description>
</rdf:RDF>

**Comment by tgbugs** [comment]
I think that this is a limitation of xml qnames not of the internal representaiton of prefixes. Try serializing to ttl and it should work as expected.

**Comment by Hendricks27** [comment]
Ohhhh. Forgive my ignorance. Appreciate your help.
