### ISSUE TITLE
Serialization shows only partial substitution of namespace.

### ISSUE THREAD

**Issue by dannmartens** [RDFLib/rdflib#977]
I noticed something strange when serializing a graph to turtle, after binding a namespace prefix in code, the output shows a mix of prefix notation and full IRIs. I am using 4.2.2. While developing this part of the app, I noticed that in the output, the substitution comes and goes in an unpredictable manner.

In code:
```python
graph.namespace_manager.bind('mbse', URIRef('http://example.com/onto/v1/mbse#'))
graph.namespace_manager.bind('requirements', URIRef('http://example.com/api/v1/requirements/'))
```
Now, look at the "requirements" prefix:
```
@prefix co: <http://purl.org/co/> .
@prefix mbse: <http://example.com/onto/v1/mbse#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix requirements: <http://example.com/api/v1/requirements/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/api/v1/requirements/92c6e875-c721-4b2c-82ab-076de020d97e> a mbse:Requirement,
        owl:NamedIndidual ;
    co:member <http://example.com/api/v1/requirements/131fe437-5b49-4ab0-bee5-5ad5b0aa7a2f>,
        <http://example.com/api/v1/requirements/238f0f5d-28d6-4349-861d-d1d3a0cb3ce6>,
        <http://example.com/api/v1/requirements/42d6cd38-6858-48a8-88a6-db886eaf3bea>,
        <http://example.com/api/v1/requirements/4e33d5ee-5494-48a6-8aaa-d86240eecfbe>,
        <http://example.com/api/v1/requirements/5990ebbb-7023-4a4e-9bb6-34aff2bb6599>,
        <http://example.com/api/v1/requirements/708ef762-0c7e-4a11-84a3-4f84ddd28d42>,
        <http://example.com/api/v1/requirements/78ea66bc-ff55-4ffc-8c3d-a931c52e6811>,
        <http://example.com/api/v1/requirements/7e24a77f-cf1b-4285-b53b-e86230927a74>,
        <http://example.com/api/v1/requirements/8e410082-b85b-4184-8728-75f404415469>,
        requirements:a130d8ff-4482-4ffa-89c1-93da3e9fdf75,
        requirements:f384f799-4eac-44f2-b131-c1d47672fb55,
        requirements:f5252fbf-fe18-4959-a4a5-1a9b7b18dd0b,
        requirements:ff701a5d-dad6-41e8-8601-6651826245d4 .
```

Only a few are substituted: I can't make any sense of this behaviour.

**Comment by white-gecko** [comment]
Can you please write a test for this and submit the test as pull request?

**Comment by niklasl** [comment]
It seems that in the example, the prefixed form only occurs where the local part begins with a letter (and conversely the UUID:s in the full URI:s begin with a digit).

**Comment by dannmartens** [comment]
@niklasl You're right, I did not notice that before. Great catch!

That would explain why it appeared to come and go in some of my tests, where the UUIDs were generated on the fly.

**Comment by tgbugs** [comment]
This should already be fixed in master I think.

**Comment by white-gecko** [comment]
In which commit, PR?

**Comment by tgbugs** [comment]
Fairly sure this should have done it https://github.com/RDFLib/rdflib/pull/649/commits/348e8dc5caa1aec00650bf995ac86e9fb27fceb1 as part of https://github.com/RDFLib/rdflib/pull/649, and I think I added a regression test, but that may be in my tests for deterministic behavior in another repo.

**Comment by gauri-b** [comment]
Has a solution already been incorporated for this issue? or is it still open?

**Comment by dannmartens** [comment]
With v5.0.0, I see that the UUIDs are properly prefixed, regardless of the
value, starting with either a letter or a digit.

However, now none of the URN-based prefixes are substituted. They don't
even show up in the prefix declarations. I checked my code: they are bound
with the namespace manager. I even tried some explicit hard-coded bindings,
to no avail.

I'll continue to investigate to see if my code could be at fault. Maybe I
overlooked something.

**Comment by tgbugs** [comment]
Do you have examples of the URN issue?

**Comment by dannmartens** [comment]
I have forked the project and created a unit test, which fails on this issue.

In the test, 'isbn' is bound to 'urn:isbn:' (trailing colon). I use 'webn' as a vanilla namespace for comparison.

.Test Issue 977, serialization output:
---
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webn: <http://w3c.org/example/isbn/> .

webn:1503280780 rdfs:label "Moby Dick" .

<urn:isbn:1503280780> rdfs:label "Moby Dick" .

---

I test the namespace manager, as well: there the binding surfaces. It's just not serialized to turtle.

On a side note, I looked at some other tests to see what format they are submitted in, and I came across test_issue161.py, which might be related to this issue.

If this test seems alright to you, and if there are no specific formatting requirements I should be aware of, I will submit a pull request.

**Comment by nemesamade** [comment]
Hello, I can confirm that URN-based prefixes are still not being serialized into the .ttl format. Is this issue being looked into? I saw 
 that the related PR has been labeled wontfix. Are there any plans to resolve this issue?

**Comment by nemesamade** [comment]
I've opened a PR (https://github.com/RDFLib/rdflib/pull/1274) that addresses and resolves this issue by modifying namespace.py,  along with adding some tests for URN namespace handling by compute_qname and turtle serialization. The change didn't break any existing tests and passes the new tests so it should be an easy fix:)
