### ISSUE TITLE
Auto-detect RDF type from file extension in parse()

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#981]
`Graph().parse("some-file.ttl", format="turtle")` is a common way to load RDF into an rdflib Graph. We have methods such as `rdflib.util.guess_format()` to guess `format` from the file extensions so what we need now is for `guess_format()` to be triggered automatically if `format` is not given so `parse()` can be used like this:

```
Graph().parse("some-file.ttl")
```

**Comment by nicholascar** [comment]
`Graph().parse("some-file.ttl", format="turtle")` is a common way to load RDF into an rdflib Graph. We have methods such as `rdflib.util.guess_format()` to guess `format` from the file extensions so what we need now is for `guess_format()` to be triggered automatically if `format` is not given so `parse()` can be used like this:

```
Graph().parse("some-file.ttl")
```

**Comment by Tanish-Gupta** [comment]
Hi,
Is this issue still open?
