### ISSUE TITLE
Can I force string-escapes for turtle serialization

### ISSUE THREAD

**Issue by retorquere** [RDFLib/rdflib#982]
In serialization to turtle format, can I cause rdflib to serialize non-7-bit-ascii strings as string escapes (so either `'\u' hex hex hex hex` or `'\U' hex hex hex hex hex hex hex hex`)?

**Comment by nicholascar** [comment]
Can you please post this to StackOverflow, tagged with `[rdflib]`? That's the better place for "Can I..." questions. Issues here are really for bug or enhancement requests. Thanks.
