### ISSUE TITLE
rdflib.exceptions.ParserError: 

### ISSUE THREAD

**Issue by JiangChao52** [RDFLib/rdflib#983]
rdflib.exceptions.ParserError: 
two elements cannot use the same ID: 'http://oaei.ontologymatching.org/2011/benchmarks/207/onto.rdf#institution'
Could you fix this error? Thank you very much!

**Comment by nicholascar** [comment]
Sorry but I don't understand what you're asking: there really does appear to be an error in that RDF. 

Line 950:
```
<owl:ObjectProperty rdf:ID="institution">
```

Line 1045:
```
<owl:ObjectProperty rdf:ID="institution">
```
They are differnt properties with different domains & ranges.

Are you asking that rdflib should parse that RDF without an error?

**Comment by JiangChao52** [comment]
Yes，I want to parse this RDF successfully using the function : Graph().parse() although these two different properties are the same ID.

**Comment by nicholascar** [comment]
Well sorry, but we can’t just change the toolkit to cater for what I think is invalid RDF! 

If you can indicate that this is valid RDF, we will change the error handling accordingly. 

Since I’ve identified the duplicate property, you can just change one and then it will likely parse.

**Comment by JiangChao52** [comment]
Thank you, I have parsed the RDF successfully by changed one's ID.
I brought it up because I can parse this RDF using Jena.

**Comment by nicholascar** [comment]
Oh, thanks for letting me know about Jena parsing, I wonder what the difference in implementation is? I’ll leave this issue open until I’ve done a comparison.

**Comment by mwatts15** [comment]
Confirming @nicholascar 's assessment
From https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-ID-xml-base (emphasis added):
>  rdf:ID provides an additional check **since the same name can only appear once in the scope of an xml:base value** (or document, if none is given), so is useful for defining a set of distinct, related terms relative to the same IRI.

**Comment by nicholascar** [comment]
OK, whatever Jena's doing is wrong! Closing the issue as a result.
