### ISSUE TITLE
Add documentation for the use of load() or remove it

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#985]
`load()` just forwards on to `parse()`:

```turtle
    def load(self, source, publicID=None, format="xml"):
        self.parse(source, publicID, format)
```

I assume this is just to cater for a legacy function!

`load()` isn't documented in https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html?highlight=load#rdflib.graph.Graph.load. Either it should be, with any justification given for it over `parse()` perhaps, or it should be removed from rdflib.

I prefer removal in the breaking 6.0.0 release. We need to tidy up useless code.

**Comment by gjhiggins** [comment]
Removed after suitable deprecation period, in f30c5c25866925019775488f2db7edeb148da605, closing.
