### ISSUE TITLE
pip release is >3 years old

### ISSUE THREAD

**Issue by darrengarvey** [RDFLib/rdflib#986]
The README suggests installing from pip, but that is version 4.2.2, which was released on Jan 2017.

Can a new release be made? What is stopping it?

**Comment by white-gecko** [comment]
We are currently in the process of preparing the master branch for a 5.0.0 release. Our schedule is to finalize it by end of next week. You can read more about our plans on the mailing list: https://groups.google.com/forum/#!topic/rdflib-dev/VFuBLRIbnBs
