### ISSUE TITLE
Update testing triplestore version

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/rdflib#990]
We use an old version of Jena/Fuseki (2.4.0) for automated tests that require a SPARQL endpoint. We need to update to a more recent one (3.14.x).

**Comment by Tanish-Gupta** [comment]
Hi,
Does this issue still needs to be resolved?

**Comment by nicholascar** [comment]
Yes, it still does. I have to check though where the version or instance of Fuseki is set because I just ran some of the SPARQL tests for RDFlib against a local Fuseki instance that I installed that was the latest version.

So the question is: what version of Fuseki does the current code require? Does it care at all? Perhaps not - it depends on whatever you have installed to work with. So the issue needs to be explored before a solution is attempted.

**Comment by gjhiggins** [comment]
> We use an old version of Jena/Fuseki (2.4.0) for automated tests that require a SPARQL endpoint. We need to update to a more recent one (3.14.x).

As of release 6.1.1, the [version of fuseki used](https://github.com/RDFLib/rdflib/blob/6ed2ef48ed38679bcdafe7cae250a2ef4b315e7b/with-fuseki.sh#L113) is the latest available binary, v 3.17.0.

Closing as completed.
