### ISSUE TITLE
DOC: sphinx theme

### ISSUE THREAD

**Issue by westurner** [RDFLib/rdflib#994]
A few issues with the [sphinx theme](https://github.com/RDFLib/rdflib/tree/master/docs/_themes/armstrong):

- [x] The logo text is difficult to read
- [ ] There's insufficient padding between the topnav and the sidenav logo
- [x] The Quick Search background does not wrap the search bar

Here's a screenshot with latest FF; scrolled all the way to the top:
![Screenshot_2020-04-04 rdflib 4 2 2 — rdflib 4 2 2 documentation](https://user-images.githubusercontent.com/50891/78449997-5f31a280-7649-11ea-9176-bd3daec345d0.png)

**Comment by white-gecko** [comment]
The documentation was update for 5.0.0: https://rdflib.readthedocs.io/en/latest/ in #989 
Maybe the padding should still be increased.

**Comment by nicholascar** [comment]
As @white-gecko says, we've got a whole new theme and I've increased the padding in between the topnav and sidenav logo top.

Addressed in PR #1004
