### ISSUE TITLE
Incorrect use of 'is'

### ISSUE THREAD

**Issue by mertzjames** [RDFLib/rdflib#998]
https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/memory.py#L363

this should instead be:

```python
if triple is None or triple == (None,None,None):
```
I discovered this when running this and getting the following error:

> SyntaxWarning: "is" with a literal. Did you mean "=="?

**Comment by white-gecko** [comment]
The issue seams obvious but somehow I can't reproduce it. I'm running on python 3.7.

I've tried the following with the current rdflib 5.0.0rc1 non produced the warning.

    from rdflib.plugins.memory import IOMemory
    s = IOMemory()
    s.contexts()
    s.contexts(None)
    s.contexts(triple=None)
    s.contexts(triple=(None, None, None))

could you please tell me how to reproduce the warning?

**Comment by tgbugs** [comment]
Pretty sure the syntax warning only happens in 3.8.

**Comment by mertzjames** [comment]
That's correct.  The error was raised on Python 3.8.
